from common import D

SITES = []

SITES.append(D(
 slug="crane", name="LiftPro Crane Services", brand=("Lift", "Pro"), cat="Crane & Heavy Equipment", schema="HomeAndConstructionBusiness", theme="dark",
 acc="#f5b800", acc2="#ff7a18", on_acc="#14151a", font="bold", emoji="🏗️",
 title="Crane Hire in Kochi | LiftPro Mobile Crane & Heavy Lifting",
 desc="LiftPro Crane Services in Kochi: mobile crane hire from 10 to 100 tons with certified operators, rigging and 24×7 emergency support. Get a quote in 30 minutes.",
 h1=("Heavy lifting,", "done safely,", "on time"), badge=("24×7", "Emergency crane support"),
 lead="LiftPro provides mobile crane hire in Kochi from 10 to 100 tons with certified operators and full rigging support. Get a free site assessment and a quote within 30 minutes.",
 cta1="Get crane quote", wa_hero="Hi, I need a crane quote for a lifting job.",
 trust=["Certified operators", "Insured equipment", "Site visit & quote in 30 min"],
 chips=[("🏗️ 10–100 ton cranes", "mobile & hydraulic"), ("🛟 Fully insured", "equipment & operators")],
 glance=[("Capacity", "10 to 100 tons"), ("Response", "Quote in 30 minutes"), ("Support", "24×7 emergency"), ("Hire basis", "Hourly, daily, monthly")],
 glance_h="LiftPro Crane Services at a glance",
 glance_p="LiftPro Crane Services rents mobile and hydraulic cranes in Kochi and across Kerala, from 10 to 100 tons, with certified operators, rigging crew and insurance. Hire is available hourly, daily or monthly.",
 services_eye="Our fleet & services", services_h="Cranes and lifting for every job", services_p="Choose the right crane and crew for construction, industry and emergencies.",
 services=[("🏗️", "Mobile crane hire", "10 to 100 ton mobile cranes for construction and industrial lifts."),
  ("🔩", "Hydraulic & pick-and-carry", "Compact cranes for tight sites and quick pickups."),
  ("🏭", "Industrial erection", "Plant, machinery and structural steel erection with rigging."),
  ("🚧", "Construction lifting", "Precast, slabs, columns and material hoisting on site."),
  ("🚨", "Breakdown & recovery", "24×7 lifting and recovery for vehicles and equipment."),
  ("👷", "Operators & riggers", "Certified operators and rigging crew with every hire.")],
 why=("Lifting you can trust", "Safety, planning and the right equipment decide how a lift goes. We handle all three.",
      [("Certified, experienced operators", "Trained crew with years of site experience."),
       ("Insured and inspected cranes", "Regular maintenance and load testing."),
       ("Lift planning included", "Site assessment and a clear lift plan first."),
       ("Fast mobilisation", "Cranes dispatched quickly across Kerala.")]),
 stats=[("100 t", "Max capacity"), ("1,200+", "Lifts completed"), ("24×7", "Emergency service"), ("0", "Safety incidents (sample)")],
 plans_eye="Hire rates", plans_h="Transparent crane hire rates", plans_p="Sample starting rates. Final quote depends on site, duration and lift plan.",
 plans=[("Pick & carry 12T", "Light lifts", "1,800", "/hour", ["Operator included", "Min 4 hours", "Ideal for small sites", "Fuel extra"], "Book pick & carry"),
  ("Mobile crane 50T", "Most popular", "6,500", "/hour", ["Certified operator", "Rigging crew available", "Site visit included", "Insured lift"], "Get 50T quote"),
  ("Mobile crane 100T", "Heavy lifts", "12,000", "/hour", ["Heavy-duty crane", "Lift plan provided", "Escort support", "Insured lift"], "Get 100T quote")],
 show_eye="Recent lifts", show_h="Jobs we handle", show_p="A few of the lifts our crews handle every month.", work_nav="Projects",
 show=[("Precast beam erection", "50T · Highway project", "CONSTRUCTION", "🚧"), ("Transformer placement", "70T · Substation", "INDUSTRIAL", "⚡"), ("Steel roof truss lift", "25T · Warehouse", "STEEL", "🏭"), ("Vehicle recovery", "Emergency · 24×7", "RECOVERY", "🚨")],
 steps=[("Tell us the lift", "Share weight, height, radius and location."), ("Site assessment", "We visit, plan the lift and recommend the crane."), ("Quote in 30 minutes", "Clear rate with operator and rigging included."), ("Safe lift on time", "Crane, crew and supervision delivered on schedule.")],
 reviews=[("They planned the lift perfectly and finished before schedule.", "Rafeeq S.", "Site engineer"),
  ("Reliable crane and a very professional operator.", "Joseph M.", "Contractor"),
  ("Called at midnight for a breakdown and they were on site within an hour.", "Binu P.", "Fleet owner")],
 faq=[("How much does crane hire cost in Kochi?", "Mobile crane hire in Kochi starts around ₹1,800 per hour for a 12-ton pick-and-carry and ₹6,500 per hour for a 50-ton crane (sample rates). The final cost depends on duration, location and lift plan."),
  ("What crane capacities do you offer?", "We offer mobile, hydraulic and pick-and-carry cranes from 10 to 100 tons for construction, industrial and recovery jobs."),
  ("Do your cranes come with an operator?", "Yes. Every hire includes a certified operator, and rigging crew can be added for complex lifts."),
  ("How quickly can you send a crane?", "For urgent jobs we can mobilise a crane within hours in the Kochi region. We provide a quote within 30 minutes of your enquiry."),
  ("Are your cranes insured and inspected?", "Yes. Our cranes are insured, regularly inspected and load-tested, and each lift follows a written plan.")],
 areas=["Kochi", "Ernakulam", "Kalamassery", "Angamaly", "Thrissur", "Alappuzha"],
 offer=("Need a crane today?", "Share the lift details and get a quote with a site visit within 30 minutes.", "Get quote now"),
 hours_txt="Office Mon–Sat 8 AM – 7 PM · Emergency 24×7", hours_spec=[("Mo-Su", "00:00", "23:59")], addr="Industrial Area, Your Locality",
 map="Crane service near Kochi, Kerala", form_title="Get a crane quote", sel=("Crane needed", ["Pick & carry (10–15T)", "Mobile crane (25–50T)", "Heavy crane (70–100T)", "Not sure, need advice"]),
 extra=("Lift date & location", "text", "e.g. 12 Nov, Kakkanad"), intent="get a crane quote", nav_cta="Get quote",
))

SITES.append(D(
 slug="real-estate", name="Prime Nest Realty", brand=("Prime", "Nest"), cat="Real Estate", schema="RealEstateAgent",
 acc="#0b5d4b", acc2="#c9a227", bg="#fbfaf6", font="serif", emoji="🏙️",
 title="Prime Nest Realty Kochi | Flats, Villas & Plots for Sale",
 desc="Prime Nest Realty in Kochi: verified flats, villas and plots for sale and rent. Free site visits, legal help and home loan support. Find your home today.",
 h1=("Find a home", "you'll love", "in Kochi"), badge=("NEW", "12 verified listings this week"),
 lead="Prime Nest Realty helps you buy, sell and rent verified flats, villas and plots in Kochi. Enjoy free site visits, legal document checks and home loan support from start to finish.",
 cta1="Book a site visit", wa_hero="Hi, I would like to see available properties.",
 trust=["Verified listings only", "Free site visits", "Legal & loan support"],
 chips=[("🏠 300+ families", "settled (sample)"), ("📑 Legal check", "on every property")],
 glance=[("Properties", "Flats, villas, plots"), ("Budget", "From ₹25 lakh"), ("Services", "Buy · Sell · Rent"), ("Site visit", "Free")],
 glance_h="Prime Nest Realty at a glance",
 glance_p="Prime Nest Realty is a real estate agency in Kochi that lists verified apartments, villas and residential plots for sale and rent. We offer free site visits, document verification and home loan assistance.",
 services_eye="What we do", services_h="Buy, sell or rent with confidence", services_p="One team for property search, paperwork and finance.",
 services=[("🏢", "Apartments & flats", "1, 2 and 3 BHK flats in prime Kochi locations."),
  ("🏡", "Villas & independent homes", "Ready-to-move villas and gated community homes."),
  ("🌴", "Plots & land", "Clear-title residential plots with road access."),
  ("🔑", "Rentals & leasing", "Apartments, houses and shops for rent and lease."),
  ("📑", "Legal & documentation", "Title check, registration and agreement support."),
  ("🏦", "Home loan assistance", "Tie-ups with leading banks for quick approvals.")],
 why=("Property search without the stress", "We shortlist only verified properties that match your budget and location.",
      [("Verified, genuine listings", "Documents checked before we list."),
       ("Local market expertise", "Honest advice on price and locality."),
       ("End-to-end support", "From site visit to registration and loan."),
       ("No hidden charges", "Clear brokerage explained upfront.")]),
 stats=[("300+", "Families settled"), ("120+", "Active listings"), ("10+", "Years in Kochi"), ("5", "Bank partners")],
 plans_eye="Featured listings", plans_h="Properties you may like", plans_p="Sample listings for demo. Prices and details are illustrative.",
 plans=[("2 BHK flat, Kakkanad", "1,150 sq ft · Ready to move", "58", "lakh", ["2 bedrooms, 2 baths", "Covered parking", "Gym & clubhouse", "Near IT park"], "Book site visit"),
  ("3 BHK villa, Edappally", "1,800 sq ft · Gated", "1.15", "crore", ["3 bedrooms, 3 baths", "Private garden", "24×7 security", "Near metro"], "Book site visit"),
  ("8 cent plot, Aluva", "Clear title · Road access", "42", "lakh", ["Corner plot", "Approved layout", "All utilities nearby", "Bank loan eligible"], "Book site visit")],
 show_eye="Neighbourhoods", show_h="Popular areas in Kochi", show_p="Where our buyers and renters are looking.", work_nav="Areas",
 show=[("Kakkanad", "IT hub · flats from ₹40 L", "IT HUB", "🏢"), ("Edappally", "Metro · villas & flats", "CENTRAL", "🏙️"), ("Fort Kochi", "Heritage · homestays", "HERITAGE", "🏛️"), ("Aluva", "Plots · good value", "PLOTS", "🌴")],
 steps=[("Share your needs", "Budget, location, size and timeline."), ("Get a shortlist", "Verified options with photos and prices."), ("Visit & decide", "Free site visits at your convenience."), ("Close the deal", "Legal check, loan and registration support.")],
 reviews=[("They found us a flat within our budget in just two weeks.", "Anil & Meena", "Home buyers"),
  ("Very transparent. Documents were checked before we paid anything.", "Shaji T.", "Plot buyer"),
  ("Rented my apartment in 5 days. Highly professional.", "Priya L.", "Owner")],
 faq=[("How much does a 2 BHK flat cost in Kochi?", "A 2 BHK flat in Kochi typically costs between ₹45 lakh and ₹85 lakh depending on the area, builder and amenities (sample range). Our agents shortlist options within your budget."),
  ("Do you charge for site visits?", "No. Site visits are free. Brokerage is only charged when a deal is completed and is explained upfront."),
  ("Can you help with home loans?", "Yes. We work with partner banks for quick loan approvals and help with the paperwork."),
  ("Are your properties legally verified?", "We check title documents, tax receipts and approvals before listing a property, and can arrange a legal opinion on request."),
  ("Do you list properties for rent?", "Yes. We list apartments, houses and shops for rent and lease and handle agreements and tenant screening.")],
 offer=("Looking to buy or sell?", "Tell us what you need and get a shortlist of verified properties within 48 hours.", "Get property shortlist"),
 hours_txt="Mon–Sat 9:30 AM – 7 PM · Sun by appointment", hours_spec=[("Mo-Sa", "09:30", "19:00")], addr="MG Road, Your Locality", range="₹₹₹",
 map="Real estate agency near Kochi, Kerala", form_title="Find your property", sel=("I'm looking to", ["Buy a flat", "Buy a villa / house", "Buy a plot", "Rent a property", "Sell my property"]),
 extra=("Budget", "text", "e.g. ₹50–70 lakh"), intent="find a property", nav_cta="Find property",
))

SITES.append(D(
 slug="landscaping", name="GreenScape Landscaping", brand=("Green", "Scape"), cat="Landscaping & Gardens", schema="HomeAndConstructionBusiness", hero="center",
 acc="#2f9e5b", acc2="#a3d65c", bg="#fafdf7", font="sans", emoji="🌿",
 title="Landscaping & Garden Design in Kochi | GreenScape",
 desc="GreenScape Landscaping in Kochi: garden design, lawns, terrace gardens, water features and yearly garden maintenance. Free site visit and 3D plan.",
 h1=("Gardens that make", "every day", "feel better"), badge=("FREE", "Site visit & garden plan"),
 lead="GreenScape designs and builds gardens, lawns and terrace gardens in Kochi, with yearly maintenance plans from ₹2,500 a month. Book a free site visit and get a 3D garden plan.",
 cta1="Book free site visit", wa_hero="Hi, I would like a garden design site visit.",
 trust=["Free site visit", "3D garden plan", "Maintenance plans"],
 chips=[("🌳 600+ gardens", "built (sample)"), ("💧 Water-wise design", "low upkeep")],
 glance=[("Services", "Design · Build · Maintain"), ("Maintenance", "From ₹2,500 / month"), ("Site visit", "Free"), ("Project time", "7–30 days")],
 glance_h="GreenScape Landscaping at a glance",
 glance_p="GreenScape is a landscaping company in Kochi offering garden design, lawn installation, terrace and vertical gardens, water features, outdoor lighting and monthly maintenance. Site visits are free.",
 services_eye="Our services", services_h="From idea to a thriving garden", services_p="Design, planting and long-term care by experienced horticulturists.",
 services=[("🌿", "Garden design & build", "Complete landscape design with plants, paths and seating."),
  ("🌱", "Lawn installation", "Natural and artificial lawns with proper drainage."),
  ("🏠", "Terrace & balcony gardens", "Lightweight, waterproof rooftop gardens."),
  ("⛲", "Water features", "Ponds, fountains and waterfalls that add calm."),
  ("💡", "Outdoor lighting", "Warm, energy-efficient garden and pathway lighting."),
  ("🧑‍🌾", "Garden maintenance", "Monthly pruning, feeding, pest and lawn care.")],
 why=("Landscapes that last", "Right plants, right soil and a plan for upkeep, so your garden keeps looking great.",
      [("Climate-suited plants", "Species that thrive in Kerala weather."),
       ("3D plan before we start", "See your garden design before work begins."),
       ("Trained horticulturists", "Skilled crew, not just labour."),
       ("Maintenance plans", "Keep your garden fresh all year.")]),
 stats=[("600+", "Gardens created"), ("12", "Years of experience"), ("40+", "Skilled crew"), ("1 yr", "Plant care support")],
 plans_eye="Packages", plans_h="Garden packages", plans_p="Sample prices. Exact quote after a free site visit.",
 plans=[("Balcony refresh", "Small spaces", "9,999", "starting", ["Planters & plants", "Soil & drainage setup", "Vertical garden option", "1 month support"], "Get balcony quote"),
  ("Home garden", "Gardens up to 1,000 sq ft", "49,999", "starting", ["3D garden plan", "Lawn & plants", "Pathway & seating", "3 months care"], "Get garden quote"),
  ("Villa landscape", "Premium projects", "1,99,999", "starting", ["Full landscape design", "Water feature", "Lighting design", "1 year maintenance"], "Get villa quote")],
 show_eye="Gallery", show_h="Recent landscapes", show_p="Styles we build most often for Kerala homes.", work_nav="Gallery",
 show=[("Tropical front garden", "Villa · 1,200 sq ft", "TROPICAL", "🌴"), ("Terrace herb garden", "Apartment · 400 sq ft", "TERRACE", "🌿"), ("Zen courtyard", "Home · water feature", "COURTYARD", "⛲"), ("Lawn & lighting", "Villa · evening look", "LAWN", "💡")],
 steps=[("Free site visit", "We measure, check sun and soil, and listen to your ideas."), ("3D garden plan", "See the design and plant list before you approve."), ("Build & plant", "Our crew builds and plants in 7 to 30 days."), ("Care & maintenance", "Optional monthly care to keep it thriving.")],
 reviews=[("Our terrace is now our favourite place. Brilliant design.", "Neha R.", "Terrace garden"),
  ("The 3D plan matched the final garden exactly.", "Dr. Mathew K.", "Villa garden"),
  ("Maintenance team is regular and the lawn looks great all year.", "Biju S.", "Monthly plan")],
 faq=[("How much does garden landscaping cost in Kochi?", "Garden landscaping in Kochi typically starts around ₹9,999 for balconies and ₹49,999 for home gardens, with villa landscapes from ₹1,99,999 (sample prices). A free site visit gives an exact quote."),
  ("How long does it take to build a garden?", "Most gardens take 7 to 30 days depending on size, design and features such as water bodies and lighting."),
  ("Do you offer garden maintenance?", "Yes. Monthly maintenance plans start at ₹2,500 and cover pruning, feeding, pest control and lawn care."),
  ("Can you build a garden on my terrace?", "Yes. We build lightweight terrace gardens with proper waterproofing and drainage to protect your roof."),
  ("Which plants suit Kerala weather?", "We choose tropical and monsoon-tolerant plants and ornamental species that need less water, matched to your sun and space.")],
 offer=("Free site visit and 3D garden plan", "Book a visit this month and get a free concept plan for your garden.", "Book free visit"),
 hours_txt="Mon–Sat 8:30 AM – 6:30 PM", hours_spec=[("Mo-Sa", "08:30", "18:30")], addr="Nursery Road, Your Locality",
 map="Landscaping nursery near Kochi, Kerala", form_title="Book a free site visit", sel=("Service", ["Garden design & build", "Terrace / balcony garden", "Lawn installation", "Water feature", "Garden maintenance"]),
 extra=("Preferred visit date", "date", ""), intent="book a free garden site visit", nav_cta="Free visit",
))

SITES.append(D(
 slug="cleaning", name="SparkClean Services", brand=("Spark", "Clean"), cat="Cleaning Services", schema="LocalBusiness",
 acc="#0891b2", acc2="#34d399", bg="#f9fdfe", font="sans", emoji="🧼",
 title="Home & Office Cleaning in Kochi | SparkClean Services",
 desc="SparkClean Services in Kochi: deep home cleaning, office cleaning, sofa and carpet shampooing and move-in cleaning from ₹1,499. Trained staff, book online.",
 h1=("A cleaner space,", "booked in", "a minute"), badge=("TRUSTED", "Background-verified cleaners"),
 lead="SparkClean provides home and office cleaning in Kochi with trained, background-verified staff and eco-friendly products. Deep cleaning starts at ₹1,499 and you can book online in a minute.",
 cta1="Book a cleaning", wa_hero="Hi, I would like to book a cleaning service.",
 trust=["Verified staff", "Eco-friendly products", "Satisfaction guarantee"],
 chips=[("🏠 5,000+ homes", "cleaned (sample)"), ("✅ Re-clean guarantee", "if not satisfied")],
 glance=[("Deep clean from", "₹1,499"), ("Service", "Home & office"), ("Booking", "Same-day available"), ("Staff", "Verified & trained")],
 glance_h="SparkClean Services at a glance",
 glance_p="SparkClean Services offers deep home cleaning, office cleaning, kitchen and bathroom cleaning, sofa and carpet shampooing and move-in/move-out cleaning in Kochi. Deep cleaning starts at ₹1,499 with same-day booking.",
 services_eye="Our services", services_h="Cleaning for homes and offices", services_p="Choose a one-time deep clean or a regular plan.",
 services=[("🏠", "Home deep cleaning", "Top-to-bottom cleaning of every room, kitchen and bathroom."),
  ("🏢", "Office & commercial", "Daily, weekly or monthly cleaning for offices and shops."),
  ("🍳", "Kitchen & bathroom", "Grease, stain and limescale removal."),
  ("🛋️", "Sofa & carpet shampooing", "Deep extraction cleaning for fabric and rugs."),
  ("📦", "Move-in / move-out", "Spotless cleaning before you move in or hand over keys."),
  ("🪟", "Glass & facade", "Windows, glass partitions and balcony cleaning.")],
 why=("Clean you can see and feel", "Trained teams, proper equipment and a checklist for every job.",
      [("Verified, trained staff", "ID-checked cleaners with proper training."),
       ("Safe, eco-friendly products", "Child and pet-friendly chemicals."),
       ("Transparent pricing", "Fixed price based on your home size."),
       ("Re-clean guarantee", "Not satisfied? We'll re-clean at no cost.")]),
 stats=[("5,000+", "Homes cleaned"), ("4.8", "Average rating (sample)"), ("60+", "Trained cleaners"), ("Same day", "Booking available")],
 plans_eye="Pricing", plans_h="Clear, fixed pricing", plans_p="Sample prices. Final price depends on the size and condition of the space.",
 plans=[("1 BHK deep clean", "Up to 700 sq ft", "1,499", "/clean", ["All rooms & balcony", "Kitchen & bathroom", "Fans, lights, windows", "3–4 hour service"], "Book 1 BHK"),
  ("2 BHK deep clean", "Up to 1,200 sq ft", "2,499", "/clean", ["All rooms & balcony", "Kitchen degreasing", "Bathroom descaling", "4–6 hour service"], "Book 2 BHK"),
  ("Office cleaning", "Monthly plan", "7,999", "/month", ["Daily or weekly visits", "Trained staff", "Washroom hygiene", "Custom checklist"], "Get office quote")],
 show_eye="Our work", show_h="Popular services", show_p="What customers book most often.", work_nav="Popular",
 show=[("Kitchen deep clean", "Grease & chimney", "KITCHEN", "🍳"), ("Sofa shampoo", "5-seater · from ₹799", "SOFA", "🛋️"), ("Bathroom restore", "Tiles & fittings", "BATHROOM", "🚿"), ("Move-in clean", "Ready for new home", "MOVE-IN", "📦")],
 steps=[("Choose your service", "Pick home, office or a specific service."), ("Book a time slot", "Same-day and next-day slots available."), ("Our team arrives", "Verified staff with equipment and products."), ("Check & enjoy", "Walk through together. Re-clean if needed.")],
 reviews=[("Our flat looked brand new. Very polite and professional team.", "Reshma P.", "Home deep clean"),
  ("Booked monthly office cleaning. Consistent and reliable.", "Arjun V.", "Office client"),
  ("Sofa and carpets look amazing after shampooing.", "Fathima N.", "Sofa cleaning")],
 faq=[("How much does home deep cleaning cost in Kochi?", "Home deep cleaning in Kochi at SparkClean starts at ₹1,499 for a 1 BHK and ₹2,499 for a 2 BHK (sample prices). The price depends on size and condition."),
  ("How long does a deep cleaning take?", "A 1 BHK takes about 3 to 4 hours and a 2 BHK 4 to 6 hours with a team of cleaners."),
  ("Do I need to provide cleaning materials?", "No. Our team brings equipment and eco-friendly cleaning products. You only need to provide water and power."),
  ("Do you offer regular office cleaning?", "Yes. Offices can choose daily, weekly or monthly plans with a custom cleaning checklist."),
  ("What if I am not satisfied?", "Tell us within 24 hours and we will re-clean the affected areas at no extra cost.")],
 offer=("Book a cleaning in 60 seconds", "Choose your service, pick a slot and relax. Same-day booking available.", "Book now"),
 hours_txt="Every day 7 AM – 8 PM", hours_spec=[("Mo-Su", "07:00", "20:00")], range="₹₹",
 map="Cleaning services near Kochi, Kerala", form_title="Book a cleaning service", sel=("Service", ["Home deep cleaning", "Office cleaning", "Kitchen & bathroom", "Sofa / carpet shampoo", "Move-in / move-out"]),
 extra=("Preferred date", "date", ""), intent="book a cleaning service", nav_cta="Book now",
))

SITES.append(D(
 slug="auditorium", name="Grand Hall Auditorium", brand=("Grand", "Hall"), cat="Auditorium & Event Venue", schema="LocalBusiness", theme="dark", hero="center",
 acc="#8b5cf6", acc2="#f472b6", font="grotesk", emoji="🎭",
 title="Auditorium Booking in Kochi | Grand Hall for Weddings",
 desc="Grand Hall Auditorium in Kochi: 800-seat AC hall for weddings, conferences and cultural events with stage, parking and catering. Check dates and book online.",
 h1=("The perfect stage for", "every big", "occasion"), badge=("800 SEATS", "Fully air-conditioned hall"),
 lead="Grand Hall is an 800-seat air-conditioned auditorium in Kochi for weddings, conferences, concerts and school events, with stage, sound, parking for 150 vehicles and in-house catering.",
 cta1="Check available dates", wa_hero="Hi, I would like to check auditorium availability.",
 trust=["800 seats, fully AC", "Parking for 150 cars", "In-house catering"],
 chips=[("🎤 Pro sound & lights", "included"), ("🅿️ 150 car parking", "free for guests")],
 glance=[("Capacity", "800 seated / 1,200 standing"), ("Rent from", "₹35,000 / day"), ("Parking", "150 cars"), ("Catering", "In-house & outside")],
 glance_h="Grand Hall Auditorium at a glance",
 glance_p="Grand Hall Auditorium in Kochi seats up to 800 guests in an air-conditioned hall with stage, lighting, sound, green rooms and parking for 150 vehicles. Rent starts at ₹35,000 per day and catering is available.",
 services_eye="Events we host", services_h="A venue for every celebration", services_p="Flexible layouts, full event support and a hassle-free booking process.",
 services=[("💍", "Weddings & receptions", "Elegant hall with stage, dining and bridal rooms."),
  ("🏢", "Conferences & seminars", "Projector, mics and seating layouts for business events."),
  ("🎶", "Concerts & cultural events", "Professional stage, sound and lighting setup."),
  ("🎓", "School & college events", "Annual days, graduations and competitions."),
  ("🎂", "Birthdays & anniversaries", "Smaller layouts and decor for family functions."),
  ("🍽️", "Catering & decoration", "In-house catering and preferred decorators.")],
 why=("Everything under one roof", "Book once and we help with stage, sound, parking and guests on the day.",
      [("Spacious AC hall", "Comfortable seating for 800 guests."),
       ("Professional AV included", "Sound system, lights and a large stage."),
       ("Ample parking", "150 cars and 200 two-wheelers."),
       ("Dedicated event manager", "One contact from booking to cleanup.")]),
 stats=[("800", "Seating capacity"), ("150", "Car parking slots"), ("1,000+", "Events hosted"), ("2", "Green rooms")],
 plans_eye="Booking rates", plans_h="Hall rental packages", plans_p="Sample rates. Final quote depends on date, duration and services.",
 plans=[("Half day", "Up to 5 hours", "20,000", "/event", ["AC hall & lights", "Basic sound system", "Parking access", "2 green rooms"], "Check half day"),
  ("Full day", "Weddings & big events", "35,000", "/day", ["Hall + stage + dining area", "Pro sound & lights", "Event manager", "Free parking"], "Check full day"),
  ("Premium", "Hall + catering + decor", "85,000", "/day", ["Full-day hall", "Catering for 300", "Stage & floral decor", "Dedicated team"], "Get premium quote")],
 show_eye="The venue", show_h="Spaces in the venue", show_p="Everything you need for a smooth event.", work_nav="Venue",
 show=[("Main auditorium", "800 seats · AC", "HALL", "🎭"), ("Dining hall", "300 guests at a time", "DINING", "🍽️"), ("Bridal & green rooms", "2 rooms with AC", "ROOMS", "👰"), ("Parking area", "150 cars · 200 bikes", "PARKING", "🅿️")],
 steps=[("Check the date", "Message us your preferred date and event type."), ("Visit & plan", "See the hall and plan layout and services."), ("Pay advance", "Confirm the date with a simple advance."), ("Enjoy your event", "Our team supports you on the day.")],
 reviews=[("Perfect venue for our wedding. Guests loved the space and parking.", "Suresh & Anu", "Wedding reception"),
  ("Smooth conference. Sound and projection were excellent.", "Dr. Nair", "Conference organiser"),
  ("Our school annual day went flawlessly.", "Principal, St. Mary's", "School event")],
 faq=[("How much does it cost to book an auditorium in Kochi?", "Grand Hall rents from ₹35,000 per day, with half-day options from ₹20,000 (sample rates). The final cost depends on the date, duration and services you add."),
  ("What is the seating capacity of Grand Hall?", "The hall seats up to 800 guests in theatre style and holds around 1,200 for standing events."),
  ("Is catering available?", "Yes. We offer in-house catering and also allow approved external caterers."),
  ("How do I check available dates?", "Message us on WhatsApp or fill the form with your preferred date. We confirm availability quickly."),
  ("Is parking available for guests?", "Yes. We have parking for 150 cars and 200 two-wheelers at no extra charge.")],
 areas=["Kochi", "Ernakulam", "Kakkanad", "Aluva", "Thrippunithura", "Angamaly"],
 offer=("Planning an event? Check your date", "Dates fill quickly in the wedding season. Check availability today.", "Check dates"),
 hours_txt="Office Mon–Sat 9 AM – 7 PM", hours_spec=[("Mo-Sa", "09:00", "19:00")], addr="Convention Road, Your Locality", range="₹₹₹",
 map="Auditorium near Kochi, Kerala", form_title="Check availability", sel=("Event type", ["Wedding / reception", "Conference / seminar", "Cultural / concert", "School / college event", "Birthday / anniversary"]),
 extra=("Event date", "date", ""), intent="check auditorium availability", nav_cta="Check dates",
))

SITES.append(D(
 slug="interior", name="Haven Interiors", brand=("Haven", " Interiors"), cat="Interior Design", schema="HomeAndConstructionBusiness",
 acc="#a8643a", acc2="#e0b184", bg="#fcfaf7", font="serif", emoji="🛋️",
 title="Interior Designers in Kochi | Haven Interiors",
 desc="Haven Interiors in Kochi: modular kitchens, wardrobes, living rooms and full-home interior design from ₹799/sq ft. Free consultation and 3D design.",
 h1=("Interiors that feel", "like", "you"), badge=("FREE", "Design consultation & 3D layout"),
 lead="Haven Interiors designs and delivers homes and offices in Kochi, from modular kitchens to full-home interiors starting at ₹799 per sq ft. Get a free consultation and 3D layout.",
 cta1="Book free consultation", wa_hero="Hi, I would like a free interior design consultation.",
 trust=["Free 3D design", "45-day delivery", "5-year warranty"],
 chips=[("🏠 400+ homes", "designed (sample)"), ("🛡️ 5-year warranty", "on woodwork")],
 glance=[("Full-home from", "₹799 / sq ft"), ("Delivery", "45–60 days"), ("Warranty", "5 years"), ("Consultation", "Free, 3D design")],
 glance_h="Haven Interiors at a glance",
 glance_p="Haven Interiors is an interior design company in Kochi offering modular kitchens, wardrobes, living and bedroom interiors and office fit-outs. Full-home interiors start at ₹799 per sq ft with a 5-year warranty.",
 services_eye="What we design", services_h="Interiors for every room", services_p="Design, manufacturing and installation handled by one team.",
 services=[("🍳", "Modular kitchens", "Smart, durable kitchens with soft-close fittings."),
  ("👗", "Wardrobes & storage", "Space-saving wardrobes tailored to your room."),
  ("🛋️", "Living & dining", "TV units, false ceilings, lighting and furniture."),
  ("🛏️", "Bedrooms", "Comfortable, calming bedroom designs."),
  ("🏢", "Office interiors", "Productive, branded workspaces and reception areas."),
  ("🏠", "Full-home interiors", "Turnkey design and execution for your new home.")],
 why=("Design that fits your life", "We design around how you live and handle everything until the keys are yours.",
      [("Free 3D design", "See your home before we build it."),
       ("In-house factory", "Quality control and on-time delivery."),
       ("Transparent quotes", "Itemised costs with no surprises."),
       ("5-year warranty", "On woodwork and fittings.")]),
 stats=[("400+", "Homes designed"), ("45 days", "Typical delivery"), ("5 yrs", "Warranty"), ("12+", "Designers")],
 plans_eye="Pricing", plans_h="Interior packages", plans_p="Sample starting prices per sq ft. Exact quote after consultation.",
 plans=[("Essential", "Practical & affordable", "799", "/sq ft", ["Modular kitchen & wardrobes", "BWP plywood, laminate finish", "Soft-close hardware", "3D design included"], "Get Essential quote"),
  ("Premium", "Most chosen", "1,299", "/sq ft", ["Full-home interior", "Premium finishes", "False ceiling & lighting", "Dedicated designer"], "Get Premium quote"),
  ("Luxury", "Bespoke design", "1,999", "/sq ft", ["Custom furniture", "Imported finishes", "Smart-home options", "Project manager"], "Get Luxury quote")],
 show_eye="Portfolio", show_h="Recent projects", show_p="A few spaces we've designed and delivered.", work_nav="Portfolio",
 show=[("Contemporary 3 BHK", "Kakkanad · 1,600 sq ft", "FULL HOME", "🏠"), ("L-shaped modular kitchen", "Edappally · acrylic finish", "KITCHEN", "🍳"), ("Master bedroom suite", "Aluva · walk-in wardrobe", "BEDROOM", "🛏️"), ("Startup office", "Infopark · 2,000 sq ft", "OFFICE", "🏢")],
 steps=[("Free consultation", "Share your needs and budget with our designer."), ("3D design & quote", "Review layouts and a clear itemised estimate."), ("Manufacturing", "Built in our factory under quality checks."), ("Installation & handover", "On-site fitting and a final walkthrough.")],
 reviews=[("Our flat was delivered on the promised date and looks stunning.", "Anitha & Roy", "3 BHK client"),
  ("The kitchen design was practical and beautiful.", "Mini J.", "Kitchen client"),
  ("Professional team and honest quotation.", "Vivek S.", "Office client")],
 faq=[("How much does interior design cost in Kochi?", "Interior design in Kochi at Haven starts around ₹799 per sq ft for the Essential package and ₹1,299 per sq ft for Premium (sample prices). A free consultation gives you an exact quote."),
  ("How long does a full-home interior take?", "Most full-home projects take 45 to 60 days from design approval to handover."),
  ("Do you provide 3D designs?", "Yes. A 3D design of your layout is included free with your consultation so you can see the final look."),
  ("What warranty do you offer?", "We offer a 5-year warranty on woodwork and fittings, with after-sales service."),
  ("Can I design only my kitchen or wardrobe?", "Yes. You can order a single kitchen, wardrobe or room instead of a full-home package.")],
 offer=("Free interior consultation and 3D design", "Book a visit this month. No obligation.", "Book free consultation"),
 hours_txt="Mon–Sat 9:30 AM – 6:30 PM", hours_spec=[("Mo-Sa", "09:30", "18:30")], addr="Design Studio, Your Locality", range="₹₹₹",
 map="Interior design studio near Kochi, Kerala", form_title="Book a free consultation", sel=("Project", ["Full-home interior", "Modular kitchen", "Wardrobes", "Living / bedroom", "Office interior"]),
 extra=("Property type & size", "text", "e.g. 3 BHK, 1,400 sq ft"), intent="book a free interior consultation", nav_cta="Free quote",
))

SITES.append(D(
 slug="photography", name="Frame & Light Studio", brand=("Frame", "&Light"), cat="Photography Studio", schema="LocalBusiness", theme="dark", hero="center",
 acc="#d4ff3a", acc2="#4dffb8", on_acc="#10120a", font="grotesk", emoji="📸",
 title="Wedding Photographers in Kochi | Frame & Light Studio",
 desc="Frame & Light Studio in Kochi: wedding, pre-wedding, baby and event photography and films from ₹15,000. Check your date and view packages.",
 h1=("Moments worth", "keeping,", "beautifully"), badge=("2026", "Wedding season bookings open"),
 lead="Frame & Light is a photography studio in Kochi for weddings, pre-wedding shoots, babies and events, with packages from ₹15,000. Check your date and see how we capture your story.",
 cta1="Check my date", wa_hero="Hi, I would like to check my date for a photo shoot.",
 trust=["Candid & cinematic", "Edited album in 30 days", "Drone & film options"],
 chips=[("📷 500+ weddings", "shot (sample)"), ("🎬 Cinematic films", "4K highlights")],
 glance=[("Packages from", "₹15,000"), ("Delivery", "Photos in 10 days"), ("Album", "Within 30 days"), ("Travel", "Across Kerala")],
 glance_h="Frame & Light Studio at a glance",
 glance_p="Frame & Light Studio is a photography and videography studio in Kochi covering weddings, pre-wedding shoots, newborn and family portraits, product shoots and events. Packages start at ₹15,000 and travel across Kerala is available.",
 services_eye="What we shoot", services_h="Photography for every story", services_p="Candid, cinematic and carefully edited.",
 services=[("💍", "Wedding photography", "Candid and traditional coverage of your whole celebration."),
  ("💞", "Pre-wedding shoots", "Creative outdoor and studio couple sessions."),
  ("👶", "Baby & family portraits", "Gentle newborn, maternity and family sessions."),
  ("🎬", "Cinematic films", "4K wedding and event films with drone shots."),
  ("🛍️", "Product & brand shoots", "Clean images for e-commerce and social media."),
  ("🎉", "Events & corporate", "Conferences, launches and parties covered well.")],
 why=("Stories told with care", "We blend into your day, stay candid and deliver images you will treasure.",
      [("Experienced team", "Lead photographer, assistant and film crew."),
       ("Fast delivery", "Preview in 3 days, full gallery in 10 days."),
       ("Premium albums", "Handcrafted albums and prints."),
       ("Backup & safety", "Every shoot backed up in two places.")]),
 stats=[("500+", "Weddings shot"), ("8", "Years of experience"), ("10 days", "Gallery delivery"), ("4K", "Film quality")],
 plans_eye="Packages", plans_h="Photography packages", plans_p="Sample prices. Customised quotes for multi-day events.",
 plans=[("Essential", "Small functions", "15,000", "/event", ["1 photographer", "6 hours coverage", "300 edited photos", "Online gallery"], "Check Essential"),
  ("Signature", "Most popular wedding pack", "65,000", "/wedding", ["Photo + video team", "Full-day coverage", "Premium album", "Highlight film"], "Check Signature"),
  ("Cinematic", "Premium storytelling", "1,25,000", "/wedding", ["2 photographers + 2 cinematographers", "Drone coverage", "Pre-wedding shoot included", "Feature film + 2 albums"], "Check Cinematic")],
 show_eye="Portfolio", show_h="Recent work", show_p="A glimpse of our recent shoots.", work_nav="Portfolio",
 show=[("Kochi wedding", "Candid · 2 days", "WEDDING", "💍"), ("Munnar pre-wedding", "Hill station shoot", "PRE-WEDDING", "🏞️"), ("Newborn session", "Studio · 3 hrs", "BABY", "👶"), ("Brand shoot", "Product · social", "COMMERCIAL", "🛍️")],
 steps=[("Share your date", "Tell us the date, venue and style you like."), ("Plan & quote", "A package and shot list made for you."), ("The shoot", "We capture candid and posed moments."), ("Edit & deliver", "Gallery, album and films delivered on time.")],
 reviews=[("They captured every emotion. Our album is a treasure.", "Anjana & Rohan", "Wedding clients"),
  ("Very professional and so patient with our baby.", "Seema M.", "Family shoot"),
  ("Fast delivery and great edits for our brand launch.", "Karthik R.", "Brand client")],
 faq=[("How much does a wedding photographer cost in Kochi?", "Wedding photography in Kochi at Frame & Light starts around ₹65,000 for a full-day photo and video package, with essential event coverage from ₹15,000 (sample prices)."),
  ("How soon do we get the photos?", "You get a preview gallery in about 3 days and the full edited gallery in around 10 days. Albums take about 30 days."),
  ("Do you travel outside Kochi?", "Yes. We cover weddings and shoots across Kerala and beyond. Travel costs are added to the quote."),
  ("Do you offer drone and video coverage?", "Yes. Packages can include 4K video, cinematic highlight films and drone shots where permitted."),
  ("How do I confirm my date?", "Share your date on WhatsApp, and pay a small advance to block it. Dates are booked on a first-come basis.")],
 offer=("Wedding season dates are filling fast", "Message us your date to check availability and get a custom quote.", "Check my date"),
 hours_txt="Studio Mon–Sat 10 AM – 7 PM", hours_spec=[("Mo-Sa", "10:00", "19:00")], addr="Studio Road, Your Locality", range="₹₹",
 map="Photography studio near Kochi, Kerala", form_title="Check your date", sel=("Shoot type", ["Wedding", "Pre-wedding", "Baby / family", "Product / brand", "Event / corporate"]),
 extra=("Event date", "date", ""), intent="check my shoot date", nav_cta="Check date",
))
