from common import D

SITES = []

SITES.append(D(
 slug="wedding", name="Eternal Vows Weddings", brand=("Eternal", "Vows"), cat="Wedding Planner", schema="LocalBusiness",
 acc="#9f1239", acc2="#e0a458", bg="#fffaf7", font="serif", emoji="💍",
 title="Wedding Planners in Kochi | Eternal Vows Weddings & Events",
 desc="Eternal Vows in Kochi: full wedding planning, decor, catering coordination and destination weddings from ₹1.5 lakh. Book a free planning call.",
 h1=("Your dream wedding,", "planned", "to perfection"), badge=("FREE", "Wedding planning call"),
 lead="Eternal Vows is a wedding planning company in Kochi handling decor, catering, photography, entertainment and guest care, with packages from ₹1.5 lakh. Book a free planning call.",
 cta1="Book planning call", wa_hero="Hi, I would like to plan my wedding.",
 trust=["End-to-end planning", "Trusted vendors", "Fixed budget promise"],
 chips=[("💐 350+ weddings", "planned (sample)"), ("🧿 One point of contact", "for everything")],
 glance=[("Packages from", "₹1.5 lakh"), ("Services", "Planning · Decor · Coordination"), ("Guests", "100 to 2,000"), ("Planning call", "Free")],
 glance_h="Eternal Vows Weddings at a glance",
 glance_p="Eternal Vows Weddings is a wedding planner in Kochi offering full wedding planning, stage and floral decor, catering coordination, photography, entertainment and destination weddings. Packages start at ₹1.5 lakh.",
 services_eye="What we plan", services_h="Every detail, handled", services_p="From the first idea to the last dance, we take care of it so you can enjoy it.",
 services=[("📋", "Full wedding planning", "Complete planning, timeline and vendor management."),
  ("💐", "Stage & floral decor", "Themed mandaps, stage design and floral arrangements."),
  ("🍽️", "Catering coordination", "Menus, tasting and service for all your functions."),
  ("📸", "Photo & video partners", "Trusted photographers and cinematographers."),
  ("🎶", "Music & entertainment", "DJ, live bands, choreography and emcees."),
  ("🏝️", "Destination weddings", "Complete planning for weddings away from home.")],
 why=("Peace of mind, start to finish", "One team, one plan, one budget. You enjoy the celebration and we handle the rest.",
      [("A dedicated wedding planner", "One contact for all your functions."),
       ("Trusted vendor network", "Negotiated rates and reliable service."),
       ("Budget transparency", "Itemised costs and no hidden charges."),
       ("On-the-day team", "Coordinators for every function and guest.")]),
 stats=[("350+", "Weddings planned"), ("10+", "Years of experience"), ("60+", "Vendor partners"), ("100%", "Budget transparency")],
 plans_eye="Packages", plans_h="Wedding planning packages", plans_p="Sample prices. Custom quotes for multi-day weddings.",
 plans=[("Day-of coordination", "You plan, we manage", "1,50,000", "starting", ["Timeline & rehearsal", "On-site team", "Vendor coordination", "Guest management"], "Get coordination quote"),
  ("Full planning", "Most popular", "4,50,000", "starting", ["Complete planning", "Stage & floral decor", "Catering coordination", "Entertainment & photo team"], "Get full planning quote"),
  ("Destination wedding", "Weddings away", "9,00,000", "starting", ["Venue & travel planning", "Guest accommodation", "Multi-day events", "Dedicated team"], "Get destination quote")],
 show_eye="Portfolio", show_h="Recent celebrations", show_p="A glimpse of weddings we've planned.", work_nav="Portfolio",
 show=[("Floral mandap wedding", "Kochi · 600 guests", "DECOR", "💐"), ("Beach wedding", "Kovalam · 150 guests", "DESTINATION", "🏝️"), ("Sangeet night", "Choreography + DJ", "SANGEET", "🎶"), ("Traditional Kerala wedding", "Temple + reception", "TRADITIONAL", "🪔")],
 steps=[("Free planning call", "Share your vision, date and budget."), ("Custom proposal", "A plan with decor, vendors and timeline."), ("Planning & booking", "We confirm venues and vendors for you."), ("Your big day", "Our team runs every function smoothly.")],
 reviews=[("They handled everything and we simply enjoyed our wedding.", "Neha & Aravind", "Wedding clients"),
  ("Beautiful decor within budget. Very caring team.", "Smitha K.", "Bride's mother"),
  ("Our destination wedding was flawless.", "Rohit & Maya", "Destination wedding")],
 faq=[("How much does a wedding planner cost in Kochi?", "Wedding planners in Kochi typically charge from ₹1.5 lakh for day-of coordination and from about ₹4.5 lakh for full planning, depending on scale (sample prices)."),
  ("How early should I book a wedding planner?", "We recommend booking 4 to 8 months before your wedding, and earlier for peak seasons or destination weddings."),
  ("Do you plan destination weddings?", "Yes. We plan and manage destination weddings including venue, travel, accommodation and entertainment."),
  ("Can I use my own vendors?", "Yes. You can bring your preferred vendors and we will coordinate them with our team."),
  ("What is included in full wedding planning?", "Full planning covers budgeting, venue, decor, catering coordination, entertainment, guest management and on-the-day coordination.")],
 offer=("Plan your wedding with us", "Book a free planning call. We'll share ideas and a custom budget.", "Book planning call"),
 hours_txt="Mon–Sat 10 AM – 7 PM", hours_spec=[("Mo-Sa", "10:00", "19:00")], addr="Boulevard Road, Your Locality", range="₹₹₹",
 map="Wedding planner near Kochi, Kerala", form_title="Book a free planning call", sel=("Planning for", ["Full wedding", "Engagement / reception", "Destination wedding", "Decor only", "Day-of coordination"]),
 extra=("Wedding date & guests", "text", "e.g. 20 Feb, 400 guests"), intent="book a wedding planning call", nav_cta="Free call",
))

SITES.append(D(
 slug="car-care", name="AutoSpa Car Care", brand=("Auto", "Spa"), cat="Car Detailing & Garage", schema="AutoRepair", theme="dark",
 acc="#22d3ee", acc2="#3b82f6", on_acc="#04141a", font="bold", emoji="🚗",
 title="Car Detailing & Ceramic Coating in Kochi | AutoSpa Car Care",
 desc="AutoSpa Car Care in Kochi: car detailing, ceramic coating, PPF, interior cleaning and servicing. Packages from ₹999. Book a slot with doorstep pickup.",
 h1=("Make your car", "look brand", "new again"), badge=("PICKUP", "Free doorstep pickup & drop"),
 lead="AutoSpa Car Care is a car detailing studio in Kochi offering ceramic coating, paint protection film, deep interior cleaning and servicing. Washes start at ₹999 with free pickup and drop.",
 cta1="Book a slot", wa_hero="Hi, I would like to book a car detailing slot.",
 trust=["Free pickup & drop", "Certified coating products", "Warranty on coatings"],
 chips=[("🚗 3,000+ cars", "detailed (sample)"), ("🛡️ Up to 5-year coating", "warranty")],
 glance=[("Packages from", "₹999"), ("Ceramic coating", "From ₹9,999"), ("Pickup & drop", "Free"), ("Turnaround", "Same day to 3 days")],
 glance_h="AutoSpa Car Care at a glance",
 glance_p="AutoSpa Car Care is a car detailing and care studio in Kochi offering foam wash, interior deep cleaning, ceramic coating, paint protection film, polishing and servicing. Packages start at ₹999 with free pickup and drop.",
 services_eye="Our services", services_h="Complete care for your car", services_p="Detailing, protection and servicing under one roof.",
 services=[("🫧", "Foam wash & detailing", "Premium wash, polish and interior vacuum."),
  ("🛡️", "Ceramic coating", "Long-lasting gloss and paint protection."),
  ("🧱", "Paint protection film (PPF)", "Self-healing film against scratches and stone chips."),
  ("🪑", "Interior deep cleaning", "Seats, roof, carpets and AC vents sanitised."),
  ("✨", "Polishing & scratch removal", "Restore shine and remove swirl marks."),
  ("🔧", "Servicing & repairs", "Periodic service, AC and denting-painting.")],
 why=("Care your car deserves", "Proper products, trained technicians and honest advice on what your car really needs.",
      [("Certified products", "Genuine coating and PPF brands."),
       ("Trained technicians", "Skilled in detailing and paint correction."),
       ("Doorstep pickup & drop", "No need to leave your day behind."),
       ("Warranty on coatings", "Written warranty with every coating.")]),
 stats=[("3,000+", "Cars detailed"), ("8", "Years in business"), ("5 yrs", "Max coating warranty"), ("Free", "Pickup & drop")],
 plans_eye="Packages", plans_h="Detailing packages", plans_p="Sample prices for hatchback/sedan. SUV and luxury cars vary.",
 plans=[("Foam wash & interior", "Monthly refresh", "999", "/car", ["Foam wash", "Interior vacuum", "Dashboard polish", "Tyre dressing"], "Book wash"),
  ("Deep detailing", "Most popular", "4,999", "/car", ["Interior deep cleaning", "Exterior polish", "Engine bay cleaning", "Odour treatment"], "Book detailing"),
  ("Ceramic coating", "Long-term protection", "9,999", "/car", ["Paint correction", "9H ceramic coating", "Up to 5-year warranty", "Maintenance wash"], "Book ceramic")],
 show_eye="Before & after", show_h="Transformations", show_p="The work our customers notice most.", work_nav="Results",
 show=[("Gloss ceramic finish", "Sedan · 3 days", "CERAMIC", "✨"), ("Interior revival", "SUV · deep clean", "INTERIOR", "🪑"), ("Scratch & swirl removal", "Hatchback · polish", "POLISH", "🫧"), ("PPF full body", "Luxury · 5 days", "PPF", "🛡️")],
 steps=[("Book a slot", "Choose your service and a convenient time."), ("Free pickup", "We collect your car from home or office."), ("Detailing", "Our technicians work with certified products."), ("Delivery & check", "Inspection together and doorstep delivery.")],
 reviews=[("My 5-year-old car looks showroom new. Superb finish.", "Vinod K.", "Ceramic coating"),
  ("Free pickup made it so convenient.", "Shilpa M.", "Deep detailing"),
  ("Honest advice and fair pricing.", "Jibin T.", "Regular customer")],
 faq=[("How much does ceramic coating cost in Kochi?", "Ceramic coating in Kochi starts around ₹9,999 for hatchbacks and sedans at AutoSpa, with up to 5-year warranty (sample prices). SUVs and luxury cars cost more."),
  ("How long does car detailing take?", "A foam wash takes about 2 hours, deep detailing about a day and ceramic coating 2 to 3 days depending on the car."),
  ("Do you offer doorstep pickup and drop?", "Yes. Pickup and drop is free within Kochi for detailing and coating packages."),
  ("What is PPF and do I need it?", "PPF (paint protection film) is a clear, self-healing film that protects paint from scratches and stone chips. It suits new and luxury cars."),
  ("How often should I detail my car?", "A foam wash every 2 to 4 weeks and a full interior detail every 6 months keeps most cars in great condition.")],
 offer=("Free pickup & drop this month", "Book a detailing or coating package and we collect and return your car.", "Book now"),
 hours_txt="Mon–Sat 8:30 AM – 7:30 PM · Sun 9 AM – 2 PM", hours_spec=[("Mo-Sa", "08:30", "19:30"), ("Su", "09:00", "14:00")],
 addr="Service Road, Your Locality", map="Car detailing studio near Kochi, Kerala", form_title="Book a detailing slot",
 sel=("Service", ["Foam wash & interior", "Deep detailing", "Ceramic coating", "PPF", "Servicing / repairs"]), extra=("Car model & year", "text", "e.g. Hyundai i20, 2022"),
 intent="book a car service", nav_cta="Book slot",
))

SITES.append(D(
 slug="pest-control", name="SafeNest Pest Control", brand=("Safe", "Nest"), cat="Pest Control", schema="HomeAndConstructionBusiness",
 acc="#dc2626", acc2="#f59e0b", bg="#fffafa", font="bold", emoji="🛡️",
 title="Pest Control in Kochi | SafeNest Termite & Cockroach Services",
 desc="SafeNest Pest Control in Kochi: termite treatment, cockroach, bed bug and rodent control with child-safe chemicals and warranty. Service from ₹799.",
 h1=("Pest-free home,", "guaranteed", "in writing"), badge=("SAFE", "Child & pet-friendly treatments"),
 lead="SafeNest Pest Control in Kochi treats termites, cockroaches, bed bugs, mosquitoes and rodents with child and pet-friendly chemicals. Service starts at ₹799 with a written warranty.",
 cta1="Book inspection", wa_hero="Hi, I would like to book a pest control inspection.",
 trust=["Free inspection", "Government-approved chemicals", "Written warranty"],
 chips=[("🏠 8,000+ homes", "treated (sample)"), ("📜 Up to 5-year warranty", "termite treatment")],
 glance=[("Service from", "₹799"), ("Termite warranty", "Up to 5 years"), ("Inspection", "Free"), ("Response", "Same or next day")],
 glance_h="SafeNest Pest Control at a glance",
 glance_p="SafeNest Pest Control provides general pest control, termite treatment, cockroach, bed bug, mosquito and rodent control for homes and businesses in Kochi. Services start at ₹799 and termite treatment carries up to a 5-year warranty.",
 services_eye="Our services", services_h="Treatments for every pest", services_p="Targeted treatment that works and is safe for your family.",
 services=[("🐜", "Termite control", "Pre and post-construction treatment with long warranty."),
  ("🪳", "Cockroach & ants", "Gel and spray treatment for kitchens and bathrooms."),
  ("🛏️", "Bed bug treatment", "Complete room treatment with follow-up."),
  ("🦟", "Mosquito control", "Fogging and larvicide to protect your home."),
  ("🐀", "Rodent control", "Inspection, baiting and entry-point sealing."),
  ("🏢", "Commercial AMC", "Annual contracts for offices, restaurants and warehouses.")],
 why=("Protection you can rely on", "We find the cause, treat it properly and put the warranty in writing.",
      [("Safe, approved chemicals", "Low-odour, child and pet-friendly."),
       ("Trained technicians", "Uniformed, ID-carrying professionals."),
       ("Written warranty", "Clear terms with free re-service."),
       ("Free inspection", "Know the problem before you pay.")]),
 stats=[("8,000+", "Homes treated"), ("12", "Years of service"), ("5 yrs", "Termite warranty"), ("Same day", "Service available")],
 plans_eye="Pricing", plans_h="Straightforward pricing", plans_p="Sample prices. Final price depends on property size and infestation.",
 plans=[("General pest control", "Cockroach, ants, spiders", "799", "/visit", ["Kitchen & bathrooms", "Gel + spray treatment", "Child & pet safe", "30-day warranty"], "Book general"),
  ("Termite treatment", "Most important", "4,999", "/home", ["Drill & inject method", "Wood & soil treatment", "Up to 5-year warranty", "Free yearly inspection"], "Book termite"),
  ("Annual contract", "Total protection", "6,999", "/year", ["4 scheduled visits", "All common pests", "Priority support", "Free re-service"], "Get annual plan")],
 show_eye="Common problems", show_h="What we treat most", show_p="The pests homeowners in Kochi call us about.", work_nav="Problems",
 show=[("Termite in wood", "Doors, wardrobes, roofs", "TERMITE", "🐜"), ("Cockroach in kitchen", "Gel treatment", "COCKROACH", "🪳"), ("Bed bugs", "Bedrooms, hostels", "BED BUGS", "🛏️"), ("Rodents in godown", "Warehouse AMC", "RODENT", "🐀")],
 steps=[("Book a free inspection", "Tell us the pest and property type."), ("Inspect & quote", "We find the source and quote clearly."), ("Treat safely", "Targeted treatment with approved chemicals."), ("Warranty & follow-up", "Written warranty and free re-service.")],
 reviews=[("Termites gone for good. Professional and clean work.", "Mohan R.", "Termite treatment"),
  ("Safe for my kids and no smell. Great service.", "Bincy A.", "General pest control"),
  ("Handles our restaurant AMC every quarter without fail.", "Hotel Spice Garden", "Commercial client")],
 faq=[("How much does termite treatment cost in Kochi?", "Termite treatment in Kochi at SafeNest starts around ₹4,999 for a standard home, with up to a 5-year warranty (sample price). The final cost depends on the area and severity."),
  ("Is pest control safe for children and pets?", "Yes. We use approved, low-odour chemicals and give simple precautions, such as keeping the area clear for a few hours after treatment."),
  ("How long does pest control treatment take?", "General pest control takes 1 to 2 hours, while termite treatment can take a few hours to a day depending on the property."),
  ("Do you give a warranty?", "Yes. Termite treatment includes up to a 5-year written warranty, and general pest control comes with a 30-day service warranty."),
  ("Do you provide annual contracts?", "Yes. Annual maintenance contracts cover scheduled visits for homes, offices, restaurants and warehouses.")],
 offer=("Free pest inspection", "Book an inspection today and know exactly what treatment you need.", "Book free inspection"),
 hours_txt="Mon–Sat 8 AM – 8 PM · Emergency calls on Sundays", hours_spec=[("Mo-Sa", "08:00", "20:00")], addr="Service Lane, Your Locality",
 map="Pest control near Kochi, Kerala", form_title="Book a free inspection", sel=("Pest problem", ["Termites", "Cockroaches / ants", "Bed bugs", "Mosquitoes", "Rodents", "Commercial / AMC"]),
 extra=("Property type & size", "text", "e.g. 2 BHK, 1,100 sq ft"), intent="book a pest control inspection", nav_cta="Free inspection",
))

SITES.append(D(
 slug="yoga", name="Serene Yoga Studio", brand=("Serene", " Yoga"), cat="Yoga & Wellness", schema="ExerciseGym", hero="center",
 acc="#4d7c6f", acc2="#e5b684", bg="#fbfaf7", font="serif", emoji="🧘",
 title="Yoga Classes in Kochi | Serene Yoga & Wellness Studio",
 desc="Serene Yoga Studio in Kochi: daily yoga, meditation, prenatal and therapy classes with certified teachers. First class free, from ₹1,800/month.",
 h1=("Find your calm,", "one breath", "at a time"), badge=("FREE", "First class for new students"),
 lead="Serene Yoga Studio in Kochi offers daily yoga, meditation, prenatal and therapeutic classes with certified teachers in small batches. Memberships start at ₹1,800 per month and your first class is free.",
 cta1="Book free class", wa_hero="Hi, I would like to book a free yoga class.",
 trust=["Certified teachers", "Small batches", "Beginner friendly"],
 chips=[("🧘 12 classes weekly", "morning & evening"), ("🌿 Small batches", "max 15 students")],
 glance=[("Membership from", "₹1,800 / month"), ("Classes", "Daily, morning & evening"), ("Batch size", "Max 15"), ("First class", "Free")],
 glance_h="Serene Yoga Studio at a glance",
 glance_p="Serene Yoga Studio in Kochi runs daily hatha and vinyasa yoga, meditation, prenatal yoga and therapy sessions in small batches of up to 15. Monthly memberships start at ₹1,800 and the first class is free.",
 services_eye="Our classes", services_h="Yoga for body and mind", services_p="Classes for every level, from first-timers to experienced practitioners.",
 services=[("🧘", "Hatha yoga", "Gentle, foundational postures with breathing."),
  ("🌊", "Vinyasa flow", "Energising flow that builds strength and flexibility."),
  ("🧠", "Meditation & pranayama", "Calm the mind, reduce stress and sleep better."),
  ("🤰", "Prenatal yoga", "Safe, supportive practice for expecting mothers."),
  ("🩺", "Therapeutic yoga", "Targeted sessions for back pain and stress."),
  ("👩‍👧", "Kids & family yoga", "Playful sessions for children and families.")],
 why=("A practice that fits your life", "Warm teachers, quiet space and classes at times you can actually keep.",
      [("Certified teachers", "RYT-qualified with years of teaching."),
       ("Small batches", "Personal guidance in every class."),
       ("Flexible timings", "Morning, evening and weekend options."),
       ("Welcoming for all", "Beginners, seniors and everyone in between.")]),
 stats=[("12", "Weekly classes"), ("8+", "Years teaching"), ("15", "Max per batch"), ("1,000+", "Students taught")],
 plans_eye="Memberships", plans_h="Simple membership plans", plans_p="Sample prices shown. Replace with your studio's actual rates.",
 plans=[("Drop-in", "Try a class", "400", "/class", ["Any class", "Mat provided", "No commitment", "First class free"], "Book drop-in"),
  ("Monthly", "Regular practice", "1,800", "/month", ["Unlimited group classes", "Meditation sessions", "Priority booking", "Monthly guidance"], "Join monthly"),
  ("Quarterly", "Best value", "4,800", "/3 months", ["Everything in Monthly", "1 private session", "Wellness workshop", "Free yoga mat"], "Join quarterly")],
 show_eye="Schedule", show_h="Weekly class schedule", show_p="Find a class that fits your day.", work_nav="Schedule",
 show=[("Sunrise hatha", "6:30 AM · Mon–Sat", "MORNING", "🌅"), ("Vinyasa flow", "7:30 AM · Tue, Thu", "FLOW", "🌊"), ("Evening meditation", "7 PM · Mon–Fri", "MIND", "🧠"), ("Prenatal yoga", "10 AM · Wed, Sat", "PRENATAL", "🤰")],
 steps=[("Book a free class", "Choose a batch and message us."), ("Meet your teacher", "A short chat about your goals and health."), ("Start practising", "Join regular classes at your pace."), ("Grow steadily", "Track progress and try new styles.")],
 reviews=[("My back pain is much better after 2 months of therapy classes.", "Sreeja V.", "Therapy student"),
  ("The most peaceful studio in town. Teachers are wonderful.", "Dr. Priya", "Morning batch"),
  ("As a complete beginner I never felt out of place.", "Anand K.", "Beginner")],
 faq=[("How much are yoga classes in Kochi?", "At Serene Yoga Studio, drop-in classes are ₹400, monthly membership is ₹1,800 and quarterly is ₹4,800 (sample prices). Your first class is free."),
  ("Is yoga suitable for complete beginners?", "Yes. Our hatha and beginner classes teach basics step by step, and teachers offer modifications for every level."),
  ("What should I bring to class?", "Wear comfortable clothing and bring a water bottle. We provide mats and props if you need them."),
  ("Do you offer prenatal and therapy classes?", "Yes. We run prenatal yoga and therapeutic yoga classes designed for pregnancy, back pain and stress."),
  ("What are the class timings?", "Classes run daily from 6:30 AM to 8 PM, with morning, evening and weekend batches.")],
 offer=("Your first class is free", "Try a class in our calm studio and meet your teacher, no commitment.", "Book free class"),
 hours_txt="Mon–Sat 6 AM – 8:30 PM · Sun 7 AM – 11 AM", hours_spec=[("Mo-Sa", "06:00", "20:30"), ("Su", "07:00", "11:00")], addr="Garden Lane, Your Locality",
 map="Yoga studio near Kochi, Kerala", form_title="Book your free class", sel=("Class", ["Hatha yoga", "Vinyasa flow", "Meditation", "Prenatal yoga", "Therapeutic yoga"]),
 intent="book a free yoga class", nav_cta="Free class",
))

SITES.append(D(
 slug="accounting", name="Ledger & Co. Chartered Accountants", brand=("Ledger", "&Co"), cat="CA, Tax & Accounting", schema="AccountingService",
 acc="#1e40af", acc2="#0ea5e9", bg="#f8fafc", font="sans", emoji="📊",
 title="Chartered Accountant in Kochi | GST, Tax & Company Registration",
 desc="Ledger & Co. in Kochi: GST, income tax, company registration, audit and bookkeeping for startups and SMEs. Free first consultation.",
 h1=("Tax and accounts,", "handled", "right"), badge=("FREE", "First consultation for businesses"),
 lead="Ledger & Co. is a chartered accountancy firm in Kochi offering GST, income tax, company registration, audit and bookkeeping for startups and small businesses. Your first consultation is free.",
 cta1="Book free consultation", wa_hero="Hi, I would like a consultation for GST/tax services.",
 trust=["Qualified CAs", "Fixed, transparent fees", "On-time filing"],
 chips=[("📑 2,000+ filings", "completed (sample)"), ("⏱️ On-time, every time", "no penalties")],
 glance=[("GST registration", "From ₹1,499"), ("ITR filing", "From ₹999"), ("Company registration", "From ₹6,999"), ("Consultation", "Free (first)")],
 glance_h="Ledger & Co. at a glance",
 glance_p="Ledger & Co. Chartered Accountants in Kochi provides GST registration and returns, income tax filing, company and LLP registration, bookkeeping, audit and business advisory. GST registration starts at ₹1,499 and ITR filing at ₹999.",
 services_eye="Our services", services_h="Everything your business needs on finance", services_p="Compliance, accounting and advisory from qualified chartered accountants.",
 services=[("🧾", "GST registration & returns", "Registration, monthly returns and reconciliation."),
  ("💼", "Income tax filing", "ITR for individuals, professionals and businesses."),
  ("🏢", "Company & LLP registration", "Private limited, LLP, partnership and proprietorship."),
  ("📒", "Bookkeeping & accounts", "Monthly accounting, MIS and payroll."),
  ("🔍", "Audit & assurance", "Statutory, tax and internal audits."),
  ("📈", "Business advisory", "Funding, projections and financial planning.")],
 why=("Compliance without the stress", "We keep your filings on time and your books clean so you can focus on business.",
      [("Qualified chartered accountants", "Experienced in startups and SMEs."),
       ("Fixed, transparent fees", "Clear fee before we begin."),
       ("Deadline reminders", "Never miss a GST or tax due date."),
       ("Secure, confidential", "Your data is handled with care.")]),
 stats=[("2,000+", "Returns filed"), ("15+", "Years of practice"), ("500+", "Business clients"), ("100%", "On-time filing")],
 plans_eye="Pricing", plans_h="Clear, fixed fees", plans_p="Sample fees shown. Final fee depends on your requirements.",
 plans=[("GST registration", "New business", "1,499", "/one-time", ["Documentation help", "Application filing", "GSTIN in 3–7 days", "Compliance guidance"], "Get GST registration"),
  ("Business accounts", "Monthly package", "3,999", "/month", ["Bookkeeping", "Monthly GST returns", "MIS report", "Priority support"], "Get monthly package"),
  ("Company registration", "Pvt Ltd / LLP", "6,999", "/one-time", ["Name approval", "Incorporation filing", "PAN & TAN", "Bank account support"], "Register company")],
 show_eye="Who we help", show_h="Clients we work with", show_p="We support businesses at every stage.", work_nav="Clients",
 show=[("Startups", "Registration, funding, GST", "STARTUP", "🚀"), ("Small businesses", "Monthly accounts & GST", "SME", "🏪"), ("Professionals", "Doctors, lawyers, freelancers", "PRO", "👩‍⚕️"), ("NRIs", "Income tax & property matters", "NRI", "🌍")],
 steps=[("Free consultation", "Tell us your needs and current situation."), ("Clear proposal", "Scope and fixed fee in writing."), ("Share documents", "Securely upload via WhatsApp or email."), ("We file & report", "On-time filing with confirmation and reports.")],
 reviews=[("They registered our company and GST in a week. Very helpful.", "Anoop & Team", "Startup founders"),
  ("Always on time with my returns. Never a penalty.", "Dr. Rajesh", "Professional"),
  ("Clean books and clear advice. Highly recommended.", "Shahina T.", "Small business")],
 faq=[("How much does GST registration cost in Kochi?", "GST registration at Ledger & Co. starts at ₹1,499 as a one-time fee (sample price). The GSTIN is usually issued in 3 to 7 working days."),
  ("What documents are needed to register a company?", "You need PAN and Aadhaar of directors, address proof, passport photos and proof of the registered office. We guide you step by step."),
  ("Can you file income tax returns for individuals?", "Yes. We file ITR for salaried individuals, professionals, business owners and NRIs, starting at ₹999."),
  ("Do you offer monthly accounting?", "Yes. Monthly bookkeeping packages start at ₹3,999 and include GST returns and MIS reports."),
  ("Is the first consultation really free?", "Yes. Your first business consultation is free, so you can understand the process and cost before deciding.")],
 offer=("Get your free business consultation", "Talk to a chartered accountant about GST, tax or company registration.", "Book free consultation"),
 hours_txt="Mon–Sat 9:30 AM – 6:30 PM", hours_spec=[("Mo-Sa", "09:30", "18:30")], addr="Business Centre, Your Locality", range="₹₹",
 map="Chartered accountant office near Kochi, Kerala", form_title="Book a free consultation", sel=("Service needed", ["GST registration / returns", "Income tax filing", "Company / LLP registration", "Bookkeeping & accounts", "Audit", "Other"]),
 intent="book a consultation", nav_cta="Free consult",
))

SITES.append(D(
 slug="pet-care", name="PawsPlus Pet Care", brand=("Paws", "Plus"), cat="Pet Care & Grooming", schema="LocalBusiness", hero="center",
 acc="#ea6a12", acc2="#ffb703", bg="#fffaf5", font="bold", emoji="🐶",
 title="Pet Grooming & Vet Care in Kochi | PawsPlus Pet Care",
 desc="PawsPlus Pet Care in Kochi: dog and cat grooming, vet consultation, vaccination, boarding and daycare. Grooming from ₹799. Book home service or a visit.",
 h1=("Because your pet", "is family,", "too"), badge=("HOME", "Doorstep grooming available"),
 lead="PawsPlus Pet Care in Kochi offers grooming, vet consultation, vaccination, boarding and daycare for dogs and cats. Grooming starts at ₹799 and home grooming is available.",
 cta1="Book grooming", wa_hero="Hi, I would like to book a grooming session for my pet.",
 trust=["Gentle, certified groomers", "Vet on call", "Doorstep service"],
 chips=[("🐕 4,000+ happy pets", "groomed (sample)"), ("🩺 Vet consult", "from ₹350")],
 glance=[("Grooming from", "₹799"), ("Vet consultation", "From ₹350"), ("Boarding", "From ₹600 / day"), ("Home service", "Available")],
 glance_h="PawsPlus Pet Care at a glance",
 glance_p="PawsPlus Pet Care in Kochi provides dog and cat grooming, veterinary consultation, vaccination, boarding, daycare and a pet supplies shop. Grooming starts at ₹799, boarding from ₹600 a day and home grooming is available.",
 services_eye="Our services", services_h="Everything your pet needs", services_p="Gentle care from people who love animals.",
 services=[("🛁", "Grooming & spa", "Bath, haircut, nail trim and ear cleaning."),
  ("🩺", "Vet consultation", "Check-ups, treatment and health advice."),
  ("💉", "Vaccination & deworming", "Complete vaccination schedule and records."),
  ("🏠", "Boarding & daycare", "Safe, comfortable stays with play and walks."),
  ("🚐", "Home grooming", "Grooming van that visits your doorstep."),
  ("🦴", "Pet food & supplies", "Quality food, toys and accessories.")],
 why=("Care that treats pets like family", "Calm handling, clean spaces and daily updates when your pet stays with us.",
      [("Gentle, trained groomers", "Fear-free handling and patient care."),
       ("Vet on call", "Quick help for any health concern."),
       ("Clean, safe boarding", "Individual rooms and supervised play."),
       ("Daily updates", "Photos and updates for boarding pets.")]),
 stats=[("4,000+", "Pets groomed"), ("10+", "Years of care"), ("2", "Vets on team"), ("7 days", "Open every week")],
 plans_eye="Pricing", plans_h="Pet care pricing", plans_p="Sample prices. Final price depends on breed, size and coat.",
 plans=[("Basic groom", "Bath & tidy", "799", "/session", ["Bath & blow-dry", "Nail trim", "Ear cleaning", "Perfume spray"], "Book basic groom"),
  ("Full spa", "Most popular", "1,499", "/session", ["Bath & haircut", "Teeth & ear care", "De-tangling", "Paw massage"], "Book full spa"),
  ("Boarding", "While you travel", "600", "/day", ["Individual room", "Walks & play", "Daily updates", "Vet on call"], "Book boarding")],
 show_eye="Our space", show_h="Pet-friendly spaces", show_p="Clean, calm and designed for comfort.", work_nav="Spaces",
 show=[("Grooming studio", "AC · gentle handling", "GROOMING", "🛁"), ("Play area", "Supervised daycare", "DAYCARE", "🐕"), ("Boarding rooms", "Individual & clean", "BOARDING", "🏠"), ("Pet shop", "Food, toys & more", "SHOP", "🦴")],
 steps=[("Book a service", "Choose grooming, vet or boarding."), ("Pickup or visit", "Bring your pet or we collect from home."), ("Gentle care", "Handled by trained, patient staff."), ("Happy pet, updates", "Pickup with photos and care notes.")],
 reviews=[("My dog usually hates baths but loved it here!", "Sneha R.", "Dog parent"),
  ("Boarded my cat for a week and got daily photos.", "Arun K.", "Cat parent"),
  ("Home grooming is a lifesaver for our busy schedule.", "Lakshmi P.", "Home grooming")],
 faq=[("How much does dog grooming cost in Kochi?", "Dog grooming in Kochi at PawsPlus starts around ₹799 for a basic groom and ₹1,499 for a full spa session (sample prices). The price depends on breed, size and coat."),
  ("Do you offer home grooming?", "Yes. Our grooming van visits homes in Kochi. Message us to book a slot."),
  ("Do you do pet boarding?", "Yes. We offer clean individual boarding rooms from ₹600 per day with walks, play and daily updates."),
  ("Is a vet available?", "Yes. Our vets are available for consultation, vaccinations, treatment and emergency guidance."),
  ("Do you groom cats too?", "Yes. We groom cats with gentle, fear-free handling. Please mention your cat's temperament when booking.")],
 offer=("Book your pet's spa day", "Gentle grooming by trained staff. First-time customers get 10% off.", "Book grooming"),
 hours_txt="Every day 9 AM – 8 PM", hours_spec=[("Mo-Su", "09:00", "20:00")], addr="Park Road, Your Locality",
 map="Pet care near Kochi, Kerala", form_title="Book for your pet", sel=("Service", ["Grooming", "Home grooming", "Vet consultation", "Vaccination", "Boarding / daycare"]),
 extra=("Pet type & breed", "text", "e.g. Labrador, 2 years"), intent="book a pet service", nav_cta="Book now",
))

SITES.append(D(
 slug="solar", name="SunBright Solar", brand=("Sun", "Bright"), cat="Solar Installation", schema="HomeAndConstructionBusiness",
 acc="#f59e0b", acc2="#f97316", on_acc="#1a1203", font="bold", emoji="☀️",
 title="Solar Panel Installation in Kochi | SunBright Rooftop Solar",
 desc="SunBright Solar in Kochi: rooftop solar for homes and businesses from ₹60,000/kW with subsidy support and 25-year panel warranty. Free quote.",
 h1=("Cut your", "electricity bill", "up to 90%"), badge=("SUBSIDY", "We handle PM Surya Ghar paperwork"),
 lead="SunBright Solar installs rooftop solar systems for homes and businesses in Kochi, with subsidy and net-metering support. Systems start from around ₹60,000 per kW with a 25-year panel warranty.",
 cta1="Get free solar quote", wa_hero="Hi, I would like a free solar quote for my home.",
 trust=["Subsidy & net-metering help", "25-year panel warranty", "Free site survey"],
 chips=[("🏠 1,200+ rooftops", "installed (sample)"), ("🔋 Save up to 90%", "on power bills")],
 glance=[("Price from", "₹60,000 / kW"), ("Panel warranty", "25 years"), ("Subsidy", "Paperwork handled"), ("Installation", "5–7 days")],
 glance_h="SunBright Solar at a glance",
 glance_p="SunBright Solar installs on-grid and hybrid rooftop solar systems for homes, shops and factories in Kochi. Systems start from about ₹60,000 per kW, with a 25-year panel warranty, subsidy support and net-metering paperwork handled for you.",
 services_eye="Our solutions", services_h="Solar for homes and businesses", services_p="Complete design, installation, subsidy and maintenance by one team.",
 services=[("🏠", "Home rooftop solar", "On-grid systems from 2 kW to 10 kW for homes."),
  ("🏭", "Commercial & industrial", "Large rooftop systems for shops, factories and campuses."),
  ("🔋", "Hybrid & battery systems", "Power backup with solar and storage."),
  ("📑", "Subsidy & net metering", "We manage applications and approvals."),
  ("🔧", "AMC & maintenance", "Cleaning, monitoring and annual service."),
  ("💧", "Solar water heaters", "Efficient hot water for homes and hotels.")],
 why=("Solar done right", "Good design, branded equipment and proper after-sales service decide how well solar performs.",
      [("Tier-1 panels & inverters", "Branded equipment with long warranty."),
       ("Free site survey & design", "Right-sized for your roof and bill."),
       ("Subsidy support", "We handle paperwork end to end."),
       ("Monitoring & service", "Track your generation and get support.")]),
 stats=[("1,200+", "Rooftops installed"), ("8 MW", "Capacity installed"), ("25 yrs", "Panel warranty"), ("3–4 yrs", "Typical payback")],
 plans_eye="Pricing", plans_h="Solar packages", plans_p="Sample prices before subsidy. Exact quote after a free site survey.",
 plans=[("3 kW home system", "Bills up to ₹3,000", "1,80,000", "starting", ["3 kW on-grid", "Tier-1 panels", "Net-metering support", "Subsidy paperwork"], "Get 3 kW quote"),
  ("5 kW home system", "Most popular", "2,90,000", "starting", ["5 kW on-grid", "Tier-1 panels & inverter", "Net-metering support", "5-year service"], "Get 5 kW quote"),
  ("Commercial system", "Shops & factories", "6,00,000", "starting", ["10 kW and above", "Custom design", "Monitoring system", "AMC included"], "Get commercial quote")],
 show_eye="Installations", show_h="Recent solar projects", show_p="Systems we've installed across Kerala.", work_nav="Projects",
 show=[("Villa rooftop, 5 kW", "Kakkanad · 600 units/mo", "HOME", "🏠"), ("School campus, 30 kW", "Aluva · savings ₹25k/mo", "SCHOOL", "🎓"), ("Factory roof, 100 kW", "Angamaly · industrial", "INDUSTRIAL", "🏭"), ("Hotel hot water", "Fort Kochi · solar heater", "HOTEL", "💧")],
 steps=[("Share your bill", "Send your last electricity bill on WhatsApp."), ("Free site survey", "We design the right system for your roof."), ("Install in 5–7 days", "Complete installation with approvals."), ("Generate & save", "Start saving and track your generation.")],
 reviews=[("Our bill dropped from ₹6,500 to under ₹500. Great team.", "Sajith K.", "5 kW home system"),
  ("They handled subsidy and net metering. Zero hassle.", "Dr. Fathima", "Home system"),
  ("The factory system paid back in under 4 years.", "Mathew & Sons", "Commercial client")],
 faq=[("How much does a rooftop solar system cost in Kochi?", "Rooftop solar in Kochi costs about ₹60,000 per kW before subsidy, so a 3 kW home system starts around ₹1,80,000 and a 5 kW system around ₹2,90,000 (sample prices)."),
  ("Is there a government subsidy for rooftop solar?", "Residential rooftop solar can qualify for central subsidy under the PM Surya Ghar scheme. We help with the application and paperwork."),
  ("How much can I save on my electricity bill?", "Most homes cut their electricity bill by 70 to 90 percent, with payback in about 3 to 4 years, depending on usage and system size."),
  ("How long does solar installation take?", "A typical home installation takes 5 to 7 days after the design and approvals are complete."),
  ("What warranty do the panels carry?", "Panels typically carry a 25-year performance warranty and inverters 5 to 10 years. We also offer annual maintenance.")],
 offer=("Get a free solar quote", "Send your electricity bill and we'll design the right system and savings plan.", "Get free quote"),
 hours_txt="Mon–Sat 9 AM – 6 PM", hours_spec=[("Mo-Sa", "09:00", "18:00")], addr="Energy Park Road, Your Locality", range="₹₹₹",
 map="Solar installer near Kochi, Kerala", form_title="Get a free solar quote", sel=("Property type", ["Home / villa", "Apartment / housing society", "Shop / commercial", "Factory / industry", "School / institution"]),
 extra=("Monthly electricity bill", "text", "e.g. ₹4,500"), intent="get a free solar quote", nav_cta="Free quote",
))
