from common import D

SITES = []

SITES.append(D(
 slug="gym", name="FitZone Gym", brand=("Fit", "Zone"), cat="Gym & Fitness", schema="ExerciseGym", theme="dark",
 acc="#ff4d2e", acc2="#ffa13d", font="bold", emoji="💪",
 title="FitZone Gym Kochi | Strength, Cardio & Personal Training",
 desc="FitZone Gym in Kochi: modern equipment, certified trainers and flexible monthly plans from ₹1,500. Book a free trial session today.",
 h1=("Build your", "strongest", "self"), badge=("NEW", "Morning & evening batches open"),
 lead="FitZone is a fully equipped gym in Kochi with certified trainers, cardio and strength zones and plans from ₹1,500 a month. Book a free trial and start this week.",
 cta1="Book free trial", wa_hero="Hi, I want to book a free trial at the gym.",
 trust=["Free trial session", "Certified trainers", "No joining fee offers"],
 chips=[("⭐ 4.9 member rating", "sample rating"), ("🏋️ 50+ machines", "strength & cardio")],
 glance=[("Plans from", "₹1,500 / month"), ("Open", "6 AM – 10 PM"), ("Trainers", "10+ certified"), ("Free trial", "1 session")],
 glance_h="FitZone Gym at a glance",
 glance_p="FitZone Gym offers strength training, cardio, HIIT, yoga and personal training in Kochi. Monthly membership starts at ₹1,500 and every new member gets a free trial session.",
 services_h="Training programs for every goal", services_p="Pick a program that matches your level. Our trainers guide you at every step.",
 services=[("🏋️", "Strength training", "Free weights and machines for muscle gain and a stronger body."),
  ("🏃", "Cardio zone", "Treadmills, cross-trainers and cycles to build stamina."),
  ("🥊", "HIIT & functional", "High-energy group classes that burn calories fast."),
  ("🧘", "Yoga & mobility", "Improve flexibility, posture and recovery."),
  ("🎯", "Personal training", "One-to-one coaching with a custom workout plan."),
  ("🥗", "Diet guidance", "Simple meal plans that fit your lifestyle and budget.")],
 why=("A gym that keeps you coming back", "Clean space, good equipment and trainers who actually track your progress.",
      [("Certified, friendly trainers", "Guidance on form and plans, not just a machine floor."),
       ("Clean and spacious", "Cleaned daily with proper ventilation and lockers."),
       ("Flexible memberships", "Monthly, quarterly and yearly with free trial."),
       ("Progress tracking", "Body assessment every month so you see real results.")]),
 stats=[("500+", "Active members"), ("10+", "Expert trainers"), ("50+", "Machines"), ("16 hrs", "Open daily")],
 plans_h="Simple, honest pricing", plans_p="No hidden charges. Sample prices shown.",
 plans=[("Monthly", "Flexible start", "1,500", "/month", ["Full gym access", "Cardio & strength zones", "Locker facility", "Basic workout plan"], "Choose Monthly"),
  ("Quarterly", "Best for beginners", "3,999", "/3 months", ["Everything in Monthly", "Group HIIT classes", "Diet guidance", "Monthly body assessment"], "Choose Quarterly"),
  ("Yearly", "Best value", "11,999", "/year", ["Everything in Quarterly", "2 personal sessions", "Priority slot booking", "Free gym t-shirt"], "Choose Yearly")],
 show_h="Classes & zones", show_p="A look at what you can do inside FitZone.", work_nav="Classes",
 show=[("Morning HIIT", "6:30 AM · Mon–Sat", "GROUP", "🔥"), ("Strength floor", "Free weights & racks", "ZONE", "🏋️"), ("Yoga flow", "7 PM · Mon, Wed, Fri", "CLASS", "🧘"), ("Personal coaching", "1-to-1 · by appointment", "PT", "🎯")],
 steps=[("Book a free trial", "Message us and pick a time that suits you."), ("Meet your trainer", "Quick assessment of your goals and fitness level."), ("Get your plan", "A workout and diet plan built for you."), ("Train and track", "Monthly check-ins to measure your progress.")],
 reviews=[("Lost 9 kg in 4 months. The trainers really care and the plan was easy to follow.", "Anoop P.", "Member for 1 year"),
  ("Clean, spacious and never too crowded. Love the morning HIIT batch!", "Sneha R.", "Member for 8 months"),
  ("Best value gym in the area. Personal training helped me gain strength fast.", "Vishnu M.", "Member for 2 years")],
 faq=[("How much does a gym membership cost in Kochi?", "At FitZone, membership starts at ₹1,500 per month, with quarterly at ₹3,999 and yearly at ₹11,999 (sample prices). Every new member gets a free trial session."),
  ("Do you offer a free trial?", "Yes. You can book one free trial session with a trainer and a basic fitness assessment before you join."),
  ("What are the gym timings?", "FitZone is open Monday to Saturday from 6 AM to 10 PM and on Sunday from 7 AM to 12 PM."),
  ("Is personal training available?", "Yes. One-to-one personal training with a custom workout and diet plan is available by appointment."),
  ("Do beginners and women members train here?", "Yes. Our trainers design beginner-friendly plans, and women-only batches can be arranged on request.")],
 offer=("Your first session is on us", "Book a free trial and fitness assessment. No payment, no pressure.", "Claim free trial"),
 addr="Main Road, Your Locality", hours_txt="Mon–Sat 6 AM – 10 PM · Sun 7 AM – 12 PM", hours_spec=[("Mo-Sa", "06:00", "22:00"), ("Su", "07:00", "12:00")],
 map="Gym near Kochi, Kerala", form_title="Book your free trial", sel=("Your goal", ["Weight loss", "Muscle gain", "General fitness", "Personal training", "Yoga"]),
 intent="book a free trial", nav_cta="Free trial", range="₹₹",
))

SITES.append(D(
 slug="clinic", name="CareWell Clinic", brand=("Care", "Well"), cat="Clinic & Healthcare", schema="MedicalClinic",
 acc="#0f9b9a", acc2="#38bdf8", bg="#fafdfd", font="sans", emoji="🩺",
 title="CareWell Clinic Kochi | Family Doctor & Health Check-ups",
 desc="CareWell Clinic in Kochi: experienced family doctors, in-house lab and health check-up packages from ₹999. Book your appointment online.",
 h1=("Quality care,", "close", "to home"), badge=("OPEN", "Appointments available today"),
 lead="CareWell Clinic is a family clinic in Kochi with experienced doctors, an in-house lab and health check-ups from ₹999. Book a time slot online and skip the waiting.",
 cta1="Book appointment", wa_hero="Hi, I would like to book an appointment.",
 trust=["Same-day appointments", "In-house lab", "Child & women care"],
 chips=[("👩‍⚕️ Women doctors", "available on request"), ("🧪 Reports same day", "for most tests")],
 glance=[("Consultation", "From ₹300"), ("Open", "8 AM – 8 PM"), ("Doctors", "8 specialists"), ("Lab", "In-house, same-day")],
 glance_h="CareWell Clinic at a glance",
 glance_p="CareWell Clinic provides general medicine, paediatrics, dental care, women's health, lab tests and health check-ups in Kochi. A general consultation starts at ₹300 and appointments can be booked online.",
 services_h="Complete care under one roof", services_p="From everyday illness to routine check-ups, we care for the whole family.",
 services=[("🧑‍⚕️", "General medicine", "Fever, infections, diabetes, BP and everyday health problems."),
  ("👶", "Paediatrics", "Child health, vaccinations and growth monitoring."),
  ("🦷", "Dental care", "Check-ups, cleaning, fillings and pain relief."),
  ("🤰", "Women's health", "Consultations, antenatal care and wellness guidance."),
  ("🧪", "Lab & diagnostics", "Blood tests, ECG and scans with quick reports."),
  ("❤️", "Health check-ups", "Preventive packages for individuals and families.")],
 why=("Care that feels personal", "We keep appointments on time and explain every diagnosis in simple language.",
      [("Experienced doctors", "A team of 8 specialists across key departments."),
       ("Short waiting time", "Online slots so you are seen on schedule."),
       ("Hygienic and safe", "Sterile equipment and clean consultation rooms."),
       ("Transparent fees", "Clear pricing with no surprise charges.")]),
 stats=[("15+", "Years of care"), ("10k+", "Patients treated"), ("8", "Specialist doctors"), ("6 days", "Open every week")],
 plans_h="Clear, affordable fees", plans_p="Sample fees shown. Replace with your clinic's actual rates.",
 plans=[("General consultation", "Per visit", "300", "/visit", ["Doctor consultation", "Prescription & advice", "Free follow-up in 3 days", "Online booking"], "Book consultation"),
  ("Basic health check", "For adults", "999", "/person", ["Blood sugar & cholesterol", "BP, BMI and ECG", "Doctor review", "Same-day report"], "Book check-up"),
  ("Full body check", "Complete screening", "2,499", "/person", ["35+ lab tests", "ECG & chest X-ray", "Doctor consultation", "Diet advice"], "Book full check")],
 show_h="Departments & clinics", show_p="Specialist clinics run on fixed days so you can plan your visit.", work_nav="Departments",
 show=[("Paediatric clinic", "Mon, Wed, Fri · 10 AM", "CHILD", "👶"), ("Dental clinic", "Daily · 9 AM – 6 PM", "DENTAL", "🦷"), ("Women's clinic", "Tue, Thu · 11 AM", "WOMEN", "🤰"), ("Health check lab", "Daily · 8 AM – 12 PM", "LAB", "🧪")],
 steps=[("Book online", "Choose your doctor and a time slot in a minute."), ("Visit on time", "Walk in at your slot with minimal waiting."), ("Consult & test", "Doctor consultation and same-day lab tests if needed."), ("Follow-up", "Free follow-up and reports shared on WhatsApp.")],
 reviews=[("Quick appointment and the doctor explained everything clearly.", "Lakshmi K.", "Patient for 3 years"),
  ("Clean clinic, friendly staff. My kids are not afraid to visit now!", "Rajesh P.", "Parent"),
  ("Lab reports came the same day. Very convenient.", "Fathima S.", "Patient")],
 faq=[("How much is a doctor consultation at CareWell Clinic?", "A general consultation starts at ₹300 per visit, with a free follow-up within 3 days (sample fee)."),
  ("Can I book a clinic appointment online?", "Yes. Choose a doctor and time slot on this page or message us on WhatsApp to confirm your appointment."),
  ("Do you have a lab for blood tests?", "Yes. Our in-house lab handles common blood tests, ECG and basic scans, with most reports ready the same day."),
  ("What are the clinic timings?", "The clinic is open Monday to Saturday from 8 AM to 8 PM and on Sunday from 9 AM to 1 PM."),
  ("Do you treat children and women?", "Yes. We have a paediatrician and a women's health clinic, and a female doctor is available on request.")],
 offer=("Book online, skip the waiting", "Choose your time slot and we'll have you seen on schedule.", "Book now"),
 hours_txt="Mon–Sat 8 AM – 8 PM · Sun 9 AM – 1 PM", hours_spec=[("Mo-Sa", "08:00", "20:00"), ("Su", "09:00", "13:00")],
 map="Clinic near Kochi, Kerala", form_title="Book your appointment", sel=("Department", ["General medicine", "Paediatrics", "Dental care", "Women's health", "Health check-up"]),
 intent="book an appointment", nav_cta="Book now",
))

SITES.append(D(
 slug="dental", name="BrightSmile Dental", brand=("Bright", "Smile"), cat="Dental Care", schema="Dentist", hero="center",
 acc="#2563eb", acc2="#22d3ee", bg="#f9fbff", font="grotesk", emoji="🦷",
 title="BrightSmile Dental Kochi | Implants, Braces & Root Canal",
 desc="BrightSmile Dental in Kochi: painless root canal, braces, implants and teeth whitening. Consultation from ₹200. Book your dental appointment online.",
 h1=("A healthier,", "brighter", "smile"), badge=("PAINLESS", "Modern dentistry for the whole family"),
 lead="BrightSmile Dental is a dental clinic in Kochi offering root canal, braces, implants, cleaning and whitening with gentle, modern care. Consultation starts at ₹200.",
 cta1="Book dental visit", wa_hero="Hi, I would like to book a dental appointment.",
 trust=["Painless procedures", "Digital X-ray", "EMI on treatments"],
 chips=[("😁 5,000+ smiles", "treated (sample)"), ("🕘 Evening slots", "till 8 PM")],
 glance=[("Consultation", "From ₹200"), ("Open", "9 AM – 8 PM"), ("Dentists", "4 specialists"), ("X-ray", "Digital, low radiation")],
 glance_h="BrightSmile Dental at a glance",
 glance_p="BrightSmile Dental provides general dentistry, root canal treatment, braces and aligners, dental implants, teeth whitening and kids' dentistry in Kochi. A first consultation costs from ₹200.",
 services_h="Dental treatments we offer", services_p="Gentle, modern treatment with clear costs explained before we start.",
 services=[("🦷", "Root canal (RCT)", "Single-visit, painless root canal to save your natural tooth."),
  ("😁", "Braces & aligners", "Metal, ceramic and clear aligners for a straighter smile."),
  ("🔩", "Dental implants", "Permanent replacement for missing teeth with natural look."),
  ("✨", "Teeth whitening", "Safe in-clinic whitening for a brighter smile."),
  ("🧒", "Kids' dentistry", "Friendly, fear-free care for children."),
  ("🪥", "Cleaning & scaling", "Deep cleaning to keep gums and teeth healthy.")],
 why=("Dentistry without the dread", "We explain every step, show you the costs first and keep treatment as comfortable as possible.",
      [("Pain-free approach", "Modern anaesthesia and gentle technique."),
       ("Sterile and safe", "Autoclaved instruments and single-use items."),
       ("Transparent pricing", "Written treatment plan before any procedure."),
       ("Flexible payment", "EMI options on larger treatments.")]),
 stats=[("12+", "Years of practice"), ("5k+", "Happy patients"), ("4", "Dental specialists"), ("100%", "Sterilised tools")],
 plans_h="Treatment costs, upfront", plans_p="Sample starting prices. Exact cost depends on your examination.",
 plans=[("Check-up & cleaning", "Every 6 months", "800", "/visit", ["Oral examination", "Scaling & polishing", "Digital X-ray if needed", "Care advice"], "Book cleaning"),
  ("Root canal", "Save your tooth", "3,500", "/tooth", ["Painless RCT", "Digital X-ray", "Temporary filling", "Follow-up visit"], "Book RCT"),
  ("Braces", "Straighter teeth", "25,000", "/full course", ["Metal or ceramic options", "Monthly adjustments", "Retainers included", "EMI available"], "Ask about braces")],
 show_h="Smile makeovers", show_p="Common treatments patients ask about most.", work_nav="Treatments",
 show=[("Clear aligners", "Invisible straightening", "ALIGNERS", "😁"), ("Single-sitting RCT", "Done in one visit", "ENDODONTICS", "🦷"), ("Implant & crown", "Fixed new tooth", "IMPLANTS", "🔩"), ("Kids' first visit", "Gentle introduction", "PAEDIATRIC", "🧒")],
 steps=[("Book a visit", "Pick a slot online or on WhatsApp."), ("Examination", "Digital X-ray and a clear diagnosis."), ("Treatment plan", "Written plan with costs and timeline."), ("Treatment & care", "Comfortable procedure and aftercare.")],
 reviews=[("Painless root canal, honestly. The doctor explained everything first.", "Divya N.", "Root canal patient"),
  ("My daughter loves coming here. Very patient with kids.", "Sandeep K.", "Parent"),
  ("Got braces here. Clear pricing and great follow-up.", "Akhil T.", "Braces patient")],
 faq=[("How much does a root canal cost in Kochi?", "A root canal at BrightSmile starts around ₹3,500 per tooth (sample price). The final cost depends on the tooth and whether a crown is needed."),
  ("Is dental treatment painful?", "No. We use modern anaesthesia and gentle technique so most treatments, including root canals, are comfortable."),
  ("How long do braces treatment take?", "Braces typically take 12 to 24 months depending on your case. We give a clear timeline after examination."),
  ("Do you offer EMI for dental treatment?", "Yes. EMI options are available on larger treatments like braces and implants. Ask at your consultation."),
  ("Can I bring my child for a first dental visit?", "Yes. Our dentists are trained to make a child's first visit friendly. We recommend the first check-up by age 3.")],
 offer=("Free dental check-up this month", "Book a slot and get a consultation with X-ray advice at no cost (sample offer).", "Claim free check-up"),
 hours_txt="Mon–Sat 9 AM – 8 PM · Sun by appointment", hours_spec=[("Mo-Sa", "09:00", "20:00")],
 map="Dental clinic near Kochi, Kerala", form_title="Book a dental appointment", sel=("Treatment", ["Check-up & cleaning", "Root canal", "Braces / aligners", "Implants", "Whitening", "Kids' dentistry"]),
 intent="book a dental appointment", nav_cta="Book visit",
))

SITES.append(D(
 slug="tuition", name="BrightPath Tuition", brand=("Bright", "Path"), cat="Tuition & Coaching", schema="EducationalOrganization",
 acc="#5b4bdb", acc2="#f59e0b", bg="#fbfbff", font="bold", emoji="🎓",
 title="BrightPath Tuition Kochi | Class 5–12 & Entrance Coaching",
 desc="BrightPath Tuition in Kochi: small batches, expert teachers and weekly tests for Class 5 to 12, SSLC and entrance coaching. Join a free demo class.",
 h1=("Learn smarter,", "score", "higher"), badge=("FREE", "Demo class for new students"),
 lead="BrightPath is a tuition centre in Kochi for Class 5 to 12 with small batches, experienced teachers and weekly tests. Fees start at ₹800 per month and the first demo class is free.",
 cta1="Book free demo", wa_hero="Hi, I want to know about the tuition classes.",
 trust=["Max 20 students per batch", "Weekly tests", "Parent progress updates"],
 chips=[("📝 Weekly tests", "with progress reports"), ("👩‍🏫 15 expert teachers", "Maths, Science, English")],
 glance=[("Classes", "5th to 12th + entrance"), ("Fees from", "₹800 / month"), ("Batch size", "Max 20 students"), ("Demo class", "Free")],
 glance_h="BrightPath Tuition at a glance",
 glance_p="BrightPath Tuition Centre in Kochi coaches students from Class 5 to Plus Two, including SSLC and entrance preparation. Batches are limited to 20 students and monthly fees start at ₹800.",
 services_h="Classes for every stage", services_p="Concept-based teaching, regular practice and personal attention.",
 services=[("📘", "Foundation (5–7)", "Strong basics in Maths, Science and English."),
  ("📝", "SSLC / Class 10", "Full syllabus, model exams and revision plans."),
  ("🔬", "Plus One & Two Science", "Physics, Chemistry, Maths and Biology with doubt clearing."),
  ("📊", "Plus One & Two Commerce", "Accountancy, Business Studies and Economics."),
  ("🏆", "Entrance coaching", "Guidance for KEAM, NEET and other entrance exams."),
  ("🗣️", "Spoken English", "Build confidence and fluency step by step.")],
 why=("Results come from attention", "Small batches mean every student is seen, tested and supported.",
      [("Experienced teachers", "Subject experts who simplify difficult topics."),
       ("Small batches", "Maximum 20 students so doubts get answered."),
       ("Regular tests", "Weekly tests and monthly progress reports."),
       ("Parent updates", "Attendance and marks shared on WhatsApp.")]),
 stats=[("10+", "Years teaching"), ("800+", "Students guided"), ("15", "Expert teachers"), ("20", "Max per batch")],
 plans_h="Affordable monthly fees", plans_p="Sample fees shown. Replace with your centre's actual rates.",
 plans=[("Foundation", "Classes 5 to 7", "800", "/month", ["Maths, Science, English", "Weekly practice tests", "Doubt clearing hours", "Parent updates"], "Join Foundation"),
  ("SSLC special", "Class 10", "1,200", "/month", ["All subjects", "Model exam series", "Revision plans", "Monthly progress report"], "Join SSLC"),
  ("Plus One & Two", "Science or Commerce", "1,800", "/month", ["Subject experts", "Chapter-wise tests", "Study material", "Entrance guidance"], "Join Plus One/Two")],
 show_h="Batches & programs", show_p="Pick the batch that fits your schedule.", work_nav="Batches",
 show=[("SSLC evening batch", "Mon–Fri · 5:30 PM", "CLASS 10", "📝"), ("Plus Two Science", "Mon–Sat · 4 PM", "SCIENCE", "🔬"), ("KEAM crash course", "Weekend · 9 AM", "ENTRANCE", "🏆"), ("Spoken English", "Tue, Thu · 6 PM", "SKILLS", "🗣️")],
 steps=[("Book a demo class", "Attend one class free and meet the teachers."), ("Level assessment", "A short test to understand where your child stands."), ("Join the right batch", "Placed in a small batch that fits the level."), ("Track progress", "Weekly tests and monthly updates to parents.")],
 reviews=[("My son's Maths marks improved a lot in just 3 months.", "Sindhu M.", "Parent, Class 10"),
  ("Teachers are friendly and always ready to clear doubts.", "Aswin R.", "Student, Plus Two"),
  ("Weekly tests and regular updates keep us informed.", "Jolly T.", "Parent, Class 8")],
 faq=[("What are the tuition fees at BrightPath?", "Fees start at ₹800 per month for Classes 5 to 7, ₹1,200 for SSLC and ₹1,800 for Plus One and Two (sample fees)."),
  ("Is there a free demo class?", "Yes. New students can attend one demo class free before deciding to join."),
  ("How many students are in each batch?", "Each batch has a maximum of 20 students so every child gets personal attention."),
  ("Do you coach for KEAM and NEET?", "Yes. Entrance coaching for KEAM, NEET and other exams runs as weekend and crash-course batches."),
  ("How will I know my child's progress?", "We share weekly test marks and monthly progress reports with parents on WhatsApp.")],
 offer=("Your first class is free", "Attend a demo class, meet the teachers and see our method before you join.", "Book demo class"),
 hours_txt="Mon–Sat 4 PM – 8 PM · Sun doubt class 9 AM – 12 PM", hours_spec=[("Mo-Sa", "16:00", "20:00"), ("Su", "09:00", "12:00")],
 map="Tuition centre near Kochi, Kerala", form_title="Book your free demo class", sel=("Class", ["Class 5–7", "Class 8–9", "SSLC (Class 10)", "Plus One", "Plus Two", "Entrance coaching", "Spoken English"]),
 intent="book a free demo class", nav_cta="Free demo",
))

SITES.append(D(
 slug="restaurant", name="Spice Route Kitchen", brand=("Spice", "Route"), cat="Restaurant & Café", schema="Restaurant", theme="dark", hero="center",
 acc="#f59e0b", acc2="#ef4444", on_acc="#14151a", font="serif", emoji="🍛",
 title="Spice Route Kitchen Kochi | Kerala Meals, Biriyani & Seafood",
 desc="Spice Route Kitchen in Kochi serves authentic Kerala meals from ₹150, biriyani, seafood and tandoor. Dine in, take away or order home delivery on WhatsApp.",
 h1=("Authentic", "Kerala", "flavours"), badge=("OPEN", "Lunch served 11 AM – 3 PM"),
 lead="Spice Route Kitchen is a Kerala restaurant in Kochi serving traditional meals from ₹150, biriyani, seafood and grills. Dine in, take away or get free delivery within 5 km.",
 cta1="Reserve a table", wa_hero="Hi, I would like to place an order.",
 trust=["Fresh daily", "Free delivery within 5 km", "Party & bulk orders"],
 chips=[("⭐ 4.8 diners' rating", "sample rating"), ("🛵 Free delivery", "within 5 km")],
 glance=[("Meals from", "₹150 / plate"), ("Open", "11 AM – 11 PM"), ("Delivery", "Free within 5 km"), ("Dine-in seats", "60")],
 glance_h="Spice Route Kitchen at a glance",
 glance_p="Spice Route Kitchen is a Kerala restaurant in Kochi serving traditional meals, biriyani, seafood fry, parotta curries and tandoor. Meals start at ₹150 and home delivery is free within 5 km.",
 services_h="Our specialties", services_p="Home-style recipes cooked fresh every day.", services_eye="What we serve",
 services=[("🍚", "Kerala meals", "Traditional meals with rice, curries, thoran and payasam."),
  ("🍗", "Biriyani", "Fragrant, slow-cooked biriyani made fresh daily."),
  ("🐟", "Seafood fry", "Fish and prawn dishes marinated in house masala."),
  ("🫓", "Parotta & curries", "Soft parotta with beef, chicken or veg curry."),
  ("🔥", "Tandoor & grill", "Smoky tandoori, kebabs and grilled platters."),
  ("🍨", "Desserts & drinks", "Falooda, fresh juices and traditional sweets.")],
 why=("Taste you remember", "Fresh ingredients, traditional recipes and generous portions at honest prices.",
      [("Cooked fresh daily", "No reheated food, only same-day preparation."),
       ("Traditional recipes", "Handed-down Malabar and Kerala flavours."),
       ("Family friendly", "Comfortable seating and a kids' menu."),
       ("Events & parties", "Bulk and party orders with on-time delivery.")]),
 stats=[("4.8", "Customer rating"), ("60+", "Dishes on menu"), ("100%", "Fresh ingredients"), ("12 hrs", "Open daily")],
 plans_eye="Menu favourites", plans_h="Customer favourites", plans_p="Sample prices shown. Replace with your actual menu.",
 plans=[("Kerala meals", "Lunch special", "150", "/plate", ["Rice with 3 curries", "Thoran & pickle", "Papad & curd", "Unlimited rice"], "Order meals"),
  ("Chicken biriyani", "Chef's pick", "220", "/plate", ["Fragrant biriyani rice", "Tender chicken", "Raita & salad", "Pickle on the side"], "Order biriyani"),
  ("Family combo", "Serves 4", "799", "/combo", ["Biriyani for 4", "Starter platter", "4 soft drinks", "Dessert to share"], "Order combo")],
 show_eye="The kitchen", show_h="Signature dishes", show_p="The plates our regulars come back for.", work_nav="Dishes",
 show=[("Karimeen pollichathu", "Pearl spot fish in banana leaf", "SEAFOOD", "🐟"), ("Malabar biriyani", "Dum-cooked, served with raita", "BIRIYANI", "🍗"), ("Beef fry & parotta", "Kerala classic combo", "CLASSIC", "🫓"), ("Falooda", "Cool dessert drink", "DESSERT", "🍨")],
 steps=[("Choose", "Browse the menu and pick your dishes."), ("Order or reserve", "Message us on WhatsApp to order or book a table."), ("We prepare fresh", "Cooked after you order, never reheated."), ("Enjoy", "Dine in, take away or get it delivered.")],
 reviews=[("Best biriyani in town. Fresh and full of flavour!", "Nizar A.", "Regular customer"),
  ("Love the Kerala meals. Tastes just like home.", "Remya V.", "Dined with family"),
  ("Ordered for a party of 30. Everything was perfect and on time.", "Jacob P.", "Party order")],
 faq=[("What is the price of Kerala meals at Spice Route Kitchen?", "Kerala meals start at ₹150 per plate with unlimited rice (sample price). Biriyani starts at ₹220."),
  ("Do you offer home delivery in Kochi?", "Yes. Delivery is free within 5 km. Order on WhatsApp and we'll confirm the timing."),
  ("Can I book a table or a party?", "Yes. Message us with the date, time and number of guests to reserve a table or plan a party order."),
  ("What are the restaurant timings?", "We are open every day from 11 AM to 11 PM."),
  ("Do you have vegetarian options?", "Yes. Our menu includes vegetarian meals, veg biriyani and paneer and vegetable curries.")],
 offer=("Free delivery within 5 km", "Order on WhatsApp for fast home delivery or easy takeaway.", "Order now"),
 hours_txt="Every day 11 AM – 11 PM", hours_spec=[("Mo-Su", "11:00", "23:00")], range="₹₹",
 map="Restaurant near Kochi, Kerala", form_title="Reserve or order", sel=("I want to", ["Reserve a table", "Place a takeaway order", "Order home delivery", "Party / bulk order"]),
 extra=("Preferred date and time", "text", "e.g. Saturday, 8 PM"), intent="reserve a table or place an order", nav_cta="Reserve",
))

SITES.append(D(
 slug="beauty", name="Glow Beauty Parlour", brand=("Glow", " Beauty"), cat="Beauty & Salon", schema="BeautySalon",
 acc="#d61f69", acc2="#f472b6", bg="#fffafb", font="serif", emoji="💄",
 title="Glow Beauty Parlour Kochi | Bridal Makeup, Facials & Hair",
 desc="Glow Beauty Parlour in Kochi: bridal makeup, facials, hair styling and threading by trained experts. Packages from ₹799. Book your slot online.",
 h1=("Look good,", "feel", "amazing"), badge=("BRIDAL", "Bookings open for the wedding season"),
 lead="Glow Beauty Parlour in Kochi offers bridal makeup, facials, hair styling and more in a hygienic, relaxing space. Packages start at ₹799 and bridal trial sessions are available.",
 cta1="Book appointment", wa_hero="Hi, I would like to book an appointment.",
 trust=["Hygienic & sterilised tools", "Trained experts", "Bridal trial available"],
 chips=[("⭐ 4.9 client rating", "sample rating"), ("✨ Bridal experts", "trial sessions")],
 glance=[("Packages from", "₹799"), ("Open", "9 AM – 8 PM"), ("Experts", "6 stylists"), ("Bridal trial", "Available")],
 glance_h="Glow Beauty Parlour at a glance",
 glance_p="Glow Beauty Parlour in Kochi provides haircuts, facials, bridal makeup, hair colour and spa, threading and waxing, nails and mehendi. Packages start at ₹799 and bridal packages include a free trial.",
 services_h="Beauty care, made for you", services_p="From a quick trim to your big day, we've got you covered.",
 services=[("💇‍♀️", "Haircut & styling", "Trims, styling and treatments for every hair type."),
  ("🧖‍♀️", "Facials & cleanup", "Glow-boosting facials with skin-friendly products."),
  ("👰", "Bridal makeup", "Long-lasting makeup and styling for your special day."),
  ("🎨", "Hair colour & spa", "Colouring, smoothening and deep-conditioning spa."),
  ("🪡", "Threading & waxing", "Quick, gentle and hygienic hair removal."),
  ("💅", "Nails & mehendi", "Manicure, pedicure, nail art and mehendi designs.")],
 why=("Hygienic, friendly and skilled", "Your comfort and skin safety come first, every visit.",
      [("Trained experts", "Specialists in hair, skin and bridal makeup."),
       ("Safe products", "Branded, skin-tested products only."),
       ("Sterilised tools", "Clean tools and fresh disposables each client."),
       ("Private, relaxed space", "Comfortable seating and appointment slots.")]),
 stats=[("8+", "Years of beauty"), ("3,000+", "Happy clients"), ("6", "Trained experts"), ("7 days", "Open every week")],
 plans_h="Pamper yourself for less", plans_p="Sample prices shown. Replace with your parlour's actual rates.",
 plans=[("Basic glow", "Quick refresh", "799", "/visit", ["Haircut or trim", "Eyebrow threading", "Basic cleanup", "Head massage"], "Book basic glow"),
  ("Party ready", "Look your best", "1,999", "/visit", ["Facial & cleanup", "Hair styling", "Light makeup", "Nail polish"], "Book party ready"),
  ("Bridal package", "The big day", "14,999", "/bride", ["Bridal makeup & hair", "Pre-bridal facial", "Mehendi (hands)", "Free trial session"], "Book bridal")],
 show_h="Popular looks", show_p="Styles our clients ask for the most.", work_nav="Looks",
 show=[("Bridal glam", "HD makeup & hairdo", "BRIDAL", "👰"), ("Hydra facial", "Instant glow", "SKIN", "🧖‍♀️"), ("Keratin smoothening", "Frizz-free hair", "HAIR", "💇‍♀️"), ("Mehendi & nails", "Festive designs", "ART", "💅")],
 steps=[("Pick your service", "Choose a package or a single service."), ("Book a slot", "Reserve your date on the form or WhatsApp."), ("Consultation", "We understand your skin, hair and style."), ("Relax & glow", "Enjoy the service and leave with a fresh look.")],
 reviews=[("Loved my bridal makeup. It looked natural and lasted the whole day!", "Aparna S.", "Bride"),
  ("Very hygienic and the staff are so friendly. My go-to parlour!", "Mubeena K.", "Regular client"),
  ("Best haircut I've had. Neethu understood exactly what I wanted.", "Anjali R.", "Client")],
 faq=[("How much is bridal makeup at Glow Beauty Parlour?", "Our bridal package starts at ₹14,999 and includes makeup, hair, a pre-bridal facial, mehendi for hands and a free trial session (sample price)."),
  ("Do I need an appointment?", "We recommend booking a slot, especially on weekends and for bridal or party looks. Walk-ins are accepted when free."),
  ("Do you offer a bridal makeup trial?", "Yes. Bridal packages include a trial session so you can finalise your look before the wedding."),
  ("Are your products and tools hygienic?", "Yes. We use branded, skin-tested products and sterilised tools with fresh disposables for every client."),
  ("What are the parlour timings?", "We are open every day from 9 AM to 8 PM.")],
 offer=("10% off your first visit", "New here? Book online and enjoy a welcome discount on any service.", "Claim offer"),
 hours_txt="Every day 9 AM – 8 PM", hours_spec=[("Mo-Su", "09:00", "20:00")],
 map="Beauty parlour near Kochi, Kerala", form_title="Book your appointment", sel=("Service", ["Haircut & styling", "Facial & cleanup", "Bridal makeup", "Hair colour / spa", "Threading & waxing", "Nails & mehendi"]),
 extra=("Preferred date", "date", ""), intent="book an appointment", nav_cta="Book now",
))

SITES.append(D(
 slug="homestay", name="Green Valley Homestay", brand=("Green", "Valley"), cat="Homestay & Resort", schema="LodgingBusiness", hero="center",
 acc="#15803d", acc2="#d9a406", bg="#fbfcf8", font="serif", emoji="🏡", city="Munnar", areas=["Munnar", "Devikulam", "Chinnakanal", "Top Station", "Adimali", "Marayoor"],
 title="Green Valley Homestay Munnar | Rooms & Home-cooked Meals",
 desc="Green Valley Homestay in Munnar: peaceful rooms from ₹2,200 a night, home-cooked Kerala meals and warm hosts. Book direct and save 10%.",
 h1=("Your peaceful", "escape", "in the hills"), badge=("SAVE 10%", "Book direct with your hosts"),
 lead="Green Valley is a family-run homestay in Munnar with cosy rooms from ₹2,200 a night, home-cooked Kerala meals and plantation views. Book directly and save 10%.",
 cta1="Check availability", wa_hero="Hi, I would like to check room availability.",
 trust=["Breakfast included", "Free Wi-Fi & parking", "Pickup from Munnar town"],
 chips=[("⭐ 4.9 guest rating", "sample rating"), ("🍳 Breakfast included", "home-cooked")],
 glance=[("Rooms from", "₹2,200 / night"), ("Rooms", "6 cosy rooms"), ("Check-in", "12 PM · out 11 AM"), ("Breakfast", "Included")],
 glance_h="Green Valley Homestay at a glance",
 glance_p="Green Valley Homestay in Munnar offers 6 rooms, home-cooked Kerala meals, plantation walks and bonfire evenings. Rooms start at ₹2,200 a night with breakfast included, and direct bookings get 10% off.",
 services_h="More than just a room", services_p="Slow down, eat well and enjoy the quiet beauty around you.", services_eye="Stay with us",
 services=[("🌳", "Nature walks", "Guided walks through plantations and green trails."),
  ("🍲", "Home-cooked meals", "Fresh Kerala breakfast, lunch and dinner by our hosts."),
  ("☕", "Plantation visit", "See spice and tea plantations up close."),
  ("🔥", "Bonfire evenings", "Warm evenings with music and stories under the stars."),
  ("🏞️", "Scenic views", "Wake up to hills, mist and open skies."),
  ("🚗", "Pickup & taxi", "Easy pickup from the town and local sightseeing.")],
 why=("A stay that feels like family", "You are a guest of the house, not a room number.",
      [("Warm, local hosts", "Tips on the best viewpoints and hidden spots."),
       ("Fresh home cooking", "Meals made with produce from our garden."),
       ("Clean, comfortable rooms", "Attached baths, hot water and quiet nights."),
       ("Direct booking benefits", "10% off and a free welcome drink.")]),
 stats=[("4.9", "Guest rating"), ("6", "Cosy rooms"), ("250+", "Happy stays"), ("24×7", "Host support")],
 plans_eye="Rooms", plans_h="Rooms for every stay", plans_p="Sample rates shown. Replace with your homestay's actual rates.",
 plans=[("Deluxe room", "Couples & solo", "2,200", "/night", ["Queen bed, attached bath", "Free breakfast", "Free Wi-Fi", "Garden view"], "Book deluxe"),
  ("Family suite", "Up to 5 guests", "3,800", "/night", ["2 bedrooms", "Free breakfast", "Private sit-out", "Kitchenette"], "Book family suite"),
  ("Entire cottage", "Groups up to 8", "6,500", "/night", ["Whole property", "Breakfast & dinner", "Bonfire setup", "Dedicated host"], "Book cottage")],
 show_eye="Around the stay", show_h="Experiences nearby", show_p="Things guests love doing around Munnar.", work_nav="Experiences",
 show=[("Tea garden walk", "Sunrise · 2 hrs", "WALK", "🍃"), ("Spice plantation", "Half day", "TOUR", "☕"), ("Viewpoint trek", "Easy · 3 hrs", "TREK", "🏞️"), ("Bonfire night", "Every evening", "EVENING", "🔥")],
 steps=[("Pick your dates", "Check availability on WhatsApp."), ("Choose a room", "Deluxe, family suite or the full cottage."), ("Confirm with advance", "Simple advance to hold your booking."), ("Arrive & relax", "We welcome you with a hot drink.")],
 reviews=[("Peaceful stay and the home-cooked food was unforgettable.", "Arun & Deepa", "Couple, 2 nights"),
  ("Perfect for our family. The hosts treated us like their own.", "Mathew J.", "Family stay"),
  ("Beautiful views and very clean rooms. Will come back!", "Sarah L.", "Solo traveller")],
 faq=[("How much does a room cost at Green Valley Homestay in Munnar?", "Rooms start at ₹2,200 per night with breakfast included. Family suites are ₹3,800 and the entire cottage is ₹6,500 (sample rates)."),
  ("Is breakfast included in the room rate?", "Yes. A home-cooked Kerala breakfast is included. Lunch and dinner can be arranged on request."),
  ("What are the check-in and check-out times?", "Check-in is from 12 PM and check-out is by 11 AM. Early check-in is possible when rooms are free."),
  ("How do I get a direct booking discount?", "Message us on WhatsApp with your dates. Direct bookings get 10% off and a free welcome drink."),
  ("Do you arrange pickup and sightseeing?", "Yes. We can arrange pickup from Munnar town and local sightseeing with trusted drivers.")],
 offer=("Book direct, save 10%", "Message us directly for the best rate plus a free welcome drink.", "Check availability"),
 addr="Hill Road, Your Village", hours_txt="Check-in 12 PM · Check-out 11 AM", hours_spec=[("Mo-Su", "00:00", "23:59")],
 map="Homestay near Munnar, Kerala", form_title="Check availability", sel=("Room type", ["Deluxe room", "Family suite", "Entire cottage"]),
 extra=("Check-in date", "date", ""), intent="check room availability", nav_cta="Check dates", range="₹₹",
))
