from common import D

SITES = []

SITES.append(D(
 slug="jewellery", name="Aurelia Jewellers", brand=("Aurelia", " Jewellers"), cat="Jewellery & Retail", schema="JewelryStore", theme="dark", hero="center",
 acc="#e0b04a", acc2="#f3dc9a", on_acc="#1a1203", font="serif", emoji="💎",
 title="Gold & Diamond Jewellery Showroom in Thrissur | Aurelia",
 desc="Aurelia Jewellers in Thrissur: BIS hallmarked gold, diamond and bridal jewellery with transparent making charges, buyback and easy gold savings plan.",
 city="Thrissur", areas=["Thrissur", "Guruvayur", "Irinjalakuda", "Chalakudy", "Kodungallur", "Wadakkanchery"],
 h1=("Timeless jewellery,", "crafted", "for your moments"), badge=("BIS", "100% hallmarked gold"),
 lead="Aurelia Jewellers is a gold and diamond jewellery showroom in Thrissur with BIS hallmarked ornaments, transparent making charges, lifetime exchange and a monthly gold savings plan.",
 cta1="Visit our showroom", wa_hero="Hi, I would like to see your jewellery collection.",
 trust=["BIS hallmarked", "Transparent making charges", "Lifetime exchange"],
 chips=[("🏅 BIS hallmark", "on every piece"), ("💍 Bridal collections", "custom designs")],
 glance=[("Purity", "22K & 18K, BIS hallmarked"), ("Making charges", "From 6% (sample)"), ("Exchange", "Lifetime value"), ("Savings plan", "11-month scheme")],
 glance_h="Aurelia Jewellers at a glance",
 glance_p="Aurelia Jewellers in Thrissur sells BIS hallmarked 22K gold, diamond and bridal jewellery. Making charges start from 6%, old gold can be exchanged at full value and a monthly gold savings plan is available.",
 services_eye="Collections", services_h="Jewellery for every occasion", services_p="Traditional Kerala designs and modern pieces, certified and fairly priced.",
 services=[("💍", "Bridal jewellery", "Temple, antique and contemporary bridal sets."),
  ("💎", "Diamond jewellery", "Certified diamonds in rings, earrings and pendants."),
  ("🪙", "Gold coins & bars", "BIS hallmarked coins for gifting and investment."),
  ("🧿", "Daily wear & kids", "Light, elegant everyday and children's pieces."),
  ("🎨", "Custom design", "Your design ideas turned into finished jewellery."),
  ("♻️", "Exchange & repair", "Old gold exchange, polishing and repair services.")],
 why=("Trust built on every piece", "Pure gold, honest pricing and service that continues long after the sale.",
      [("BIS hallmarked purity", "Every ornament is hallmarked and certified."),
       ("Transparent pricing", "Gold rate, making and GST shown clearly on the bill."),
       ("Lifetime exchange", "Full value on exchange of your Aurelia jewellery."),
       ("Gold savings plan", "Pay monthly and redeem as jewellery.")]),
 stats=[("30+", "Years of trust"), ("5,000+", "Designs in stock"), ("100%", "Hallmarked gold"), ("11 months", "Savings plan")],
 plans_eye="Savings plans", plans_h="Plan your gold purchase", plans_p="Sample schemes shown. Terms vary by showroom.",
 plans=[("Gold Saver", "Small monthly steps", "2,000", "/month", ["11-month plan", "Bonus on final instalment", "Redeem on any jewellery", "Flexible start date"], "Join Gold Saver"),
  ("Wedding Plan", "Most popular", "10,000", "/month", ["11-month plan", "Bonus on final instalment", "Free bridal consultation", "Priority design booking"], "Join Wedding Plan"),
  ("Diamond Plan", "For special gifts", "5,000", "/month", ["11-month plan", "Certified diamond jewellery", "Complimentary cleaning", "Insurance on purchase"], "Join Diamond Plan")],
 show_eye="Featured", show_h="Collections customers love", show_p="A glimpse of what you'll find in our showroom.", work_nav="Collections",
 show=[("Temple bridal set", "22K · Kerala style", "BRIDAL", "👑"), ("Solitaire ring", "Certified diamond", "DIAMOND", "💍"), ("Kasavu-inspired necklace", "Light weight", "FESTIVE", "✨"), ("Gold coins", "BIS hallmarked", "INVEST", "🪙")],
 steps=[("Browse & choose", "Visit the showroom or see designs on WhatsApp."), ("Clear estimate", "Gold rate, weight, making and GST explained."), ("Custom or ready", "Pick ready jewellery or order a custom design."), ("Lifetime care", "Free cleaning, repair and exchange support.")],
 reviews=[("Beautiful bridal set and the billing was completely transparent.", "Reshma & Arun", "Wedding purchase"),
  ("Exchanged my old gold at a fair rate. Very trustworthy.", "Sathyan P.", "Exchange customer"),
  ("The gold savings plan made my daughter's wedding easier.", "Latha M.", "Savings plan")],
 faq=[("Is the gold at Aurelia Jewellers BIS hallmarked?", "Yes. All 22K and 18K gold jewellery at Aurelia is BIS hallmarked and comes with a purity certificate (sample information)."),
  ("What are the making charges for gold jewellery?", "Making charges start from about 6% depending on design and complexity, and are shown separately on the estimate (sample)."),
  ("Can I exchange my old gold jewellery?", "Yes. You can exchange old gold for new jewellery at the day's gold rate after purity testing."),
  ("Do you offer a gold savings scheme?", "Yes. Our 11-month savings plan lets you pay monthly instalments and redeem them as jewellery, with a bonus on the final instalment."),
  ("Can you make custom jewellery designs?", "Yes. Share a picture or idea and our designers will create a custom piece with a clear quote and timeline.")],
 offer=("Visit the showroom this wedding season", "Book a private viewing and bridal consultation with our designers.", "Book a viewing"),
 hours_txt="Mon–Sat 9:30 AM – 8 PM · Sun 10 AM – 6 PM", hours_spec=[("Mo-Sa", "09:30", "20:00"), ("Su", "10:00", "18:00")], addr="Round South, Your Locality", range="₹₹₹",
 map="Jewellery showroom near Thrissur, Kerala", form_title="Book a showroom visit", sel=("Interested in", ["Bridal jewellery", "Diamond jewellery", "Gold coins", "Custom design", "Gold savings plan"]),
 extra=("Preferred date", "date", ""), intent="visit the jewellery showroom", nav_cta="Visit us",
))

SITES.append(D(
 slug="travel", name="Wanderlust Holidays", brand=("Wander", "lust"), cat="Tourism & Travel", schema="TravelAgency",
 acc="#0369a1", acc2="#fb923c", bg="#f9fcff", font="bold", emoji="✈️",
 title="Travel Agency in Kochi | Kerala, Domestic & Gulf Tour Packages",
 desc="Wanderlust Holidays in Kochi: Kerala tour packages, Dubai and Europe holidays, honeymoon trips and flight, visa and hotel bookings from ₹7,999.",
 h1=("Journeys worth", "remembering,", "planned for you"), badge=("OFFER", "Honeymoon & family packages"),
 lead="Wanderlust Holidays plans Kerala, India and international tours from Kochi, with flights, hotels, visas and local guides included. Packages start from ₹7,999 per person.",
 cta1="Plan my trip", wa_hero="Hi, I would like to plan a holiday.",
 trust=["Flights, hotels & visas", "Local expert guides", "24×7 trip support"],
 chips=[("🌴 150+ destinations", "India & abroad"), ("🛟 24×7 support", "during your trip")],
 glance=[("Packages from", "₹7,999 / person"), ("Destinations", "Kerala, India, Gulf, Europe"), ("Visa help", "Included"), ("Support", "24×7 on trip")],
 glance_h="Wanderlust Holidays at a glance",
 glance_p="Wanderlust Holidays is a travel agency in Kochi offering Kerala and India tour packages, honeymoon trips, Dubai and Europe holidays, visa assistance, flights and hotel bookings. Packages start from ₹7,999 per person.",
 services_eye="What we offer", services_h="Every kind of holiday, planned end to end", services_p="Tell us your budget and dates. We handle everything else.",
 services=[("🌴", "Kerala tours", "Munnar, Alleppey, Kovalam and wildlife packages."),
  ("🗺️", "India holidays", "Rajasthan, Goa, Himachal, Kashmir and more."),
  ("🌍", "International packages", "Dubai, Singapore, Thailand, Europe and beyond."),
  ("💑", "Honeymoon specials", "Romantic stays, private transfers and surprises."),
  ("🛂", "Visa & documentation", "Assistance with tourist visas and travel documents."),
  ("✈️", "Flights & hotels", "Best fares and handpicked stays at every budget.")],
 why=("Travel without the stress", "From the first idea to the airport drop, one team looks after your whole trip.",
      [("Customised itineraries", "Built around your pace, budget and interests."),
       ("Trusted local partners", "Vetted hotels, drivers and guides."),
       ("Transparent pricing", "Clear inclusions and no hidden costs."),
       ("Support during travel", "A real person reachable 24×7.")]),
 stats=[("150+", "Destinations"), ("10k+", "Travellers served"), ("12", "Years in travel"), ("24×7", "Trip support")],
 plans_eye="Packages", plans_h="Popular holiday packages", plans_p="Sample prices per person on twin sharing. Rates change with season.",
 plans=[("Munnar & Thekkady", "3 nights / 4 days", "7,999", "/person", ["Hotel stay with breakfast", "Private cab & sightseeing", "Spice plantation visit", "Guide on request"], "Plan Kerala trip"),
  ("Dubai Holiday", "5 nights / 6 days", "42,999", "/person", ["Flights from Kochi", "Hotel with breakfast", "Desert safari & city tour", "Visa assistance"], "Plan Dubai trip"),
  ("Europe Highlights", "8 nights / 9 days", "1,29,999", "/person", ["Flights & Schengen visa help", "4-star stays", "Guided city tours", "Airport transfers"], "Plan Europe trip")],
 show_eye="Destinations", show_h="Where our travellers are going", show_p="Popular trips this season.", work_nav="Destinations",
 show=[("Alleppey houseboat", "2 days · from ₹6,500", "KERALA", "🛶"), ("Munnar hills", "3 nights · from ₹7,999", "HILLS", "🏞️"), ("Dubai", "5 nights · from ₹42,999", "GULF", "🏙️"), ("Maldives escape", "4 nights · honeymoon", "ISLAND", "🏝️")],
 steps=[("Share your plan", "Dates, budget, group size and interests."), ("Get a custom itinerary", "Day-wise plan with clear inclusions."), ("Confirm & book", "Pay a small advance to lock rates."), ("Travel with support", "We assist before and during your trip.")],
 reviews=[("Our Munnar trip was perfectly planned. Zero stress.", "Anita & Joseph", "Family trip"),
  ("Visa and flights sorted in days. Dubai was fantastic.", "Rahul S.", "Dubai holiday"),
  ("Honeymoon package exceeded expectations.", "Meera & Karthik", "Honeymoon")],
 faq=[("How much does a Kerala tour package cost from Kochi?", "Kerala tour packages from Kochi start around ₹7,999 per person for a 3-night Munnar and Thekkady trip with stay, breakfast and cab (sample price)."),
  ("Do you help with visas and flights?", "Yes. We assist with tourist visa documentation, flights and hotel bookings as part of international packages."),
  ("Can I customise my itinerary?", "Yes. All our packages can be customised for dates, hotel category, activities and group size."),
  ("What is the best time to visit Kerala?", "Kerala is pleasant from September to March, with monsoon from June to August being popular for Ayurveda and houseboat stays."),
  ("How do I book and pay?", "Share your plan on WhatsApp, approve the itinerary and pay a small advance. The balance is due before travel.")],
 offer=("Plan your dream holiday with us", "Share your dates and budget and get a custom itinerary within 24 hours.", "Plan my trip"),
 hours_txt="Mon–Sat 9:30 AM – 7 PM", hours_spec=[("Mo-Sa", "09:30", "19:00")], addr="MG Road, Your Locality",
 map="Travel agency near Kochi, Kerala", form_title="Plan your trip", sel=("Trip type", ["Kerala tour", "India holiday", "International trip", "Honeymoon", "Flights / visa only"]),
 extra=("Travel dates & travellers", "text", "e.g. 15–19 Dec, 4 people"), intent="plan a trip", nav_cta="Plan trip",
))

SITES.append(D(
 slug="manufacturing", name="PrecisionWorks Industries", brand=("Precision", "Works"), cat="Manufacturing", schema="LocalBusiness", font="grotesk",
 acc="#0f4c81", acc2="#f97316", bg="#f8fafc", emoji="🏭", city="Angamaly",
 areas=["Kalamassery", "Angamaly", "Perumbavoor", "Thrissur", "Palakkad", "Kollam"],
 title="CNC Machining & Metal Fabrication in Kerala | PrecisionWorks",
 desc="PrecisionWorks Industries in Angamaly: CNC machining, metal fabrication and sheet metal for OEMs with ISO 9001 quality, quick quotes and on-time delivery.",
 h1=("Precision parts,", "delivered", "on time"), badge=("ISO 9001", "Quality-certified manufacturing"),
 lead="PrecisionWorks Industries is a CNC machining and metal fabrication company in Angamaly, Kerala, supplying OEMs and industries with ISO 9001 quality, tight tolerances and quotes within 24 hours.",
 cta1="Request a quote", wa_hero="Hi, I would like to request a quote for manufacturing.",
 trust=["ISO 9001 quality", "Tolerance up to ±0.01 mm", "Quote in 24 hours"],
 chips=[("⚙️ 25+ CNC machines", "turning & milling"), ("📦 98% on-time delivery", "sample figure")],
 glance=[("Services", "CNC, fabrication, sheet metal"), ("Tolerance", "±0.01 mm"), ("Quote time", "Within 24 hours"), ("Certification", "ISO 9001:2015")],
 glance_h="PrecisionWorks Industries at a glance",
 glance_p="PrecisionWorks Industries manufactures precision CNC machined parts, metal fabrication and sheet metal components for OEMs and industrial customers in Kerala. Tolerances reach ±0.01 mm and quotes are provided within 24 hours.",
 services_eye="Capabilities", services_h="Manufacturing capabilities", services_p="From prototype to production, one trusted supplier for your components.",
 services=[("⚙️", "CNC turning & milling", "High-precision parts in steel, aluminium and brass."),
  ("🔧", "Metal fabrication", "Welding, cutting and assembly of structures."),
  ("📐", "Sheet metal work", "Laser cutting, bending and punching."),
  ("🧪", "Quality inspection", "CMM and gauge inspection with reports."),
  ("🎨", "Surface finishing", "Powder coating, anodising and plating partners."),
  ("📦", "Prototyping to production", "Small batches to high-volume supply.")],
 why=("A supplier you can depend on", "Consistent quality, honest lead times and engineers who understand your drawings.",
      [("ISO 9001 quality system", "Documented process and inspection."),
       ("Engineering support", "DFM feedback to reduce your cost."),
       ("Reliable lead times", "Planned production and clear updates."),
       ("Confidential & secure", "NDAs and drawing protection on request.")]),
 stats=[("25+", "CNC machines"), ("200+", "Industrial clients"), ("±0.01mm", "Tolerance"), ("20 yrs", "Experience")],
 plans_eye="How we quote", plans_h="Choose how you work with us", plans_p="Engagement options. Quotes are prepared from your drawing or sample.",
 plans=[("Prototype", "1 to 50 pieces", "On request", "", ["Quick turnaround", "Material suggestions", "Dimensional report", "Design feedback"], "Request prototype quote"),
  ("Batch production", "Most popular", "On request", "", ["50 to 5,000 pieces", "Process planning", "In-process inspection", "Scheduled delivery"], "Request batch quote"),
  ("Annual supply", "Contracts & OEMs", "On request", "", ["Rate contracts", "Stock & call-off", "Dedicated account manager", "Quarterly reviews"], "Discuss supply contract")],
 show_eye="Industries", show_h="Industries we supply", show_p="Components for a wide range of sectors.", work_nav="Industries",
 show=[("Automotive parts", "Shafts, bushes, brackets", "AUTO", "🚗"), ("Food machinery", "Stainless components", "FOOD", "🍽️"), ("Electrical & power", "Housings, busbars", "ELECTRICAL", "⚡"), ("Marine & fishing", "Corrosion-resistant parts", "MARINE", "⚓")],
 steps=[("Send your drawing", "Share a drawing, sample or specification."), ("Quote in 24 hours", "Clear price, material and lead time."), ("Production & inspection", "Manufactured with in-process checks."), ("Delivery with report", "Packed, documented and delivered on schedule.")],
 reviews=[("Consistent quality and always on schedule.", "Procurement head", "Auto components client"),
  ("Their engineers suggested changes that cut our part cost.", "Plant manager", "OEM client"),
  ("Reliable partner for our annual supply contract.", "Operations lead", "Industrial client")],
 faq=[("What materials and processes does PrecisionWorks work with?", "We machine steel, stainless steel, aluminium, brass and engineering plastics using CNC turning and milling, and also offer fabrication and sheet metal work."),
  ("What tolerances can you achieve?", "Our CNC machines can hold tolerances up to ±0.01 mm depending on the material, size and drawing (sample specification)."),
  ("How fast can I get a quote?", "We provide a quotation within 24 hours of receiving a drawing or sample."),
  ("Do you accept small prototype orders?", "Yes. We handle prototypes from a single piece up to full production batches."),
  ("Are you ISO certified?", "Yes. PrecisionWorks operates an ISO 9001:2015 quality management system with documented inspection.")],
 offer=("Send your drawing, get a quote in 24 hours", "Share a drawing or sample and our engineers will respond with price and lead time.", "Request quote"),
 hours_txt="Mon–Sat 8:30 AM – 6 PM", hours_spec=[("Mo-Sa", "08:30", "18:00")], addr="Industrial Estate, Your Locality", range="₹₹₹",
 map="Manufacturing unit near Angamaly, Kerala", form_title="Request a quote", sel=("Requirement", ["CNC machining", "Metal fabrication", "Sheet metal", "Prototype", "Annual supply contract"]),
 extra=("Material & quantity", "text", "e.g. EN8 steel, 500 pcs"), intent="request a manufacturing quote", nav_cta="Get quote",
))

SITES.append(D(
 slug="it-software", name="NexaCode Technologies", brand=("Nexa", "Code"), cat="IT & Software", schema="ProfessionalService", theme="dark", hero="center",
 acc="#6366f1", acc2="#22d3ee", font="grotesk", emoji="💻",
 title="Software Development Company in Kerala | NexaCode Technologies",
 desc="NexaCode Technologies in Kochi: custom software, web and mobile app development, cloud and AI solutions for startups and enterprises. Get a free consultation.",
 h1=("We build software", "that grows", "your business"), badge=("AI", "Now building AI-powered solutions"),
 lead="NexaCode Technologies is a software development company in Kochi building custom web apps, mobile apps, cloud systems and AI solutions for startups and enterprises, with a free technical consultation.",
 cta1="Book a free consultation", wa_hero="Hi, I would like to discuss a software project.",
 trust=["Agile delivery", "Dedicated team option", "NDA & IP protection"],
 chips=[("🚀 150+ projects", "delivered (sample)"), ("☁️ Cloud & AI ready", "scalable systems")],
 glance=[("Services", "Web, mobile, cloud, AI"), ("Projects from", "₹1.5 lakh"), ("Team model", "Fixed price or dedicated"), ("Consultation", "Free")],
 glance_h="NexaCode Technologies at a glance",
 glance_p="NexaCode Technologies develops custom web and mobile applications, ERP and CRM systems, cloud infrastructure and AI solutions for startups and enterprises in Kerala and abroad. Projects start from ₹1.5 lakh with a free consultation.",
 services_eye="Services", services_h="Technology that moves your business forward", services_p="From MVP to enterprise platforms, built with modern, scalable stacks.",
 services=[("🌐", "Web application development", "Fast, secure web platforms and portals."),
  ("📱", "Mobile app development", "Android, iOS and cross-platform apps."),
  ("🧩", "ERP, CRM & custom software", "Systems tailored to your workflows."),
  ("☁️", "Cloud & DevOps", "AWS, Azure and Google Cloud deployment."),
  ("🤖", "AI & automation", "Chatbots, analytics and process automation."),
  ("🎨", "UI/UX design", "Research-led, conversion-focused interfaces.")],
 why=("A technology partner, not just a vendor", "We take ownership of outcomes and communicate clearly at every sprint.",
      [("Experienced engineers", "Senior developers and architects."),
       ("Agile, transparent delivery", "Weekly demos and clear milestones."),
       ("Secure by design", "Best practices and code reviews."),
       ("Post-launch support", "Maintenance and scaling help.")]),
 stats=[("150+", "Projects delivered"), ("40+", "Engineers"), ("12", "Years building"), ("98%", "Client retention (sample)")],
 plans_eye="Engagement models", plans_h="Work with us your way", plans_p="Sample starting prices. Final quote after requirement discussion.",
 plans=[("MVP Build", "For startups", "1,50,000", "starting", ["Discovery & UX", "Web or mobile MVP", "8 to 12 weeks", "Post-launch support"], "Plan my MVP"),
  ("Dedicated Team", "Most popular", "1,80,000", "/month", ["Developers + QA + PM", "Scalable team size", "Weekly sprints", "Monthly reporting"], "Hire a team"),
  ("Enterprise", "Complex systems", "On request", "", ["Architecture & roadmap", "Security & compliance", "Integrations", "SLA support"], "Talk to an architect")],
 show_eye="Case studies", show_h="What we've built", show_p="A sample of solutions across industries.", work_nav="Work",
 show=[("Fleet tracking platform", "Web + mobile · logistics", "LOGISTICS", "🚚"), ("Hospital management system", "Cloud ERP · healthcare", "HEALTHCARE", "🏥"), ("Online learning app", "Mobile · education", "EDTECH", "🎓"), ("AI chatbot", "Support automation", "AI", "🤖")],
 steps=[("Discovery", "We understand goals, users and constraints."), ("Design & plan", "Wireframes, architecture and a clear estimate."), ("Build in sprints", "Weekly demos and feedback loops."), ("Launch & scale", "Deployment, monitoring and ongoing support.")],
 reviews=[("They delivered our MVP on time and the quality was excellent.", "Founder", "Startup client"),
  ("Responsive team that really understood our business.", "CTO", "Enterprise client"),
  ("The dedicated team model worked beautifully for us.", "Product head", "SaaS client")],
 faq=[("How much does custom software development cost in India?", "Custom software projects at NexaCode typically start from ₹1.5 lakh for an MVP, and a dedicated development team starts from about ₹1.8 lakh per month (sample prices)."),
  ("How long does it take to build a mobile app?", "A typical MVP takes 8 to 12 weeks, depending on features, platforms and integrations."),
  ("Do you sign NDAs and protect our IP?", "Yes. We sign NDAs before discussions and all code and IP are transferred to you on payment."),
  ("Can you maintain our application after launch?", "Yes. We offer maintenance, monitoring and new feature development under flexible support plans."),
  ("Which technologies do you work with?", "We work with React, Node.js, Python, Java, Flutter, React Native, AWS, Azure and modern AI tools.")],
 offer=("Have an idea? Let's build it", "Book a free technical consultation and get a clear roadmap and estimate.", "Book consultation"),
 hours_txt="Mon–Fri 9:30 AM – 6:30 PM", hours_spec=[("Mo-Fr", "09:30", "18:30")], addr="Tech Park Road, Infopark", range="₹₹₹",
 map="Software company near Infopark Kochi, Kerala", form_title="Tell us about your project", sel=("Project type", ["Web application", "Mobile app", "ERP / CRM", "Cloud / DevOps", "AI / automation", "UI/UX design"]),
 extra=("Budget & timeline", "text", "e.g. ₹3 lakh, 3 months"), intent="discuss a software project", nav_cta="Free consult",
))

SITES.append(D(
 slug="fashion", name="Maison Vela Boutique", brand=("Maison", " Vela"), cat="Fashion & Lifestyle", schema="ClothingStore", hero="center",
 acc="#111827", acc2="#e8a98c", bg="#fdfaf8", font="serif", emoji="👗",
 title="Designer Boutique in Kochi | Sarees, Kurtis & Bridal Wear",
 desc="Maison Vela Boutique in Kochi: designer sarees, kurtis, bridal wear and custom tailoring with free alterations. Shop online on WhatsApp or visit the store.",
 h1=("Wear your", "story,", "beautifully"), badge=("NEW", "Festive collection just arrived"),
 lead="Maison Vela is a designer boutique in Kochi offering sarees, kurtis, lehengas and custom bridal wear, with free alterations and shopping by video call or WhatsApp.",
 cta1="Shop the collection", wa_hero="Hi, I would like to see your latest collection.",
 trust=["Custom tailoring", "Free alterations", "Shop by video call"],
 chips=[("🧵 Custom tailoring", "ready in 7 days"), ("📦 Pan-India delivery", "COD available")],
 glance=[("Categories", "Sarees, kurtis, bridal"), ("Price range", "From ₹1,499"), ("Tailoring", "Custom, 7 days"), ("Delivery", "Pan-India")],
 glance_h="Maison Vela Boutique at a glance",
 glance_p="Maison Vela Boutique in Kochi sells designer sarees, kurtis, lehengas and bridal wear with custom tailoring in about 7 days and free alterations. Prices start from ₹1,499 and orders can be placed in store or on WhatsApp.",
 services_eye="Collections", services_h="Fashion for every celebration", services_p="Handpicked designs and custom pieces made for you.",
 services=[("🥻", "Sarees", "Kasavu, silk, cotton and designer sarees."),
  ("👘", "Kurtis & co-ords", "Everyday and festive kurtis in sizes S to 5XL."),
  ("👰", "Bridal & lehengas", "Custom bridal wear with trial fittings."),
  ("🧵", "Custom tailoring", "Stitched to your measurements in 7 days."),
  ("👨", "Menswear", "Ethnic wear, kurtas and festive collections."),
  ("💍", "Accessories", "Jewellery, dupattas and matching accessories.")],
 why=("Style that fits you perfectly", "Quality fabric, careful finishing and personal styling at every step.",
      [("Personal styling", "Help choosing outfits for your occasion."),
       ("Free alterations", "Perfect fit on every purchase."),
       ("Exclusive designs", "Limited pieces you won't find everywhere."),
       ("Easy shopping", "Visit, video call or order on WhatsApp.")]),
 stats=[("5,000+", "Happy customers"), ("500+", "Designs"), ("7 days", "Tailoring time"), ("Pan-India", "Delivery")],
 plans_eye="Price guide", plans_h="Fashion for every budget", plans_p="Sample starting prices. Final price depends on design and fabric.",
 plans=[("Everyday wear", "Kurtis & cotton sarees", "1,499", "starting", ["Quality fabrics", "Free alterations", "Easy exchange", "New arrivals weekly"], "Shop everyday wear"),
  ("Festive & party", "Most popular", "4,999", "starting", ["Designer sarees & lehengas", "Matching accessories", "Free alterations", "Gift packaging"], "Shop festive"),
  ("Bridal couture", "Custom made", "24,999", "starting", ["Custom bridal outfit", "Trial fitting", "Hand embroidery", "Dedicated stylist"], "Book bridal consultation")],
 show_eye="Lookbook", show_h="This season's looks", show_p="A peek at our latest collections.", work_nav="Lookbook",
 show=[("Kasavu festive saree", "Onam collection", "SAREE", "🥻"), ("Pastel kurti set", "Daily elegance", "KURTI", "👘"), ("Bridal lehenga", "Custom embroidery", "BRIDAL", "👰"), ("Menswear kurta", "Festive edit", "MEN", "👨")],
 steps=[("Browse or visit", "Visit the boutique or browse on WhatsApp."), ("Style & fit", "Personal styling and measurements."), ("Tailor & finish", "Stitched, finished and checked for fit."), ("Delivery or pickup", "Ship pan-India or collect from the store.")],
 reviews=[("My bridal lehenga was exactly how I imagined it.", "Nithya R.", "Bride"),
  ("Lovely collection and the stylists are very helpful.", "Jasmine A.", "Regular customer"),
  ("Ordered a saree on WhatsApp. Arrived beautifully packed.", "Divya S.", "Online order")],
 faq=[("How much does custom tailoring cost at Maison Vela?", "Custom stitching starts around ₹1,499 for kurtis and ₹24,999 for bridal wear, depending on design and fabric (sample prices)."),
  ("How long does tailoring take?", "Most custom outfits are ready in about 7 days. Bridal pieces take 3 to 4 weeks including trials."),
  ("Do you offer alterations?", "Yes. Alterations are free on all purchases from our boutique."),
  ("Can I shop online or on WhatsApp?", "Yes. You can browse by video call or WhatsApp and we deliver across India with cash on delivery available."),
  ("Do you have plus-size options?", "Yes. Our kurti and tailoring ranges cover sizes S to 5XL, and custom tailoring is available for every body type.")],
 offer=("Festive collection is here", "Visit the boutique or shop on WhatsApp and get free alterations on every outfit.", "Shop now"),
 hours_txt="Mon–Sat 10 AM – 8:30 PM · Sun 11 AM – 7 PM", hours_spec=[("Mo-Sa", "10:00", "20:30"), ("Su", "11:00", "19:00")], addr="Boutique Street, Your Locality", range="₹₹",
 map="Boutique near Kochi, Kerala", form_title="Book a styling visit", sel=("Interested in", ["Sarees", "Kurtis & co-ords", "Bridal wear", "Custom tailoring", "Menswear"]),
 extra=("Occasion / date", "text", "e.g. Wedding, 20 Jan"), intent="shop at the boutique", nav_cta="Shop now",
))

SITES.append(D(
 slug="ecommerce", name="Kerala Spice Co.", brand=("Kerala", "Spice"), cat="E-commerce Store", schema="Store", hero="split",
 acc="#c026d3", acc2="#fb923c", bg="#fffafe", font="bold", emoji="🛒",
 title="Buy Kerala Spices Online | Kerala Spice Co. Free Shipping",
 desc="Kerala Spice Co.: pure cardamom, pepper, cinnamon and spice gift boxes direct from Idukki farms. Free shipping above ₹499 and easy 7-day returns.",
 h1=("Farm-fresh spices,", "shipped", "to your door"), badge=("FREE", "Shipping above ₹499"),
 lead="Kerala Spice Co. sells pure cardamom, black pepper, cinnamon and gift boxes sourced directly from Idukki farms, with free shipping above ₹499 and easy 7-day returns.",
 cta1="Shop on WhatsApp", wa_hero="Hi, I would like to order spices.",
 trust=["Direct from farms", "Free shipping above ₹499", "7-day easy returns"],
 chips=[("🌶️ 50+ products", "pure & fresh"), ("🚚 Ships in 24 hrs", "pan-India")],
 glance=[("Products", "50+ spices & gift boxes"), ("Free shipping", "Above ₹499"), ("Dispatch", "Within 24 hours"), ("Returns", "7 days")],
 glance_h="Kerala Spice Co. at a glance",
 glance_p="Kerala Spice Co. is an online store selling pure Kerala cardamom, black pepper, cinnamon, cloves and spice gift boxes direct from farms in Idukki. Orders ship within 24 hours, free above ₹499, with 7-day returns.",
 services_eye="Shop by category", services_h="Pure spices, from farm to kitchen", services_p="Single-origin, small-batch and packed fresh.",
 services=[("🫚", "Cardamom", "Bold, aromatic green cardamom from Idukki."),
  ("⚫", "Black pepper", "Tellicherry-style bold pepper, sun dried."),
  ("🌿", "Cinnamon & cloves", "Fresh whole spices with rich aroma."),
  ("🍛", "Masala blends", "House blends for curry, biriyani and more."),
  ("🎁", "Gift boxes", "Beautiful spice hampers for gifting."),
  ("🏢", "Bulk & wholesale", "Special pricing for restaurants and retailers.")],
 why=("Why customers reorder", "Freshness, honest pricing and packaging that keeps the aroma locked in.",
      [("Direct from farmers", "Fair prices and traceable sourcing."),
       ("Packed fresh to order", "Airtight pouches and quick dispatch."),
       ("Lab-tested quality", "Purity and no artificial colours."),
       ("Easy returns", "Not happy? Return within 7 days.")]),
 stats=[("20k+", "Orders shipped"), ("4.8", "Average rating (sample)"), ("50+", "Products"), ("24 hrs", "Dispatch time")],
 plans_eye="Bestsellers", plans_h="Customer favourites", plans_p="Sample prices shown. Replace with your actual catalogue.",
 plans=[("Green Cardamom 100g", "Bold 8mm pods", "499", "/100g", ["Idukki-grown", "Fresh aroma", "Airtight pouch", "Free shipping"], "Order cardamom"),
  ("Spice Gift Box", "Most gifted", "1,299", "/box", ["6 premium spices", "Wooden gift box", "Recipe card", "Gift message"], "Order gift box"),
  ("Pepper 250g", "Tellicherry style", "349", "/250g", ["Sun-dried", "Strong, bold flavour", "Single origin", "Free shipping above ₹499"], "Order pepper")],
 show_eye="Gift ideas", show_h="Hampers & collections", show_p="Thoughtful gifts straight from Kerala.", work_nav="Gifts",
 show=[("Festive hamper", "8 spices + sweets", "GIFT", "🎁"), ("Cooking starter kit", "10 essential spices", "KIT", "🍛"), ("Ayurveda tea set", "Herbs & spices", "WELLNESS", "🍵"), ("Bulk pack", "5 kg for restaurants", "BULK", "📦")],
 steps=[("Choose products", "Browse and pick your spices or gift box."), ("Order & pay", "Pay online, on delivery or via WhatsApp."), ("Packed & shipped", "Dispatched within 24 hours."), ("Enjoy fresh flavour", "Delivered in 2 to 5 days across India.")],
 reviews=[("The cardamom smells incredible. Far better than supermarket packs.", "Sunita B.", "Bangalore customer"),
  ("Gifted the spice box to my parents. They loved it.", "Rahul M.", "Gift buyer"),
  ("We order pepper in bulk for our restaurant every month.", "Chef Mathew", "Restaurant client")],
 faq=[("Are your Kerala spices pure and fresh?", "Yes. We source directly from farmers in Idukki and pack to order, with no artificial colours or fillers (sample information)."),
  ("What are the shipping charges?", "Shipping is free on orders above ₹499. Below that, a small flat shipping fee applies."),
  ("How long does delivery take?", "Orders are dispatched within 24 hours and usually arrive in 2 to 5 days across India."),
  ("Can I return an order?", "Yes. You can request a return within 7 days if there is a quality issue or the wrong item is received."),
  ("Do you offer wholesale prices?", "Yes. We offer bulk pricing for restaurants, retailers and gifting. Message us with your requirement.")],
 offer=("Free shipping above ₹499", "Order today and get pure Kerala spices delivered in 2 to 5 days.", "Shop now"),
 hours_txt="Mon–Sat 9 AM – 7 PM (orders 24×7 online)", hours_spec=[("Mo-Sa", "09:00", "19:00")], addr="Spice Market Road, Your Locality",
 map="Spice shop near Kochi, Kerala", form_title="Place an order", sel=("Interested in", ["Cardamom", "Black pepper", "Cinnamon & cloves", "Gift box", "Bulk / wholesale"]),
 extra=("Quantity / pincode", "text", "e.g. 2 packs, 682001"), intent="place an order", nav_cta="Order now",
))

SITES.append(D(
 slug="corporate-b2b", name="Apex Business Solutions", brand=("Apex", " Business"), cat="Corporate & B2B", schema="ProfessionalService",
 acc="#334155", acc2="#c9a227", bg="#f8f9fb", font="sans", emoji="🏢",
 title="Business Consulting & Outsourcing in Kochi | Apex Business",
 desc="Apex Business Solutions in Kochi: B2B consulting, HR and payroll, business setup and corporate outsourcing for growing companies. Request a proposal today.",
 h1=("Business services,", "built for", "growing companies"), badge=("B2B", "Trusted by 300+ companies"),
 lead="Apex Business Solutions provides B2B consulting, HR and payroll outsourcing, business setup and compliance services to growing companies in Kerala, with dedicated account managers and transparent pricing.",
 cta1="Request a proposal", wa_hero="Hi, I would like a proposal for business services.",
 trust=["Dedicated account manager", "Confidential & secure", "Transparent pricing"],
 chips=[("🤝 300+ companies", "served (sample)"), ("📈 Scalable services", "grow with you")],
 glance=[("Services", "Consulting, HR, compliance"), ("Clients", "Startups to enterprises"), ("Engagement", "Project or retainer"), ("Proposal", "Within 48 hours")],
 glance_h="Apex Business Solutions at a glance",
 glance_p="Apex Business Solutions offers business consulting, HR and payroll outsourcing, company setup and compliance, procurement support and corporate training to startups and mid-sized companies in Kerala, with proposals within 48 hours.",
 services_eye="Services", services_h="Everything your business needs to scale", services_p="One partner for the functions that let you focus on your core business.",
 services=[("📊", "Business consulting", "Strategy, operations and growth advisory."),
  ("👥", "HR & payroll outsourcing", "Recruitment, payroll and statutory compliance."),
  ("🏛️", "Company setup & compliance", "Registration, licences and ongoing filings."),
  ("📦", "Procurement & vendor management", "Sourcing support and vendor negotiation."),
  ("🎓", "Corporate training", "Leadership and skills programs for your teams."),
  ("🛡️", "Risk & audit support", "Process audits and internal controls.")],
 why=("A partner invested in your growth", "We act as an extension of your team with clear deliverables and honest reporting.",
      [("Experienced consultants", "Domain experts across industries."),
       ("Clear scope & pricing", "Defined deliverables and timelines."),
       ("Dedicated account manager", "One point of contact for everything."),
       ("Confidential & secure", "NDAs and strict data practices.")]),
 stats=[("300+", "Companies served"), ("15+", "Years of experience"), ("60+", "Consultants"), ("48 hrs", "Proposal time")],
 plans_eye="Engagements", plans_h="Flexible ways to work together", plans_p="Sample starting prices. Customised after a scoping call.",
 plans=[("Project", "Defined scope", "50,000", "starting", ["Clear deliverables", "Fixed timeline", "Weekly updates", "Final report"], "Discuss a project"),
  ("Retainer", "Most popular", "75,000", "/month", ["Dedicated consultant", "Monthly planning", "Priority response", "Quarterly review"], "Request retainer proposal"),
  ("Outsourced function", "HR, payroll, compliance", "On request", "", ["Full process ownership", "SLA-based delivery", "Dashboard reporting", "Scalable team"], "Discuss outsourcing")],
 show_eye="Industries", show_h="Sectors we work with", show_p="Experience across a wide range of businesses.", work_nav="Sectors",
 show=[("Manufacturing", "Operations & compliance", "INDUSTRY", "🏭"), ("Healthcare", "HR & payroll", "HEALTH", "🏥"), ("Retail & trading", "Vendor management", "RETAIL", "🛍️"), ("Technology", "Setup & hiring", "TECH", "💻")],
 steps=[("Scoping call", "Understand your needs and priorities."), ("Proposal in 48 hours", "Scope, team, timeline and pricing."), ("Onboarding", "Kick-off with your account manager."), ("Delivery & reviews", "Regular reporting and improvements.")],
 reviews=[("They handled payroll and compliance so we could focus on growth.", "Managing Director", "Trading company"),
  ("Professional, responsive and genuinely helpful.", "Finance head", "Manufacturing client"),
  ("Clear reporting and no surprises. Highly recommended.", "CEO", "Startup")],
 faq=[("What services does Apex Business Solutions offer to companies?", "We offer business consulting, HR and payroll outsourcing, company setup and compliance, procurement support, corporate training and process audit services."),
  ("How much do your B2B services cost?", "Projects start from about ₹50,000 and monthly retainers from about ₹75,000 (sample prices). We send a customised proposal after a scoping call."),
  ("How quickly can we get a proposal?", "You receive a written proposal with scope, timeline and pricing within 48 hours of the scoping call."),
  ("Do you work with startups and small businesses?", "Yes. We work with startups, SMEs and large companies, and scale the engagement to your stage."),
  ("Is our business information kept confidential?", "Yes. We sign NDAs and follow strict data-handling practices on every engagement.")],
 offer=("Let's talk about your business goals", "Book a scoping call and get a tailored proposal in 48 hours.", "Request proposal"),
 hours_txt="Mon–Fri 9:30 AM – 6:30 PM · Sat 10 AM – 2 PM", hours_spec=[("Mo-Fr", "09:30", "18:30"), ("Sa", "10:00", "14:00")], addr="Business Tower, Your Locality", range="₹₹₹",
 map="Business consulting office near Kochi, Kerala", form_title="Request a proposal", sel=("Service needed", ["Business consulting", "HR & payroll", "Company setup & compliance", "Procurement", "Corporate training"]),
 extra=("Company name & size", "text", "e.g. ABC Traders, 40 staff"), intent="request a business proposal", nav_cta="Get proposal",
))

SITES.append(D(
 slug="finance-insurance", name="SecureWealth Advisors", brand=("Secure", "Wealth"), cat="Finance & Insurance", schema="InsuranceAgency",
 acc="#065f46", acc2="#38bdf8", bg="#f8fcfa", font="sans", emoji="🏦",
 title="Insurance & Mutual Fund Advisor in Kochi | SecureWealth",
 desc="SecureWealth Advisors in Kochi: life, health and motor insurance, mutual funds, SIPs and loan assistance. Free policy review and personalised financial plan.",
 h1=("Protect today,", "grow", "for tomorrow"), badge=("FREE", "Policy & portfolio review"),
 lead="SecureWealth Advisors helps families in Kochi with life, health and motor insurance, mutual funds and SIPs, and home and business loans. Get a free policy review and a personalised financial plan.",
 cta1="Get free review", wa_hero="Hi, I would like a free insurance and investment review.",
 trust=["Unbiased advice", "20+ insurers & AMCs", "Claim support"],
 chips=[("🛡️ 20+ insurers", "compare & choose"), ("📈 SIP from ₹500", "start small")],
 glance=[("Services", "Insurance, SIP, loans"), ("SIP from", "₹500 / month"), ("Review", "Free"), ("Claims help", "Included")],
 glance_h="SecureWealth Advisors at a glance",
 glance_p="SecureWealth Advisors in Kochi offers life, health, motor and business insurance, mutual funds and SIPs, and home and business loan assistance from 20+ insurers and fund houses. SIPs start from ₹500 a month and the policy review is free.",
 services_eye="Services", services_h="Complete financial protection and growth", services_p="Plain-language advice and help at every stage of life.",
 services=[("❤️", "Life insurance", "Term and savings plans for family protection."),
  ("🏥", "Health insurance", "Individual, family and senior citizen plans."),
  ("🚗", "Motor & general insurance", "Car, bike, home and business cover."),
  ("📈", "Mutual funds & SIP", "Goal-based investing from ₹500 a month."),
  ("🏠", "Home & business loans", "Assistance with documentation and approvals."),
  ("👴", "Retirement planning", "Build income that lasts through retirement.")],
 why=("Advice you can understand and trust", "We recommend what fits your needs, not what pays the highest commission.",
      [("Unbiased comparison", "Plans compared across multiple insurers."),
       ("Goal-based planning", "Education, home, retirement and more."),
       ("Claims assistance", "We stand by you when you need to claim."),
       ("Regular reviews", "Yearly portfolio and policy check-ups.")]),
 stats=[("3,000+", "Families advised"), ("20+", "Insurance partners"), ("₹50 Cr+", "Assets advised (sample)"), ("12 yrs", "Experience")],
 plans_eye="Packages", plans_h="Start where you are", plans_p="Advisory is free. You pay only for the products you choose.",
 plans=[("Protection Check", "Know your cover gap", "Free", "", ["Review of existing policies", "Cover gap analysis", "Plan comparison", "No obligation"], "Get free review"),
  ("Family Plan", "Most popular", "Free", "", ["Life + health + motor", "Goal-based SIP plan", "Annual review", "Claims support"], "Plan for my family"),
  ("Business Cover", "For entrepreneurs", "Free", "", ["Business & liability cover", "Key-person insurance", "Employee health plans", "Loan assistance"], "Cover my business")],
 show_eye="Goals", show_h="What are you planning for?", show_p="Common goals we help families achieve.", work_nav="Goals",
 show=[("Child education", "SIP + protection", "EDUCATION", "🎓"), ("Dream home", "Loan + insurance", "HOME", "🏠"), ("Retirement", "Income for life", "RETIRE", "👴"), ("Family protection", "Term + health", "PROTECT", "🛡️")],
 steps=[("Free consultation", "Share your goals, income and existing cover."), ("Compare & recommend", "Clear, side-by-side options."), ("Apply & issue", "We handle paperwork and onboarding."), ("Review yearly", "Regular reviews and claims support.")],
 reviews=[("They found us better health cover at a lower premium.", "Sreekumar P.", "Health insurance"),
  ("My SIP journey started here and I finally have a clear plan.", "Aishwarya N.", "Mutual funds"),
  ("Helped with a smooth claim during a hospital stay.", "Joseph K.", "Claim support")],
 faq=[("How much life insurance cover do I need?", "A common guide is 10 to 15 times your annual income, adjusted for loans and goals. We calculate this with you during a free review."),
  ("What is the minimum amount to start a SIP?", "You can start a mutual fund SIP from ₹500 a month with most fund houses."),
  ("Is your advice free?", "Yes. Policy reviews and planning are free. We are paid by the insurers and fund houses for products you choose, and we disclose this clearly."),
  ("Can you help with claim settlement?", "Yes. We guide you through documentation and follow up with the insurer to support your claim."),
  ("Do you help with home and business loans?", "Yes. We help compare lenders, prepare documents and track approvals for home and business loans.")],
 offer=("Get your free policy and portfolio review", "See where you're covered, where you're not and how to fix it.", "Get free review"),
 hours_txt="Mon–Sat 9:30 AM – 6:30 PM", hours_spec=[("Mo-Sa", "09:30", "18:30")], addr="Finance Centre, Your Locality", range="₹₹",
 map="Insurance advisor office near Kochi, Kerala", form_title="Get a free review", sel=("I need help with", ["Life insurance", "Health insurance", "Motor / general insurance", "Mutual funds & SIP", "Home / business loan", "Retirement planning"]),
 intent="get a free financial review", nav_cta="Free review",
))

SITES.append(D(
 slug="legal", name="Justicia Law Chambers", brand=("Justicia", " Law"), cat="Legal & Professional Services", schema="LegalService",
 acc="#1e293b", acc2="#b45309", bg="#faf9f6", font="serif", emoji="⚖️",
 title="Advocates & Legal Services in Kochi | Justicia Law Chambers",
 desc="Justicia Law Chambers in Kochi: property, family, corporate and cheque-bounce legal services by experienced advocates. Book a confidential consultation.",
 h1=("Clear legal advice,", "trusted", "representation"), badge=("CONFIDENTIAL", "First consultation ₹500"),
 lead="Justicia Law Chambers is a law firm in Kochi handling property, family, civil, criminal, corporate and cheque-bounce matters. Book a confidential consultation with an experienced advocate.",
 cta1="Book consultation", wa_hero="Hi, I would like a legal consultation.",
 trust=["Confidential consultations", "Court & documentation", "Fixed, clear fees"],
 chips=[("⚖️ 2,000+ cases", "handled (sample)"), ("🔒 100% confidential", "attorney-client")],
 glance=[("Practice areas", "Property, family, corporate"), ("Consultation", "From ₹500"), ("Courts", "High Court & district"), ("Response", "Same day")],
 glance_h="Justicia Law Chambers at a glance",
 glance_p="Justicia Law Chambers in Kochi provides legal services in property and title verification, family law, civil and criminal matters, corporate and contract law, and cheque-bounce cases. A first consultation starts at ₹500 and all discussions are confidential.",
 services_eye="Practice areas", services_h="Legal help when it matters most", services_p="Practical advice and strong representation across key areas of law.",
 services=[("🏠", "Property & title verification", "Due diligence, agreements and registration."),
  ("👨‍👩‍👧", "Family law", "Divorce, custody, maintenance and wills."),
  ("🏛️", "Civil & criminal litigation", "Representation in district courts and High Court."),
  ("📑", "Corporate & contracts", "Agreements, company law and compliance."),
  ("💳", "Cheque bounce & recovery", "Notices, complaints and money recovery."),
  ("🌐", "NRI legal services", "Property, power of attorney and family matters.")],
 why=("Advice you can rely on", "We explain your options in simple terms and act in your best interest.",
      [("Experienced advocates", "Decades of combined courtroom practice."),
       ("Strict confidentiality", "Your matters stay private."),
       ("Transparent fees", "Clear fee discussion before we start."),
       ("Prompt communication", "Regular updates on your case.")]),
 stats=[("2,000+", "Cases handled"), ("20+", "Years of practice"), ("6", "Advocates"), ("Same day", "Response")],
 plans_eye="Fees", plans_h="Clear and fair legal fees", plans_p="Sample fees shown. Exact fees depend on the matter.",
 plans=[("Consultation", "30–45 minutes", "500", "/session", ["Confidential discussion", "Case assessment", "Document review", "Next-step advice"], "Book consultation"),
  ("Property verification", "Most requested", "7,500", "starting", ["Title & encumbrance check", "Legal opinion report", "Agreement review", "Registration guidance"], "Book verification"),
  ("Litigation support", "Court matters", "On request", "", ["Case strategy", "Filing & representation", "Regular updates", "Fixed-fee options"], "Discuss my case")],
 show_eye="Experience", show_h="Matters we handle often", show_p="Common legal issues clients bring to us.", work_nav="Matters",
 show=[("Property title dispute", "Civil · High Court", "PROPERTY", "🏠"), ("Cheque-bounce complaint", "Section 138 · recovery", "CHEQUE", "💳"), ("Family settlement", "Mediation & drafting", "FAMILY", "👨‍👩‍👧"), ("Company agreements", "Contracts & compliance", "CORPORATE", "📑")],
 steps=[("Confidential consultation", "Explain your matter and goals."), ("Assessment & fee", "Clear legal options and fee estimate."), ("Action & drafting", "Notices, filings or agreements prepared."), ("Representation & updates", "Court appearances and regular updates.")],
 reviews=[("They explained everything clearly and resolved our property matter quickly.", "Gopinath K.", "Property client"),
  ("Compassionate and professional during a difficult time.", "Anita S.", "Family law client"),
  ("Cheque-bounce matter settled well within the expected time.", "Rajeev T.", "Business owner")],
 faq=[("How much does a lawyer consultation cost in Kochi?", "A first consultation at Justicia Law Chambers starts at ₹500 for 30 to 45 minutes (sample fee). Further fees depend on the matter and are agreed upfront."),
  ("Do you handle property title verification?", "Yes. We verify title documents, encumbrance and approvals and provide a written legal opinion before you buy."),
  ("Can you help with a cheque bounce case?", "Yes. We send the legal notice, file the complaint under Section 138 and represent you through to recovery."),
  ("Are consultations confidential?", "Yes. All discussions are protected by attorney-client confidentiality."),
  ("Do you assist NRI clients?", "Yes. We help NRIs with property matters, powers of attorney and family issues, with online consultations available.")],
 offer=("Speak to an advocate today", "Book a confidential consultation and understand your options clearly.", "Book consultation"),
 hours_txt="Mon–Sat 10 AM – 6 PM", hours_spec=[("Mo-Sa", "10:00", "18:00")], addr="Court Road, Your Locality", range="₹₹",
 map="Law office near Kochi High Court, Kerala", form_title="Book a confidential consultation", sel=("Matter type", ["Property / title", "Family law", "Civil / criminal", "Corporate / contracts", "Cheque bounce / recovery", "NRI legal matter"]),
 extra=("Brief about your matter", "text", "e.g. property dispute"), intent="book a legal consultation", nav_cta="Consult",
))
