"""Industry landing page content (1 of 3). Each entry is written for that industry; do not copy-paste between entries."""
INDS = []
def I(**kw): INDS.append(kw)

I(demo="gym", url="gyms-and-fitness-centres", name="Gyms & Fitness Centres", short="Gym", singular="gym",
  kf="membership plans, trainer profiles, free-trial booking and WhatsApp enquiries",
  intro="A gym website has one job: turn a curious visitor into a free-trial booking. People choose a gym by location, price and the trainers they will meet, so your site should show all three in the first scroll and make enquiring one tap away.",
  queries=["gym near me Thrissur", "gym membership fees in Kochi", "best gym for weight loss near me", "personal trainer in Kozhikode", "women only gym Kerala"],
  needs=[("Clear membership plans", "List monthly, quarterly and yearly plans with prices so visitors can compare without phoning you."),
         ("Free-trial booking", "A visible button that opens WhatsApp with the visitor's name and fitness goal already filled in."),
         ("Trainer profiles", "Photos and certifications show who will coach them and build trust faster than any slogan."),
         ("Batch timetable", "A simple schedule (morning HIIT, yoga, women's batch) answers the most common question before anyone calls."),
         ("Location and timings", "A map, parking note and opening hours, marked up so Google can show them directly in results."),
         ("Real member results", "Transformations shared with permission and described honestly beat generic stock photos.")],
  mistakes=[("Hiding prices behind 'call us'", "Most visitors will not call just to learn a price. Show starting prices and your free-trial offer."),
            ("One long page with no clear next step", "Put a trial or WhatsApp button in the header, the hero and the footer."),
            ("Stock photos of other gyms", "Use real photos of your floor, equipment and trainers, even if taken on a phone.")],
  faq=[("How much does a gym website cost in Kerala?", "A single-page gym website with a free-trial form and WhatsApp button starts at ₹5,000 with Qrenzy, and a complete six-section website with SEO is typically ₹12,000. The first-year domain and hosting are included."),
       ("What should a gym website include?", "It should include membership plans, trainer profiles, a batch timetable, a map with opening hours and a free-trial button. A short FAQ about timings, women's batches and parking also helps Google and AI assistants answer questions about your gym."),
       ("Can members book a free trial on WhatsApp?", "Yes. The enquiry form opens WhatsApp with the visitor's name, phone number and goal already filled in, so you can reply from your own number without any extra software."),
       ("How do I make my gym appear on Google Maps?", "Set up a Google Business Profile with the same name, address and phone number as your website, then add the map and opening hours on the site. Rankings depend on competition and reviews, so no one can guarantee a position.")],
  related=["yoga", "clinic", "beauty"])

I(demo="clinic", url="clinics", name="Clinics & Healthcare", short="Clinic", singular="clinic",
  kf="doctor profiles, services, appointment requests and clear opening hours",
  intro="Patients search for a clinic when they are worried, often late in the evening and on a phone. A clinic website should answer three questions quickly: who will see me, what do you treat and how do I get an appointment.",
  queries=["family doctor near me Thrissur", "paediatrician in Kochi", "clinic open on Sunday near me", "health check-up package Kozhikode", "lab test near me"],
  needs=[("Doctor profiles", "Name, qualification and the days each doctor sits, so patients know who to ask for."),
         ("Services in plain language", "Describe what you treat the way patients describe their problem, not only in medical terms."),
         ("Appointment request", "A short form that opens WhatsApp with name and department filled in, so reception can confirm a slot."),
         ("Timings and emergency note", "Opening hours for each doctor, plus a clear line on what to do in an emergency."),
         ("Location help", "A map, landmark and parking information, because many first-time patients are lost on arrival."),
         ("Registration and policies", "Show your clinic registration details and privacy note where applicable.")],
  mistakes=[("Medical jargon everywhere", "Patients search by symptom or need. Write service pages the way they would ask the question."),
            ("Guaranteed-cure claims", "Avoid promises of results or cures. Follow your medical council's advertising guidelines and keep the content informative."),
            ("No mobile booking path", "If booking needs a desktop form or a phone call, many patients will pick the next clinic. Offer WhatsApp.")],
  faq=[("How much does a clinic website cost in Kerala?", "A clinic website with doctor profiles, services, a map and an appointment form typically costs ₹12,000 with Qrenzy, and a simple one-page version starts at ₹5,000. The first-year domain and hosting are included."),
       ("Can patients request appointments through the website?", "Yes. The form opens WhatsApp with the patient's name, phone number and department filled in, and your reception confirms the time. It does not store medical details."),
       ("What should a clinic put on its website?", "Doctor names and qualifications, services, timings, location with a map, contact numbers and registration details where applicable. Avoid publishing patient testimonials or outcome claims unless your regulator allows it."),
       ("Does a clinic need structured data for Google?", "It helps. MedicalClinic and FAQ structured data let Google understand your name, address, hours and common questions. It must match what is visible on the page, and it does not by itself guarantee higher rankings.")],
  related=["dental", "gym", "pet-care"])

I(demo="dental", url="dental-clinics", name="Dental Clinics", short="Dental Clinic", singular="dental clinic",
  kf="treatment pages, cost guidance, appointment booking and a clear map",
  intro="People searching for a dentist usually have a specific problem such as a toothache, braces or a missing tooth, and they compare cost and comfort before booking. A good dental website answers those two worries and makes the first appointment easy.",
  queries=["dentist near me Thrissur", "root canal cost in Kochi", "braces treatment in Kerala", "dental implant cost Kozhikode", "emergency dentist open now"],
  needs=[("One page per treatment", "Root canal, braces, implants and whitening each deserve a page that explains the process and recovery."),
         ("Cost guidance", "Starting prices or ranges reduce fear and filter serious enquiries. Say what changes the final cost."),
         ("Comfort and sterilisation", "Patients worry about pain and hygiene. Explain anaesthesia, sterilisation and your approach in plain words."),
         ("Before and after, with consent", "Treatment photos shown with permission and clear captions build trust, within your council's guidelines."),
         ("Appointment and emergency path", "A booking button, plus a clear line for toothache or injury, opens WhatsApp on any phone."),
         ("Kids and family section", "Parents search separately for a child-friendly dentist. Give them their own section.")],
  mistakes=[("A single 'Services' list", "Google and patients both prefer a clear page for each treatment. Give each treatment its own section or page."),
            ("No cost information at all", "Patients assume the worst. A 'from' price with an honest note about what affects it performs better."),
            ("Exaggerated claims", "Avoid words like 'best' or 'painless guaranteed'. Describe your method and let reviews speak.")],
  faq=[("How much does a dental clinic website cost in Kerala?", "A dental website with treatment sections, an appointment form and a map typically costs ₹12,000 with Qrenzy, and the first-year domain and hosting are included. A one-page version starts at ₹5,000."),
       ("What pages does a dental clinic website need?", "At minimum: home, treatments (root canal, braces, implants, whitening, kids), about the dentists, contact with a map and an FAQ. Separate pages for key treatments help you appear for specific searches."),
       ("Can I show before and after photos?", "Yes, with patient consent and within the advertising rules of your dental council. We add the photos you provide and caption them clearly."),
       ("How do dentists get more patients from Google?", "A complete Google Business Profile, a fast mobile website with treatment pages and honest reviews work together. We build the website side. Results depend on your location and competition and cannot be guaranteed.")],
  related=["clinic", "pet-care", "beauty"])

I(demo="tuition", url="tuition-centres", name="Tuition Centres", short="Tuition Centre", singular="tuition centre",
  kf="class and batch details, fees, teacher profiles and demo-class booking",
  intro="Parents choose a tuition centre by results, teachers and trust, and they usually decide after a conversation. Your website should give them the facts upfront and make booking a demo class as easy as sending a message.",
  queries=["tuition centre near me Thrissur", "SSLC tuition in Kochi", "Plus Two commerce tuition Kozhikode", "NEET coaching in Kerala", "spoken English classes near me"],
  needs=[("Class and batch details", "Which classes, subjects and timings, and how many students per batch."),
         ("Fees stated clearly", "Monthly fees by class remove the most common hesitation."),
         ("Teacher profiles", "Parents want to know who teaches their child. Show qualification and experience."),
         ("Demo-class booking", "A button that opens WhatsApp with the student's class and subject pre-filled."),
         ("Progress and communication", "Explain weekly tests and how parents receive updates."),
         ("Results shown carefully", "Share results with permission, and be specific about the batch and year.")],
  mistakes=[("Listing every subject in one block", "Organise by class (5–7, SSLC, Plus One/Two) so each parent finds theirs immediately."),
            ("Unverifiable claims like '100% results'", "Use exact, verifiable numbers or leave them out. Honest details build more trust."),
            ("No phone-friendly contact", "Most parents browse on a phone. A WhatsApp button beats a long contact form.")],
  faq=[("How much does a tuition centre website cost in Kerala?", "A tuition centre website with classes, fees, teacher profiles and a demo-class form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("Can parents book a demo class from the website?", "Yes. The form opens WhatsApp with the student's name, class and subject already filled in, so you can confirm a slot from your own number."),
       ("What should a tuition website include?", "Classes and subjects, timings, fees, teacher profiles, results shared with permission, a location map and a short FAQ. A page per major class helps you appear for searches like SSLC tuition."),
       ("Will the website help me appear in 'near me' searches?", "It helps when combined with a Google Business Profile and correct name, address and phone details on both. No one can guarantee rankings, which depend on competition and reviews.")],
  related=["yoga", "accounting", "clinic"])

I(demo="restaurant", url="restaurants-and-cafes", name="Restaurants & Cafés", short="Restaurant", singular="restaurant",
  kf="menu highlights, table booking, WhatsApp ordering and clear timings",
  intro="Diners decide in seconds, usually on a phone and often while standing outside. Your restaurant website should show what you are known for, the prices and how to reserve or order, before they scroll twice.",
  queries=["restaurant near me Thrissur", "Kerala meals in Kochi", "best biriyani near me", "family restaurant with parking Kozhikode", "party hall restaurant booking"],
  needs=[("Menu that loads fast", "Use readable text, not a PDF image, so Google and phones can read it."),
         ("Signature dishes", "Lead with the three dishes people travel for, with real photos."),
         ("Order or reserve on WhatsApp", "One tap opens WhatsApp with the dish, date or guest count filled in."),
         ("Timings and holidays", "Opening hours, lunch and dinner times and any weekly off, kept current."),
         ("Location and parking", "Map, landmark and parking details reduce no-shows and complaints."),
         ("Licence information", "Show your FSSAI licence number where applicable.")],
  mistakes=[("A menu uploaded as an image or PDF", "Visitors cannot search it and Google cannot read it. Publish the menu as text."),
            ("Outdated timings", "Wrong hours cost bookings and reviews. Keep timings accurate on the site and on Google."),
            ("No way to order from the website", "If the only path is a call, many visitors leave. Add a WhatsApp order button.")],
  faq=[("How much does a restaurant website cost in Kerala?", "A restaurant website with a menu, photos, location and WhatsApp ordering typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. The first-year domain and hosting are included."),
       ("Can customers order or reserve on WhatsApp?", "Yes. The buttons open WhatsApp with the customer's name, dish or booking details filled in. You confirm from your own number without extra software."),
       ("Should a restaurant publish its full menu online?", "Yes, as readable text with prices. Search engines can read it, customers can compare and it supports searches for specific dishes."),
       ("How can a restaurant rank for dish searches like biriyani near me?", "Use the dish names on your menu and signature pages, keep your Google Business Profile complete and collect genuine reviews. We build the website side. Rankings cannot be guaranteed.")],
  related=["homestay", "travel", "auditorium"])

I(demo="beauty", url="beauty-parlours-and-salons", name="Beauty Parlours & Salons", short="Beauty Parlour", singular="beauty parlour",
  kf="service menu, bridal packages, appointment requests and a gallery of your work",
  intro="Clients pick a parlour by the look of the work and how easy it is to book. A beauty website should show your best results, list services with prices and let a client request a slot in a minute, especially before weddings and festivals.",
  queries=["beauty parlour near me Thrissur", "bridal makeup in Kochi", "hair spa near me", "facial price Kozhikode", "ladies salon open on Sunday"],
  needs=[("Service menu with prices", "Haircuts, facials and packages with starting prices avoid repeated phone calls."),
         ("Bridal section", "Brides search separately and plan early. Give them their own page, packages and trial information."),
         ("Gallery of real work", "Your own photographs of finished looks, shown with client permission."),
         ("Appointment request", "A WhatsApp button with service and preferred date prefilled."),
         ("Hygiene and products", "State the brands and your hygiene practices. Clients care about both."),
         ("Location and timings", "Map, landmark and opening hours, kept accurate for festival seasons.")],
  mistakes=[("Posting only on Instagram", "Social posts disappear. A website gives permanent pages that Google can show for local searches."),
            ("No pricing at all", "Clients move on if they cannot guess the cost. Show starting prices."),
            ("Low-quality gallery photos", "Use well-lit photos with permission. A few strong images beat dozens of weak ones.")],
  faq=[("How much does a beauty parlour website cost in Kerala?", "A beauty parlour website with services, packages, a gallery and WhatsApp booking typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("Can clients book appointments through the site?", "Yes. The form opens WhatsApp with the client's name, service and preferred date filled in, and you confirm the slot yourself."),
       ("What should a bridal makeup page include?", "Packages and prices, what a trial includes, sample looks with permission, advance booking steps and travel details. Brides compare many artists, so clarity matters."),
       ("Is Instagram enough for a salon?", "Instagram is useful for showing your work, but it does not rank for local searches the way a website and Google Business Profile can. The best results come from using all three together.")],
  related=["wedding", "photography", "fashion"])

I(demo="homestay", url="homestays-and-resorts", name="Homestays & Resorts", short="Homestay", singular="homestay",
  kf="rooms, photos, direct booking enquiries and local experiences",
  intro="Travellers compare many stays and book through platforms that charge commission. Your own website lets you show rooms honestly, offer a direct-booking benefit and answer the questions that decide a booking: location, food, access and price.",
  queries=["homestay in Munnar", "family stay in Wayanad", "budget resort near Kochi", "homestay with home-cooked food Kerala", "houseboat stay Alleppey"],
  needs=[("Room pages with real photos", "Each room type with photos, size, bed type, amenities and price per night."),
         ("Direct-booking offer", "A clear benefit for booking direct, such as a discount or a welcome drink."),
         ("Location and access", "Distance from the nearest town or station and honest road conditions."),
         ("Food and experiences", "Home-cooked meals, plantation walks and local trips are often the deciding factor."),
         ("Availability enquiry", "A form that opens WhatsApp with dates, guests and room type prefilled."),
         ("Reviews and house rules", "Genuine guest feedback and simple rules reduce surprises.")],
  mistakes=[("Relying only on booking platforms", "You pay commission and compete with every listing. A direct website captures bookings at full value."),
            ("Hiding the location details", "Travellers worry about reaching you. Explain access, parking and nearest facilities."),
            ("Few or dark photos", "Photograph rooms in daylight and show the views. Photos decide most bookings.")],
  faq=[("How much does a homestay website cost in Kerala?", "A homestay website with room pages, photos, a map and a WhatsApp enquiry form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("Can guests book directly through the website?", "Guests send an enquiry with dates and room type to your WhatsApp, and you confirm availability and advance payment yourself. We do not process payments on the site."),
       ("How can a homestay appear for searches like homestay in Munnar?", "Use the place name naturally on your pages, publish real photos and a complete Google Business Profile, and collect genuine reviews. We build the website. Rankings cannot be guaranteed."),
       ("Do I still need booking platforms?", "Many hosts use both. A direct website lets you offer the best rate to repeat guests and those who find you on Google, while platforms bring extra visibility.")],
  related=["restaurant", "travel", "landscaping"])

I(demo="crane", url="crane-services", name="Crane & Heavy Equipment Services", short="Crane Service", singular="crane service",
  kf="fleet capacities, rate guidance, safety credentials and quick quote requests",
  intro="Contractors and factories need a crane quickly and judge a supplier by capacity, safety and how fast they respond. A crane service website should list the fleet, show proof of safety and make requesting a quote a two-minute task.",
  queries=["crane on rent Thrissur", "50 ton crane hire Kochi", "mobile crane service near me", "hydra crane hire Kozhikode", "crane for steel erection Kerala"],
  needs=[("Fleet and capacities", "Each crane type with tonnage, reach and typical use, so buyers can match it to their lift."),
         ("Rate guidance", "Starting hourly or daily rates, with a note on what changes the final price."),
         ("Safety and credentials", "Operator certification, insurance and inspection information, shown without exaggeration."),
         ("Quote request with lift details", "A form that asks weight, height, radius and location and opens WhatsApp."),
         ("Service area", "The districts you cover and response time for emergencies."),
         ("Past jobs", "Short descriptions of lifts you have completed, with permission.")],
  mistakes=[("Only a phone number", "Buyers compare several suppliers. A quote form that captures the lift details gets answered faster."),
            ("No tonnage information", "Visitors cannot tell if you can handle their job. List capacities clearly."),
            ("Unverified safety claims", "Only state certifications and insurance you actually hold, and keep documents ready.")],
  faq=[("How much does a crane service website cost in Kerala?", "A crane service website with fleet pages, rate guidance and a quote form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("What should a crane hire website show?", "Crane types and capacities, service area, rate guidance, safety and insurance details, contact numbers for emergencies and a quote form that collects weight, height, radius and location."),
       ("Can enquiries come to WhatsApp?", "Yes. The quote form opens WhatsApp with the lift details filled in, so your team can reply with a price quickly from a company number."),
       ("Do crane companies really get leads from Google?", "Many buyers search for crane hire in their area, so a clear website and Google Business Profile can help you appear. Results depend on your location, competition and reviews and cannot be guaranteed.")],
  related=["manufacturing", "solar", "real-estate"])

I(demo="real-estate", url="real-estate-agents", name="Real Estate Agents", short="Real Estate", singular="real estate agency",
  kf="verified property listings, area guides, site-visit booking and loan support",
  intro="Property buyers search by area and budget and trust agents who show real listings with clear details. A real estate website should present each property with photos, price and location, and make booking a site visit simple.",
  queries=["2 BHK flat for sale Thrissur", "villas in Kochi", "residential plots near Aluva", "flat for rent near me", "property dealers Kozhikode"],
  needs=[("Listings with full details", "Price, area, bedrooms, location and clear photos for every property."),
         ("Search by area and budget", "Visitors should be able to find flats, villas or plots in their range quickly."),
         ("Area guides", "Short pages on neighbourhoods build trust and capture local searches."),
         ("Site-visit booking", "A WhatsApp button with the property and preferred date prefilled."),
         ("Legal and loan help", "Explain document checks and loan support so buyers feel safe."),
         ("Registration details", "Show your RERA registration number where applicable.")],
  mistakes=[("Listings without prices", "Buyers filter by budget. Hidden prices lose serious enquiries."),
            ("Copied photos and descriptions", "Duplicate content hurts search visibility and trust. Use your own photos and wording."),
            ("Old listings left online", "Sold properties frustrate visitors. Mark or remove them promptly.")],
  faq=[("How much does a real estate website cost in Kerala?", "A real estate website with listings, area pages and enquiry forms typically costs ₹12,000 to ₹25,000 with Qrenzy depending on the number of listings, and a simple one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("Can I list properties on the website myself?", "Our standard website lists a set of properties that we update for you under the care plan. If you need frequent self-service updates, tell us and we will quote a suitable option."),
       ("How can an agent rank for searches like flats for sale in Thrissur?", "Create pages for areas and property types, use real photos and details, keep your Google Business Profile complete and gather reviews. Rankings cannot be guaranteed."),
       ("Do I need to show a RERA number?", "In many cases yes. Registered agents and promoters are expected to quote their RERA registration where applicable, so check the current requirements for your business and add the number to the site.")],
  related=["interior", "landscaping", "finance-insurance"])

I(demo="landscaping", url="landscaping-companies", name="Landscaping Companies", short="Landscaping", singular="landscaping company",
  kf="a project gallery, service pages, package prices and free site-visit booking",
  intro="Garden customers buy with their eyes. A landscaping website should show finished gardens first, explain what you design and build, and make a free site visit easy to book.",
  queries=["landscaping in Thrissur", "terrace garden design Kochi", "garden maintenance near me", "lawn installation Kerala", "villa landscape designers"],
  needs=[("Project gallery", "Finished gardens with before and after photos and short notes on size and style."),
         ("Services explained", "Design, lawns, terrace gardens, water features and maintenance, each with a short page."),
         ("Package prices", "Starting prices by garden size help buyers decide to call."),
         ("Site-visit booking", "A WhatsApp button that asks location and space type."),
         ("Plant suitability", "Short notes on plants that suit Kerala's climate show real expertise."),
         ("Maintenance plans", "Monthly care builds recurring revenue. Explain what is included.")],
  mistakes=[("Stock garden photos", "Customers can tell. Use your own projects, even small ones."),
            ("No price signal", "Without a starting price people assume it is too costly. Show package ranges."),
            ("No maintenance offer", "Many customers need ongoing care. Add a simple plan page.")],
  faq=[("How much does a landscaping website cost in Kerala?", "A landscaping website with a project gallery, services and a site-visit form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("What should a landscaping website show first?", "Show your best finished projects in the first screen, followed by services, packages and a clear button to book a free site visit."),
       ("Can I add more projects later?", "Yes. Send us new photos and notes and we add them, or use the care plan for regular updates."),
       ("Does a landscaping company need a blog?", "Helpful guides such as plants for terrace gardens in Kerala can attract searches, but they are optional. A strong gallery and local service pages matter more at the start.")],
  related=["interior", "real-estate", "cleaning"])
