"""Industry landing page content (2 of 3)."""
from ind1 import INDS, I

I(demo="cleaning", url="cleaning-services", name="Cleaning Services", short="Cleaning Company", singular="cleaning company",
  kf="service packages, fixed prices, instant booking and a satisfaction promise",
  intro="Customers hire cleaners when they are busy or about to host, and they worry about trust and price. A cleaning company website should show fixed prices, who will come to the home and how to book a slot in a minute.",
  queries=["home cleaning service Thrissur", "deep cleaning price in Kochi", "office cleaning company Kozhikode", "sofa cleaning near me", "move in cleaning Kerala"],
  needs=[("Fixed prices by home size", "1 BHK, 2 BHK and 3 BHK prices remove the main hesitation."),
         ("What each service includes", "A checklist for deep cleaning, kitchen, bathroom and sofa cleaning avoids disputes."),
         ("Staff trust signals", "ID verification, training and uniforms ease worries about strangers entering the home."),
         ("Instant booking", "A WhatsApp button that captures area, home size and preferred date."),
         ("Before and after photos", "Real results with customer permission."),
         ("Re-clean promise", "A clear, honest satisfaction policy builds confidence.")],
  mistakes=[("Quoting only after a call", "Most visitors want a price range first. Publish starting prices."),
            ("Vague service descriptions", "'Deep cleaning' means different things. List exactly what you clean."),
            ("No commercial section", "Offices and shops search differently. Give them their own page and plans.")],
  faq=[("How much does a cleaning company website cost in Kerala?", "A cleaning company website with service pages, prices and a booking form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("Can customers book a cleaning slot on WhatsApp?", "Yes. The form opens WhatsApp with the customer's area, home size and preferred date filled in, so you can confirm quickly."),
       ("What should a home cleaning page include?", "Prices by home size, a checklist of what is cleaned, how long it takes, how booking works and your re-clean policy."),
       ("Do cleaning companies benefit from local pages?", "Yes. Pages for the areas you serve can match local searches, provided each has useful details and is not a copy of the others.")],
  related=["pest-control", "landscaping", "interior"])

I(demo="auditorium", url="auditoriums-and-event-venues", name="Auditoriums & Event Venues", short="Auditorium", singular="auditorium",
  kf="capacity and layouts, rent guidance, availability enquiries and facility details",
  intro="Event organisers shortlist venues by capacity, date availability and what is included. An auditorium website should state seating clearly, show the hall honestly and make checking a date a one-tap enquiry.",
  queries=["auditorium for wedding Thrissur", "convention hall in Kochi", "AC hall for rent near me", "conference hall booking Kozhikode", "auditorium with parking Kerala"],
  needs=[("Capacity and layouts", "Seating for theatre, banquet and standing formats, with hall dimensions."),
         ("Photos and a virtual walk-through", "Real images of the hall, stage, dining area and parking."),
         ("Rent guidance", "Starting rates by event type and duration, with what is included."),
         ("Date check enquiry", "A form that captures event type, date and guests and opens WhatsApp."),
         ("Facilities list", "AC, sound, lights, green rooms, generator and parking in a simple list."),
         ("Catering and decoration policy", "Clarify in-house and outside options to avoid last-minute disputes.")],
  mistakes=[("No capacity numbers", "Planners cannot shortlist without them. State seated and standing capacity."),
            ("Only a phone number for bookings", "People enquire in the evening. A form that captures dates works around the clock."),
            ("Hiding parking details", "Parking is often the deciding factor. Give numbers and access information.")],
  faq=[("How much does an auditorium website cost in Kerala?", "An auditorium website with hall details, a gallery and a date-enquiry form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("Can organisers check dates on the website?", "They can send a date enquiry that opens WhatsApp with event type, date and guest count. We do not show a live calendar unless you ask for a custom option."),
       ("What should an event venue page include?", "Capacity, layouts, photos, facilities, parking, catering policy, indicative rent and a clear way to enquire."),
       ("Does a venue need a Google Business Profile as well?", "Yes. Many organisers search on Google Maps first, so a complete profile with photos and reviews complements the website.")],
  related=["wedding", "photography", "restaurant"])

I(demo="interior", url="interior-designers", name="Interior Designers", short="Interior Designer", singular="interior design company",
  kf="project portfolio, package guidance, a design process explained and consultation booking",
  intro="Homeowners choose an interior designer by portfolio, process and trust, and a bad experience is a big risk for them. Your website should show finished homes, explain how a project runs and reduce uncertainty about cost and timelines.",
  queries=["interior designers in Thrissur", "modular kitchen cost Kochi", "full home interior price Kerala", "2 BHK interior design Kozhikode", "wardrobe design near me"],
  needs=[("Portfolio by project type", "Kitchens, bedrooms, living rooms and full homes, with size and location."),
         ("Cost guidance", "Per-square-foot ranges and what affects them, so visitors can plan a budget."),
         ("A clear process", "Consultation, design, quote, manufacturing, installation. Explain each stage."),
         ("Consultation booking", "A WhatsApp button with property type, size and city prefilled."),
         ("Materials and warranty", "State the boards, hardware and warranty you actually offer."),
         ("Client stories", "Short, genuine notes about timelines and communication, shown with permission.")],
  mistakes=[("A portfolio of unnamed photos", "Add size, city and what was delivered so visitors trust the work."),
            ("Hiding timelines", "Delays are the top worry. Share realistic ranges for typical projects."),
            ("Heavy images that load slowly", "Compress photos so the site is fast on mobile data.")],
  faq=[("How much does an interior designer website cost in Kerala?", "An interior designer website with a portfolio, process, packages and a consultation form typically costs ₹12,000 to ₹25,000 with Qrenzy depending on portfolio size, and a one-page version starts at ₹5,000."),
       ("How many photos should a portfolio have?", "Quality matters more than volume. Start with 15 to 30 well-lit images across project types, and add more over time."),
       ("Can clients request a consultation online?", "Yes. The form opens WhatsApp with property type, size and city filled in so you can respond with a time."),
       ("Should I show prices on my site?", "Showing starting ranges per square foot, with a note about what changes them, generally attracts better-qualified enquiries than hiding prices completely.")],
  related=["landscaping", "real-estate", "photography"])

I(demo="photography", url="photographers", name="Photographers & Studios", short="Photographer", singular="photography studio",
  kf="a strong portfolio, package prices, date checks and fast delivery information",
  intro="Photographers are chosen on the quality of their work and how easy they are to book for a specific date. A photography website should let the portfolio carry the first impression, then answer price, availability and delivery questions.",
  queries=["wedding photographers in Thrissur", "pre wedding shoot Kochi", "baby photoshoot near me", "event photographer Kozhikode", "product photography Kerala"],
  needs=[("Portfolio first", "Large, fast-loading galleries by category: weddings, pre-wedding, babies, products."),
         ("Packages and prices", "Starting prices for photo, video and album packages."),
         ("Date availability enquiry", "A form that captures date, location and event type on WhatsApp."),
         ("Delivery timelines", "How long previews, galleries and albums take, stated plainly."),
         ("About the team", "People hire people. Show who will shoot their day."),
         ("Short films and reels", "Link or embed highlights to show your style in motion.")],
  mistakes=[("Only a social media profile", "Clients want a permanent portfolio and prices. A website adds both."),
            ("Giant uncompressed images", "Slow galleries lose visitors. Optimise images for the web."),
            ("No pricing signal", "Even a 'starting from' amount filters out mismatched enquiries.")],
  faq=[("How much does a photographer website cost in Kerala?", "A photography website with galleries, packages and a date-enquiry form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("How many photos should my portfolio have?", "Start with your best 20 to 40 images across categories. A smaller, stronger portfolio converts better than a large mixed one."),
       ("Can clients check my availability?", "They can send a date enquiry that opens WhatsApp with the event, date and place filled in, and you confirm. We do not show a live calendar by default."),
       ("Can the website show my photo and video work?", "Yes. We can embed galleries and link or embed videos from YouTube or Instagram. Large galleries should be optimised so pages stay fast.")],
  related=["wedding", "beauty", "auditorium"])

I(demo="wedding", url="wedding-planners", name="Wedding Planners", short="Wedding Planner", singular="wedding planning company",
  kf="package tiers, a portfolio of events, a planning process and consultation booking",
  intro="Couples and families entrust a wedding planner with the biggest event of their lives, so trust and clarity matter more than anything. Your website should show real events, explain how planning works and make a first conversation easy.",
  queries=["wedding planners in Thrissur", "destination wedding planner Kerala", "wedding decoration Kochi", "event management company Kozhikode", "engagement planning near me"],
  needs=[("Event portfolio", "Photos and short stories of weddings you planned, with size and style."),
         ("Planning packages", "Day-of coordination, full planning and destination options, with starting budgets."),
         ("A transparent process", "From first call to wedding day, show each step and who handles it."),
         ("Vendor network", "Decorators, caterers, photographers and artists you work with."),
         ("Consultation booking", "A form that captures date, guest count and city on WhatsApp."),
         ("Testimonials with permission", "Short notes from couples describing the experience.")],
  mistakes=[("Showing only decoration photos", "Couples also want to know how you manage timelines and budgets. Explain the process."),
            ("No budget indication", "Without a range, serious and casual enquiries look the same. Give starting packages."),
            ("Slow replies", "Wedding dates book fast. Use WhatsApp so enquiries reach you instantly.")],
  faq=[("How much does a wedding planner website cost in Kerala?", "A wedding planner website with a portfolio, packages and a consultation form typically costs ₹12,000 to ₹25,000 with Qrenzy, and a one-page version starts at ₹5,000."),
       ("What should a wedding planner's website include?", "A portfolio of real events, packages with starting budgets, the planning process, vendor partners, testimonials and a consultation form."),
       ("Can couples book a planning call from the site?", "Yes. The form opens WhatsApp with the wedding date, guest count and city filled in so you can propose a time."),
       ("Do I need separate pages for destination weddings?", "If you offer them, yes. A dedicated page lets you explain locations, logistics and pricing, and matches specific searches.")],
  related=["photography", "auditorium", "beauty"])

I(demo="car-care", url="car-detailing-and-garages", name="Car Detailing Studios & Garages", short="Car Detailing", singular="car detailing studio",
  kf="service packages, before and after results, booking and pickup information",
  intro="Car owners trust a detailer with an expensive asset and look for proof of quality, honest advice and convenience. A car care website should show results, explain each service in plain language and make booking and pickup easy.",
  queries=["ceramic coating in Thrissur", "car detailing near me Kochi", "PPF installation Kerala", "car interior cleaning Kozhikode", "car polishing near me"],
  needs=[("Service explanations", "What ceramic coating, PPF and polishing actually do, and who needs them."),
         ("Before and after results", "Real photos on real cars, labelled with the service and car model."),
         ("Packages with prices", "Starting prices by car size reduce hesitation."),
         ("Booking and pickup", "A WhatsApp button with car model, service and preferred slot."),
         ("Products and warranty", "Name the brands you use and what the warranty covers."),
         ("Location and timings", "Studio address, map and working hours.")],
  mistakes=[("Technical jargon without explanation", "Explain benefits simply. Most owners do not know the difference between coating and wax."),
            ("Unlabelled gallery photos", "Say which car, which service and how long it took."),
            ("Overpromising warranty", "State exactly what the warranty covers and the maintenance it requires.")],
  faq=[("How much does a car detailing website cost in Kerala?", "A car detailing website with service pages, a gallery and a booking form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("What should a ceramic coating page say?", "Explain what it is, how long it lasts, how it is applied, the warranty terms, maintenance needs and starting prices by car size."),
       ("Can customers book and request pickup from the website?", "Yes. The form opens WhatsApp with the car model, service and preferred time filled in so you can confirm."),
       ("How do detailers get found on Google?", "A complete Google Business Profile with photos, reviews and a fast website with pages for each major service work together. Rankings depend on competition and cannot be guaranteed.")],
  related=["manufacturing", "crane", "cleaning"])

I(demo="pest-control", url="pest-control-companies", name="Pest Control Companies", short="Pest Control", singular="pest control company",
  kf="treatment pages, safety information, warranty details and quick inspection requests",
  intro="Customers search for pest control when they already have a problem, often urgently. A pest control website should reassure them about safety, explain the treatment and offer a fast way to book an inspection.",
  queries=["termite treatment Thrissur", "pest control near me Kochi", "cockroach control price Kozhikode", "bed bug treatment Kerala", "rodent control for restaurant"],
  needs=[("A page per pest", "Termites, cockroaches, bed bugs, mosquitoes and rodents each deserve a page that explains signs, treatment and prevention."),
         ("Safety information", "Explain chemicals, child and pet safety and the precautions after treatment."),
         ("Warranty terms", "State exactly what a termite or general warranty covers and for how long."),
         ("Quick inspection request", "A WhatsApp form that captures the pest, property type and area."),
         ("Licence and credentials", "Mention your pest control licence and trained technicians where applicable."),
         ("Commercial plans", "Restaurants, hotels and warehouses need contracts. Give them their own section.")],
  mistakes=[("Treating all pests as one service", "People search for a specific pest. Create a separate page for each."),
            ("No safety explanation", "Customers worry about children and pets. Address it directly."),
            ("Vague warranty claims", "Say what is covered and what is not to avoid disputes.")],
  faq=[("How much does a pest control website cost in Kerala?", "A pest control website with treatment pages, warranty details and an inspection form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("What pages should a pest control website have?", "A page for each major pest, a safety page, warranty terms, service areas, commercial plans and a contact form. Separate pest pages help you appear for specific searches."),
       ("Can customers request an inspection online?", "Yes. The form opens WhatsApp with the pest, property type and area filled in, and you respond with a time."),
       ("Should I mention my licence on the website?", "Yes, where applicable. Showing your licence and training builds trust, and customers increasingly ask for it.")],
  related=["cleaning", "landscaping", "real-estate"])

I(demo="yoga", url="yoga-studios", name="Yoga Studios & Wellness Centres", short="Yoga Studio", singular="yoga studio",
  kf="class schedules, memberships, teacher profiles and free first-class booking",
  intro="People looking for yoga want a calm space, a teacher they trust and times that fit their day. A yoga studio website should communicate that atmosphere, show the schedule clearly and make the first class easy to book.",
  queries=["yoga classes near me Thrissur", "prenatal yoga in Kochi", "meditation classes Kozhikode", "morning yoga batch Kerala", "yoga for back pain near me"],
  needs=[("Class schedule", "A readable weekly timetable by style and level."),
         ("Teacher profiles", "Qualifications and teaching style, with a friendly photo."),
         ("Membership options", "Drop-in, monthly and quarterly prices with what is included."),
         ("First-class booking", "A WhatsApp button for a free or trial class."),
         ("Class descriptions", "Explain hatha, vinyasa, prenatal and therapy classes for beginners."),
         ("Studio atmosphere", "Photos of the space communicate calm better than words.")],
  mistakes=[("Using jargon", "Beginners do not know the styles. Describe who each class is for."),
            ("Hidden timetable", "If visitors must ask for timings, many will not. Publish it."),
            ("Health claims", "Avoid medical promises. Describe benefits carefully and encourage consulting a doctor for conditions.")],
  faq=[("How much does a yoga studio website cost in Kerala?", "A yoga studio website with a schedule, memberships and a first-class form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("What should a yoga studio website include?", "Class types with descriptions, a timetable, teacher profiles, membership prices, studio photos, location and a clear first-class button."),
       ("Can students book classes through the site?", "They can send a booking request that opens WhatsApp with their name, class and preferred time filled in. We do not take payments on the site."),
       ("How can a yoga studio rank for near me searches?", "Complete your Google Business Profile, keep your name, address and phone consistent on your site, publish class pages and earn genuine reviews. Rankings cannot be guaranteed.")],
  related=["gym", "clinic", "beauty"])

I(demo="accounting", url="chartered-accountants", name="Chartered Accountants & Tax Consultants", short="Chartered Accountant", singular="CA firm",
  kf="service pages, fee guidance, a documents checklist and consultation requests",
  intro="Business owners look for an accountant they can trust with money and compliance. A CA firm website should explain services in plain language, set expectations on documents and fees and let a prospect request a consultation.",
  queries=["chartered accountant in Thrissur", "GST registration Kochi", "income tax filing near me", "company registration Kozhikode", "bookkeeping services Kerala"],
  needs=[("A page per service", "GST, income tax, company registration, audit and bookkeeping each explained simply."),
         ("Documents checklist", "What a client must bring for each service saves time on both sides."),
         ("Fee guidance", "Starting fees for common services help clients self-qualify."),
         ("Consultation request", "A form that captures the service needed and business type on WhatsApp."),
         ("About the firm", "Qualifications, experience and the people clients will work with."),
         ("Professional guidelines", "Present information within the guidelines your professional body sets for member websites.")],
  mistakes=[("Heavy compliance jargon", "Write for business owners, not other accountants."),
            ("No fee signal", "Even a range reduces back-and-forth. Explain what changes the fee."),
            ("Outdated deadlines", "Wrong due dates harm credibility. Keep content current or avoid dates.")],
  faq=[("How much does a CA firm website cost in Kerala?", "A CA firm website with service pages, a documents checklist and a consultation form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("What should an accountant's website include?", "Service pages, fee guidance, documents checklists, about the firm, contact and FAQs. Keep the tone professional and within your institute's guidelines."),
       ("Can accountants publish tax guidance?", "Helpful explainers on common topics attract searches, but they must be accurate and dated. Anything time-sensitive should be reviewed regularly."),
       ("Are there rules on how CAs advertise?", "Yes. Professional bodies set rules on how members may present themselves online. Check the current guidelines before publishing and we will follow them in the content you approve.")],
  related=["legal", "finance-insurance", "corporate-b2b"])

I(demo="pet-care", url="pet-care-and-grooming", name="Pet Care & Grooming", short="Pet Care", singular="pet care business",
  kf="grooming packages, boarding information, vet services and easy booking",
  intro="Pet owners treat their animals as family and choose a service they trust with them. A pet care website should show gentle handling, clean spaces and clear prices, and make booking grooming or boarding simple.",
  queries=["dog grooming near me Thrissur", "pet boarding in Kochi", "cat grooming Kozhikode", "vet near me Kerala", "home pet grooming service"],
  needs=[("Service and price list", "Grooming packages by breed size, boarding rates and vet services."),
         ("Photos of the space", "Clean, calm rooms and play areas reassure owners."),
         ("Staff and handling approach", "Explain how you handle nervous pets and what training your team has."),
         ("Booking and home service", "A WhatsApp button with pet type, breed and service prefilled."),
         ("Vaccination requirements", "State what you need before boarding or grooming."),
         ("Reviews and updates", "Genuine feedback and examples of daily updates for boarders.")],
  mistakes=[("Not stating requirements", "Owners hate surprises. List vaccination and temperament rules upfront."),
            ("One price for all pets", "Size and coat change the work. Show price ranges by size."),
            ("No emergency information", "Say how you handle health problems and which vet you work with.")],
  faq=[("How much does a pet care website cost in Kerala?", "A pet care website with services, prices and a booking form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("What should a pet grooming website include?", "Services and prices by size, photos of the studio, how you handle nervous pets, requirements, location, timings and a booking button."),
       ("Can customers book home grooming online?", "They can send a booking request that opens WhatsApp with pet type, area and preferred time filled in so you can confirm."),
       ("Do pet businesses need a Google Business Profile?", "Yes. Owners search 'near me' on Google Maps, so a complete profile with photos and reviews works well alongside your website.")],
  related=["clinic", "dental", "cleaning"])
