"""Industry landing page content (3 of 3)."""
from ind1 import INDS, I

I(demo="solar", url="solar-installers", name="Solar Installers", short="Solar Installer", singular="solar installation company",
  kf="system sizes, savings guidance, subsidy information and free survey booking",
  intro="Homeowners and businesses research solar carefully because it is a large, long-term purchase. A solar installer website should explain system sizes and savings honestly, address subsidy and net metering questions and make a free site survey easy to book.",
  queries=["solar panel installation Thrissur", "3 kW solar price Kochi", "rooftop solar subsidy Kerala", "solar for home near me", "net metering solar Kozhikode"],
  needs=[("System size guide", "Explain how bill size relates to 2 kW, 3 kW and 5 kW systems."),
         ("Savings estimates, honestly", "Show how savings are calculated, with a note that results depend on usage and sunlight."),
         ("Subsidy and net-metering help", "Explain what you handle for the customer, and refer to current official rules."),
         ("Site-survey booking", "A form that captures the electricity bill and roof type on WhatsApp."),
         ("Equipment and warranty", "Name panel and inverter brands and the warranty terms."),
         ("Installed projects", "Photos and sizes of homes and businesses you have completed.")],
  mistakes=[("Unrealistic savings claims", "Avoid 'zero bill' promises. Explain how usage and generation affect results."),
            ("Outdated subsidy information", "Schemes change. Link to official sources and say you will confirm current eligibility."),
            ("No price range", "Starting prices by system size help buyers take the first step.")],
  faq=[("How much does a solar installer website cost in Kerala?", "A solar installer website with system guides, projects and a survey form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("What should a solar company's website include?", "System sizes and indicative prices, how savings work, subsidy and net-metering help, equipment brands, warranty, completed projects and a survey request form."),
       ("Can customers send their electricity bill for a quote?", "Yes. The form opens WhatsApp where they can attach the bill, and you reply with a recommended system size and estimate."),
       ("Is it safe to promise savings on a website?", "Be careful. State typical ranges with the assumptions behind them and avoid guarantees, because results depend on usage, roof and weather.")],
  related=["crane", "manufacturing", "real-estate"])

I(demo="jewellery", url="jewellery-shops", name="Jewellery Shops", short="Jewellery Shop", singular="jewellery shop",
  kf="collections, gold-rate transparency, bridal enquiries and savings-scheme details",
  intro="Jewellery buyers care about trust, purity and price transparency before they care about design. A jewellery shop website should show collections beautifully, explain purity and making charges clearly and invite shoppers to visit.",
  queries=["jewellery shop in Thrissur", "bridal gold set Kochi", "diamond jewellery near me", "gold savings scheme Kozhikode", "lightweight gold earrings Kerala"],
  needs=[("Collections that look premium", "High-quality photos grouped by occasion: bridal, daily wear, kids, diamond."),
         ("Purity and hallmark information", "Explain BIS hallmarking and what customers receive on the bill."),
         ("Making-charge transparency", "Say how making charges are shown, to build trust before the visit."),
         ("Savings scheme details", "Plan structure, duration and redemption terms, stated plainly."),
         ("Showroom visit booking", "A form that captures occasion and preferred date on WhatsApp."),
         ("Exchange and buyback policy", "State the process for old gold clearly.")],
  mistakes=[("Showing prices that change daily", "Gold rates move. Link to a rate note or say prices are confirmed at the showroom."),
            ("Poor product photography", "Dull images hurt a premium category. Use well-lit, consistent photos."),
            ("No policy details", "Exchange, buyback and savings terms must be easy to find.")],
  faq=[("How much does a jewellery shop website cost in Kerala?", "A jewellery shop website with collections, scheme details and a showroom enquiry form typically costs ₹12,000 to ₹25,000 with Qrenzy depending on the number of collections, and a one-page version starts at ₹5,000."),
       ("Should a jewellery site show product prices?", "Because gold prices change daily, many shops show weights and designs and confirm the price at the showroom. Others publish indicative ranges with a clear note."),
       ("Can customers enquire about a design on WhatsApp?", "Yes. Each collection can have a button that opens WhatsApp with the design name filled in, so your team can share details and photos."),
       ("What should be on a jewellery shop's legal and trust pages?", "Hallmarking information, exchange and buyback policy, savings scheme terms and showroom details. Keep these accurate and updated.")],
  related=["fashion", "wedding", "ecommerce"])

I(demo="travel", url="travel-agencies", name="Travel Agencies & Tour Operators", short="Travel Agency", singular="travel agency",
  kf="tour packages, itineraries, visa support and quick trip enquiries",
  intro="Travellers compare many agents and choose the one that feels reliable and explains the trip clearly. A travel agency website should present itineraries with prices and inclusions, and let people ask about their dates quickly.",
  queries=["tour packages from Thrissur", "Kerala honeymoon package", "Dubai tour package from Kochi", "Munnar tour packages", "visa assistance near me"],
  needs=[("Package pages with itineraries", "Day-wise plans, inclusions, exclusions and starting prices."),
         ("Destination categories", "Kerala, India, Gulf and international, easy to browse."),
         ("Visa and documents help", "Explain what you handle and what the traveller must provide."),
         ("Trip enquiry form", "Dates, group size and budget sent to WhatsApp."),
         ("Trust signals", "Registration details, years in business and real traveller feedback."),
         ("Seasonal offers", "A simple page for current deals, updated regularly.")],
  mistakes=[("'Price on request' everywhere", "Show 'from' prices with clear inclusions to attract serious enquiries."),
            ("Copying itineraries from other sites", "Duplicate content ranks poorly. Write your own plans with local detail."),
            ("No cancellation terms", "State changes and cancellation rules clearly to prevent disputes.")],
  faq=[("How much does a travel agency website cost in Kerala?", "A travel agency website with package pages, itineraries and an enquiry form typically costs ₹12,000 to ₹25,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("What should a tour operator's website include?", "Packages with itineraries and prices, destination categories, visa help, traveller feedback, contact details and a trip enquiry form."),
       ("Can travellers request a quote on WhatsApp?", "Yes. The form opens WhatsApp with dates, group size and destination filled in, so you can send an itinerary and price."),
       ("Do I need a separate page for each package?", "Yes, for your main packages. Separate pages help you appear for specific searches such as Munnar tour packages.")],
  related=["homestay", "restaurant", "finance-insurance"])

I(demo="manufacturing", url="manufacturers", name="Manufacturers & Industrial Suppliers", short="Manufacturer", singular="manufacturing company",
  kf="capabilities, product specifications, quality credentials and quote requests",
  intro="Industrial buyers look for capability, quality and reliability before price, and they often send enquiries with drawings. A manufacturer's website should list capabilities and tolerances, show proof of quality and make a quote request detailed but simple.",
  queries=["CNC machining in Angamaly", "metal fabrication Thrissur", "sheet metal works near me", "OEM parts manufacturer Kerala", "industrial supplier Kochi"],
  needs=[("Capabilities and equipment", "Machines, materials and tolerances, stated precisely."),
         ("Product or process pages", "A page for each capability with typical applications."),
         ("Quality credentials", "Certifications you actually hold, with certificate details available on request."),
         ("Quote request with specifications", "A form that asks material, quantity and drawing availability."),
         ("Industries served", "Automotive, food, electrical, marine and others you supply."),
         ("Contact for procurement", "Direct numbers and an email for purchase teams.")],
  mistakes=[("Claiming certifications you do not hold", "Only state ISO or other approvals you have, and keep certificates ready."),
            ("A catalogue image instead of text", "Buyers and Google cannot search images. Publish specifications as text."),
            ("A generic contact form", "Ask for the details you need to quote: material, size, quantity and drawing.")],
  faq=[("How much does a manufacturer's website cost in Kerala?", "A manufacturer website with capability pages, industries served and a quote form typically costs ₹12,000 to ₹25,000 with Qrenzy depending on the number of product pages, and a one-page version starts at ₹5,000."),
       ("What should an industrial company website include?", "Capabilities, equipment, materials, tolerances, quality credentials, industries served, sample work and a detailed quote request form."),
       ("Can buyers send drawings through the site?", "The form opens WhatsApp or email where buyers can attach drawings. We can also provide an email address for larger files."),
       ("Do B2B buyers really search on Google?", "Many procurement teams search for suppliers by process and location, so clear capability pages can help you appear. Results depend on competition and cannot be guaranteed.")],
  related=["crane", "corporate-b2b", "it-software"])

I(demo="it-software", url="software-companies", name="Software & IT Companies", short="Software Company", singular="software company",
  kf="service pages, case studies, engagement models and consultation booking",
  intro="Clients hire a software partner on evidence: past work, clear process and communication. A software company website should explain services in business terms, show case studies and make a first discussion easy to schedule.",
  queries=["software development company Thrissur", "mobile app developers Kochi", "custom ERP development Kerala", "website development company Kozhikode", "AI solutions for business India"],
  needs=[("Service pages by need", "Web apps, mobile apps, ERP, cloud and AI, each described by the business outcome."),
         ("Case studies", "Problem, solution and result, with permission and honest metrics."),
         ("Engagement models", "Fixed price, dedicated team and retainer options explained."),
         ("Technology and process", "Stacks you use and how you run sprints and communicate."),
         ("Consultation booking", "A form that captures project type, budget range and timeline."),
         ("Security and IP", "State how you protect confidentiality and ownership of code.")],
  mistakes=[("Listing only technologies", "Clients buy outcomes. Lead with the problems you solve."),
            ("No evidence of work", "Add at least a few case studies, even for smaller projects."),
            ("A slow, heavy website", "A technology company's site is its own proof. Keep it fast and clean.")],
  faq=[("How much does a software company website cost in Kerala?", "A software company website with service pages, case studies and a consultation form typically costs ₹12,000 to ₹25,000 with Qrenzy, and a one-page version starts at ₹5,000."),
       ("What pages does an IT company need?", "Home, services, case studies, about the team, careers if hiring, contact and a short FAQ. A blog is optional but helpful for search."),
       ("How can a software firm get leads from its website?", "Clear service pages, genuine case studies, a fast site and Google Business Profile for local searches work together. Results depend on competition and cannot be guaranteed."),
       ("Can the website include an AI chatbot?", "A chatbot can be added as a separate custom option. The standard website uses WhatsApp and forms for enquiries.")],
  related=["corporate-b2b", "ecommerce", "manufacturing"])

I(demo="fashion", url="fashion-boutiques", name="Fashion Boutiques", short="Boutique", singular="fashion boutique",
  kf="collection pages, lookbooks, custom tailoring information and WhatsApp shopping",
  intro="Fashion shoppers respond to visuals and convenience. A boutique website should present collections in a clean lookbook, explain tailoring and alterations and let shoppers ask about a piece with one tap.",
  queries=["boutique in Thrissur", "designer sarees Kochi", "bridal lehenga near me", "custom tailoring Kozhikode", "ethnic wear for women Kerala"],
  needs=[("A clean lookbook", "Consistent, well-lit photos grouped by category and occasion."),
         ("Ask about this outfit", "A WhatsApp button on each collection that carries the design name."),
         ("Custom tailoring details", "Process, timelines and measurements, explained simply."),
         ("Size and fit guidance", "A short guide reduces returns and uncertainty."),
         ("Delivery and returns", "State shipping, cash-on-delivery and exchange policies."),
         ("Store details", "Address, map and timings for shoppers who want to visit.")],
  mistakes=[("Inconsistent photography", "Mixed lighting and backgrounds make a boutique look less premium."),
            ("No price or size information", "Shoppers leave when they cannot tell if a piece suits their budget or size."),
            ("Hidden return policy", "Clear exchange terms increase confidence to order remotely.")],
  faq=[("How much does a boutique website cost in Kerala?", "A boutique website with collections, a lookbook and WhatsApp ordering typically costs ₹12,000 to ₹25,000 with Qrenzy depending on the number of collections, and a one-page version starts at ₹5,000."),
       ("Can a boutique sell directly on the website?", "Our standard website shows collections and takes enquiries on WhatsApp. If you want a full online store with payments, see our online store option."),
       ("How many photos should each collection have?", "Start with 8 to 12 strong photos per collection. Quality and consistency matter more than quantity."),
       ("Is Instagram enough for a boutique?", "Instagram is great for discovery, but a website gives permanent pages that can rank on Google for searches like designer sarees in your city.")],
  related=["jewellery", "beauty", "ecommerce"])

I(demo="ecommerce", url="online-stores", name="Online Stores & Product Sellers", short="Online Store", singular="online store",
  kf="a product catalogue, ordering on WhatsApp, delivery and returns information",
  intro="Online shoppers need to trust a seller they have not met. A small online store should show products clearly, explain delivery and returns honestly and make ordering simple, even if orders begin on WhatsApp.",
  queries=["buy Kerala spices online", "handmade products online India", "gift hampers Kerala", "organic products home delivery Thrissur", "wholesale supplier Kerala"],
  needs=[("Clear product pages", "Photos, size, weight, price and a short honest description for each product."),
         ("Order on WhatsApp or checkout", "Start with WhatsApp ordering and add payments when volume grows."),
         ("Delivery and shipping info", "Charges, timelines and areas served, stated plainly."),
         ("Returns and support", "Return conditions and a contact point for problems."),
         ("Seller details", "Business name, address and contact, as expected on online sellers' sites."),
         ("Reviews and social proof", "Genuine customer feedback shown with permission.")],
  mistakes=[("No delivery or return policy", "Shoppers abandon when they cannot tell what happens if something goes wrong."),
            ("Poor product photos", "Photos decide purchases. Use clear images on a plain background."),
            ("Pretending to be bigger", "Be honest about being a small seller. Authenticity builds trust.")],
  faq=[("How much does an online store website cost in Kerala?", "A product catalogue website with WhatsApp ordering typically costs ₹12,000 to ₹25,000 with Qrenzy depending on the number of products. A full store with online payments and inventory is a custom project that we quote separately."),
       ("Can customers pay online on the website?", "Our standard catalogue takes orders on WhatsApp. Online payments and a shopping cart need a store platform, which we can set up as a custom project."),
       ("What legal pages should an online seller have?", "At least terms, privacy, shipping and return policies and your seller contact details. Check current e-commerce rules for what applies to your business."),
       ("Can the site help with Google Shopping?", "A product catalogue with structured data can be a starting point, but Google Shopping needs a merchant account and feed. We can advise if you want to pursue it.")],
  related=["fashion", "jewellery", "corporate-b2b"])

I(demo="corporate-b2b", url="b2b-and-corporate-services", name="B2B & Corporate Service Providers", short="B2B Company", singular="B2B service company",
  kf="service pages, sector expertise, proposal requests and credibility signals",
  intro="Business buyers research suppliers before they ever call, and they look for clarity on what you do, who you serve and how you work. A B2B company website should explain services plainly, show experience and invite a proposal request.",
  queries=["business consultants in Thrissur", "payroll outsourcing Kochi", "company registration services Kerala", "HR consultancy Kozhikode", "corporate training providers near me"],
  needs=[("Service pages by buyer need", "Describe each service by the problem it solves and who it is for."),
         ("Sectors and experience", "Industries you work with and the types of companies you have helped."),
         ("How you work", "Scoping, proposal, onboarding and reporting, explained in simple steps."),
         ("Proposal request", "A form that captures company size, requirement and timeline."),
         ("Credibility", "Team profiles, years in business and client notes shown with permission."),
         ("Contact for decision-makers", "Direct, professional contact details.")],
  mistakes=[("Generic 'we do everything' messaging", "Specificity wins B2B trust. Focus on a few services and sectors."),
            ("No sign of real clients", "Add logos, case notes or testimonials with permission."),
            ("Contact form with too many fields", "Ask only what you need to schedule the first call.")],
  faq=[("How much does a B2B company website cost in Kerala?", "A B2B services website with service pages, sector pages and a proposal form typically costs ₹12,000 to ₹25,000 with Qrenzy, and a one-page version starts at ₹5,000."),
       ("What should a B2B website include?", "Services, sectors served, process, team, client evidence, contact details and a proposal request form."),
       ("Can the website generate B2B enquiries?", "Yes, when it explains services clearly and makes enquiring easy. Results depend on your market and promotion, and cannot be guaranteed."),
       ("Do B2B companies need case studies?", "They help a lot. Even a few short, honest case studies show buyers how you work and what results to expect.")],
  related=["accounting", "it-software", "manufacturing"])

I(demo="finance-insurance", url="insurance-and-finance-advisors", name="Insurance & Finance Advisors", short="Insurance Advisor", singular="insurance and finance advisory",
  kf="product explanations, planning guides, claim support and free-review requests",
  intro="People approach an insurance or finance advisor for peace of mind, so trust and clarity come before products. An advisor's website should explain options in plain language, show credentials and make a free review easy to request.",
  queries=["insurance advisor in Thrissur", "health insurance plans Kochi", "mutual fund SIP advisor Kerala", "term insurance near me", "home loan assistance Kozhikode"],
  needs=[("Plain-language product pages", "Term, health, motor, SIP and loans explained for ordinary families."),
         ("Credentials and registrations", "Display your licence, registration numbers and affiliations as required."),
         ("Planning guides", "Short guides on goals such as education, home and retirement."),
         ("Free review request", "A form that captures needs and existing cover on WhatsApp."),
         ("Claims support explanation", "Describe how you help when a claim arises."),
         ("Required disclaimers", "Include the risk and regulatory notices that apply to your products.")],
  mistakes=[("Promising returns", "Avoid return guarantees and misleading comparisons. Follow regulator and distributor guidelines."),
            ("Product-first messaging", "Start with the family's goal and then explain the product."),
            ("Missing registration details", "Display the registration information regulators expect.")],
  faq=[("How much does an insurance advisor website cost in Kerala?", "An advisor website with product pages, planning guides and a review form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("What disclaimers should a finance website show?", "The required regulatory and risk notices for your products, plus your registration details. Check current IRDAI, SEBI and AMFI guidelines for what applies to you."),
       ("Can clients request a free policy review online?", "Yes. The form opens WhatsApp with their needs filled in, and you reply with the next steps. Personal documents should be shared privately, not on the website."),
       ("Can an advisor show past returns?", "Be very careful. Regulators restrict how performance is presented, so show only what is permitted with the required disclosures.")],
  related=["accounting", "legal", "real-estate"])

I(demo="legal", url="law-firms-and-advocates", name="Law Firms & Advocates", short="Law Firm", singular="law firm",
  kf="practice areas, advocate profiles, a confidential enquiry path and informational content",
  intro="People looking for a lawyer are often anxious and want clarity and discretion. A law firm's website should present practice areas and advocates professionally, offer informational guidance and provide a discreet way to ask for a consultation, within the rules that govern advocates.",
  queries=["advocate in Thrissur", "property lawyer Kochi", "cheque bounce case lawyer Kerala", "family court advocate Kozhikode", "NRI legal services India"],
  needs=[("Practice areas in plain language", "Describe the matters you handle and the questions people have."),
         ("Advocate profiles", "Names, qualifications, enrolment and courts of practice."),
         ("Informational guides", "Explain common processes such as property verification, without promising outcomes."),
         ("A discreet enquiry path", "A short form or call request that does not ask for sensitive details."),
         ("Location and courts", "Address, map and the courts you appear in."),
         ("Compliance with advocate rules", "Advocates in India are bound by Bar Council rules on advertising. Keep the site informational and check the current rules.")],
  mistakes=[("Claiming success rates or comparing with other lawyers", "This can breach professional rules. Stay factual and informational."),
            ("Asking for case details in a form", "Keep first contact simple and move sensitive details to a private conversation."),
            ("Legal jargon", "Write for a worried client. Clear guidance builds trust.")],
  faq=[("How much does a law firm website cost in Kerala?", "A law firm website with practice areas, advocate profiles and a consultation form typically costs ₹12,000 with Qrenzy, and a one-page version starts at ₹5,000. First-year domain and hosting are included."),
       ("Can advocates have a website in India?", "Yes, but advocates are bound by Bar Council of India rules on advertising and solicitation. The website should be informational, and you should check the current rules before publishing."),
       ("What can a law firm website safely include?", "Names and qualifications, practice areas, contact details, courts and informational guides. Avoid success claims, client testimonials about results and comparisons."),
       ("Can clients contact the firm privately?", "Yes. The enquiry opens WhatsApp or a call request, and we recommend asking for sensitive details only in a private conversation.")],
  related=["accounting", "finance-insurance", "real-estate"])
